### ISSUE TITLE
MIME type for OpenCL source code?

### ISSUE THREAD

**Issue by aaronpuchert** [KhronosGroup/OpenCL-Docs#1]
Recently, OpenCL C source code [was registered](https://cgit.freedesktop.org/xdg/shared-mime-info/commit/?id=4ab969c398671c519a10a601ad3eeb46f04361de) in freedesktop.org's `shared-mime-info` as `text/x-opencl-src`. (The `x-` prefix makes it a nonstandard extension.) The [freedesktop.org](https://www.freedesktop.org/wiki/) project maintains common components shared by all Linux desktops.

Since OpenCL C is based on C, which has type `text/x-csrc`, we wondered over [at KDE](https://phabricator.kde.org/D5621) if it shouldn't rather be `text/x-opencl-csrc`. Especially since there is also OpenCL C++. Does Khronos have a position on this?

Text editors and IDEs need a way to recognize the language of a given source code file, and the usual way to do this is via MIME types.

(Originally opened as KhronosGroup/OpenCL-Registry#27, but I was told it rather belongs here.)

**Comment by kepatil** [comment]
@aaronpuchert The OpenCL working group discussed this briefly and there were no strong opinions about the mime types. Looks like text/x-opencl-csrc is the most logical choice.

**Comment by aaronpuchert** [comment]
Thanks for the answer! I'm going to push for the necessary changes.
