### ISSUE TITLE
Update refpages to match latest API spec update

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenCL-Docs#102]
Working through #99 I realized that there seem to be a lot of missing HTML anchors in the 2.2 API spec in the registry, which AFAIK was put there in https://github.com/KhronosGroup/OpenCL-Registry/pull/60 . As a result, links from the refpages like https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_API.html#clGetDeviceIDs , which should open on the clGetDeviceIDs function, just open at the start of the spec.

I'm not sure what's caused this. The anchors come from the asciidoctor fragments built from cl.xml automatically, and I've no idea why they wouldn't propagate through to the output - maybe there was something odd about the toolchain, or some unusual options passed in the build? A spec I just built from OpenCL-Docs master branch doesn't suffer this problem. @mkinsner , I think this was your PR - do you recall anything unusual about generating the spec?

@bashbaug I think the best course of action would be to regenerate a spec from the last approved commit to OpenCL-Docs, ensure the anchors are present, and update the registry. Could you give that a try? If not, could you point me at the commit to do this from? Presumably current master, but I'm not keeping up with OpenCL WG activity so am unsure. Probably the other specs should be rebuilt at the same time, to be on the safe side.

**Comment by mkinsner** [comment]
We don't think the anchors were merged as of the most recent maintenance release.  I have the action to push a new maintenance version, including the anchors.

**Comment by oddhack** [comment]
Spec has been updated; need to update refpages now.

**Comment by oddhack** [comment]
This is fixed. I had to push a couple of minor changes to the Makefile to properly regenerate the refpages - the renaming of files in api/ to .asciidoc wasn't reflected in the refpage extraction process.
