### ISSUE TITLE
geometric functions and rounding modes

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#1024]
The section text for "geometric functions" currently contains the lines ([link](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#geometric-functions)):

> The built-in geometric functions are implemented using the round to nearest even rounding mode. The built-in geometric functions may be implemented using contractions such as mad or fma.

This text has been around since OpenCL 1.0.

Without knowing the exact operations that are performed though, and the order in which they are performed, it's not clear how this information is useful or actionable.  Can it be removed?

Note:
* We do describe accuracy requirements for these geometric functions.
* We do not have similar text in the OpenCL SPIR-V environment spec, though we do in the OpenCL extended instruction set ([link](https://registry.khronos.org/SPIR-V/specs/1.0/OpenCL.ExtendedInstructionSet.100.html#_a_id_geometric_a_geometric_instructions)).
* The section text for "common functions" contains similar text as well - can it also be removed ([link](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#common-functions))?

**Comment by jlewis-austin** [comment]
I agree both of the original statements are unnecessary if none of the geometric functions are specified as correctly rounded. Any operator with a non-zero ULP spec is fair game for whatever implementation that meets the spec.  Nothing should be said about implementation details.

**Comment by bashbaug** [comment]
Action item: file an issue about invariance across calls before closing.

**Comment by bashbaug** [comment]
I created an issue about invariance, as discussed, so closing this issue.
