### ISSUE TITLE
Handling of VkSubResourcelayout offset when importing Vulkan images through cl_khr_external_memory

### ISSUE THREAD

**Issue by bcalidas** [KhronosGroup/OpenCL-Docs#1040]
When importing linear Vulkan images it is possible that the VkSubResourcelayout structure associated with the image has a non zero offset member.  Since cl_khr_external_memory does not accept an offset, it is implicit that in such cases the offset member  in VkSubResourcelayout  must be zero.  Would it make sense to clarify the offset handling more explicitly for such cases.
The PR for this clarification is -  https://github.com/KhronosGroup/OpenCL-Docs/pull/1039
For image layouts that are not linear, explicitly handling an offset gets tricky. An inference mechanism would work better in such cases.
Going forward,  introducing an external memory handle type that is linked to inferring images exported from Vulkan, could be a good solution.

**Comment by bcalidas** [comment]
For reference , here is the Vk Subresource layout. -

typedef struct VkSubresourceLayout {
  VkDeviceSize offset;
  VkDeviceSize size;
  VkDeviceSize rowPitch;
  VkDeviceSize arrayPitch;
  VkDeviceSize depthPitch;
} VkSubresourceLayout;

**Comment by nikhiljnv** [comment]
Closing without adding any clarification as discussed in memory subgroup call on January 16th, 2024. The PR #1039 is already closed. Closing the issue too.
