### ISSUE TITLE
Redirect man page

### ISSUE THREAD

**Issue by Richardk2n** [KhronosGroup/OpenCL-Docs#1053]
I found man.opencl.org very useful. For a Google search with `opencl <any function in the kernel or the lib>` it is usually the top result. Recently you apparently removed this and redirected everything to https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/

I do understand, that you want to switch to this new long and cumbersome redundant URL. But why not redirect to the respective page instead of dropping everyone on the main page, which requires me to click through submenus to get where I wanted to go?

**Comment by bashbaug** [comment]
Thank you for the report - we're looking into this.

**Comment by bashbaug** [comment]
Hello and thank you for your patience.  We've been trying to get this cleaned up.

I just tried a Google search with "opencl clEnqueueNDRangeKernel" and for me at least the top link is now to:

https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/clEnqueueNDRangeKernel.html

I think this is where we'd like to end up, so this seems good.

If there are still direct links to the older man.opencl.org pages then these are still redirecting to the main page, but hopefully this is still progress.

**Comment by bashbaug** [comment]
Hello, we've made a bunch of small changes and our default search engine behavior is much better now.  The redirect still goes to the main page vs. to a subpage for any hard-coded links, but the search engines have switched to the new pages, so we are closing this issue.

Please feel free to reopen this issue or file another one if you're still encountering issues.  Thanks!
