### ISSUE TITLE
Preferred phrasing for generated extension dependencies

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenCL-Docs#1055]
Currently #950 emits version-notes for extensions which are grammatically and probably technically wrong as they look just like the core version dependencies:

> {apiname} is missing before version cl_khr_some_extension

@bashbaug what would you recommend to use when the dependency is on an extension? I'm thinking

> {apiname} requires support for <<extension_name>>

or

> {apiname} requires the <<extension_name>> extension

which are consistent with patterns in a small number of handcoded comments already present.

**Comment by bashbaug** [comment]
Including @alycm who wrote the core version dependency text and may have a stronger opinion.

I'm fine with either option.  If I had to pick I think I'd go with "{apiname} requires the <<extension_name>> extension", but it's a pretty weak preference.

Looking through the Vulkan specification it seems to use the phrasing "provided by <<extension_name>>".  Maybe we should adopt something similar, like "{apiname} is provided by the <<extension_name>> extension", or the more concise "{apiname} is provided by <<extension_name>>"?

**Comment by bashbaug** [comment]
@oddhack do you have what you need here?  Assigning back to you, for now.

**Comment by bashbaug** [comment]
Discussed four options in the March 26th teleconference:

1. {apiname} requires support for <<extension_name>>
2. {apiname} requires the <<extension_name>> extension
3. {apiname} is provided by the <<extension_name>> extension
4. {apiname} is provided by <<extension_name>>

Preference was generally for (3) or (4).  We will go with (3) for now.
