### ISSUE TITLE
Clarify behavior in case of multiple clEnqueueAcquireExternalMemObjectsKHR calls on the same cl_mem

### ISSUE THREAD

**Issue by nikhiljnv** [KhronosGroup/OpenCL-Docs#1086]
Clarify behavior in case of multiple clEnqueueAcquireExternalMemObjectsKHR calls on the same cl_mem without corresponding clEnqueueReleaseExternalMemObjectsKHR.

This came up as part of https://github.com/KhronosGroup/OpenCL-CTS/pull/1899

**Comment by nikhiljnv** [comment]
Check how implementations behave if we do multiple acquires with earlier interops (GL/DX) as well as external sharing.

**Comment by nikhiljnv** [comment]
Some options -
1. Leave the behavior as implementation defined
2. Return an error
3. Recommend acquire to be used only once, but leave multiple acquires/release behavior implementation defined.

**Comment by bcalidas** [comment]
Option 3 looks to be best.

**Comment by bashbaug** [comment]
This was fixed by #1176.  Closing.
