### ISSUE TITLE
Investigate difference between Asciidoctor 1.5.8 and 2.0.10 output

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#109]
There have been comments that Asciidoctor 2.0 has backwards incompatible changes that likely affect the OpenCL specification, e.g. the comments here: https://github.com/KhronosGroup/OpenCL-Docs/pull/75#discussion_r280960606

However, it's not clear to me what the incompatibilities are.  This is not an urgent issue, I'm not aware of us being limited by using 1.5.8.

My intent is to render with both versions in HTML and diff the output, hoping that the incidental noise level is low.

**Comment by oddhack** [comment]
There are some markup constructs we use in Vulkan which are no longer supported in 2.0, though I'm not sure if they're used in the CL specs. My recommendation is to defer a switchover - there's no obvious need to until such time in the future as some asciidoctor extension we use will no longer work with 1.5.8, and that's probably years in the future.

**Comment by alycm** [comment]
This PR updates Asciidoctor to 2.0.16 as part of a syntax highlighting upgrade: https://github.com/KhronosGroup/OpenCL-Docs/pull/691
