### ISSUE TITLE
Generic Address Space Issues

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#114]
I’ve been looking at the generic address space text in the OpenCL C spec and I think it needs some tidying up.  I also wonder if we want to move the generic address space descriptions to another spec so we’re less dependent on the OpenCL C spec – this could either be the SPIR-V environment spec or somewhere in the API spec.

Some things to fix:

> If the type of an object is qualified by an address space name, the object is allocated in the specified address name; otherwise, the object is allocated in the generic address space.

I think this is wrong – you never allocate an object in the generic address space.  This may be a copy-paste bug from an earlier spec?  It should say “global” address space for declarations at program scope, and “private” address space for everything else.

> Before referring to the region pointed to, the pointer must be associated with a named address space.

I don’t know what it means to “associate” a pointer with a named address space.

> Casting a pointer to address space A to a pointer to address space is illegal if A and B are named address spaces and A is not the same as B.

I think this is a simple one – we’re just missing a “B” in this sentence – but it should be fixed.

```c
int *foo;               // OK. foo is allocated in global address space.
                        // pointer to foo in generic address space
```

Note that this “foo” is at program scope so it’s correct that it is allocated in the global address space, but it should say that “foo points to a location in the generic address space” similar to the example below where “foo” is declared in kernel scope.

> In the example below, var is in the unnamed generic address space which gets mapped to the global or local address space depending on the result of the conditional expression.

This is incorrect – var is in the private address space.  It points to a location in the generic address space.  The location that it points to is the global address space or the local address space depending on the result of the conditional expression.

Also, I don’t think we ever say that a pointer to a location in the global address space is bitwise equivalent to a pointer to the same location in the generic address space, but I think this has to be true for SVM address equivalence to work with the generic address space.

I'll file a PR to fix these later this week, but wanted to submit an issue in case there are any comments first.  Thanks!

**Comment by b-sumner** [comment]
I agree that all the issues you found in the existing text need to be fixed.  I'm not so sure that it is true that, or we need to state that, a generic pointer to a global object has to be bitwise identical to a global pointer pointing at the same object.  Which "SVM address equivalence" do you mean?

**Comment by bashbaug** [comment]
> I'm not so sure that it is true that, or we need to state that, a generic pointer to a global object has to be bitwise identical to a global pointer pointing at the same object. Which "SVM address equivalence" do you mean?

Hi @b-sumner, here is an example to motivate why I think we may want this to be the case.  It walks a linked list constructed on the host from SVM allocations on the device.

This initial version does not use the generic address space.  Do we agree that this is a valid OpenCL 2.0 SVM kernel?

```c
struct Node {
    global struct Node* pNext;  // pointer to global address space
    uint Num;
};
kernel void WalkLinkedList( global struct Node* pHead )
{
    global struct Node* pNode = pHead;
    while( pNode ) {
        pNode->Num = pNode->Num * 2 + 1;
        pNode = pNode->pNext;
    }
}
```

If so, here is a variant that uses the generic address space instead:

```c
struct Node {
    struct Node* pNext;  // pointer to generic address space
    uint Num;
};
kernel void WalkLinkedList( global struct Node* pHead )
{
    // implicit conversion from pointer to global to pointer to generic address space:
    struct Node* pNode = pHead;
    while( pNode ) {
        pNode->Num = pNode->Num * 2 + 1;
        pNode = pNode->pNext;
    }
}
```

If we want this to be valid as well we will need bitwise equivalence between pointers to the global address space and pointers to the generic address space, since there is no implicit or explicit conversion from a pointer to the global address space to a pointer to the generic address space while walking the linked list.

**Comment by bashbaug** [comment]
I'll file another issue to track the address space equivalence questions regarding pointers to the global address space and pointers to the generic address space, since accepting #123 may close this issue.

**Comment by alycm** [comment]
https://github.com/KhronosGroup/OpenCL-Docs/pull/123 is merged so I'll close this issue.
