### ISSUE TITLE
Presubmit workflow fails on `Install required packages` stage

### ISSUE THREAD

**Issue by SunSerega** [KhronosGroup/OpenCL-Docs#1192]
I fast-forwarded `main` in my fork and got an email pointing to this:

https://github.com/SunSerega/OpenCL-Docs/actions/runs/9651543782/job/26619662691

It seems it fails to download `ghostscript` and its dependencies.

**Comment by bashbaug** [comment]
Thanks, we're looking into this.

**Comment by bashbaug** [comment]
Can you try re-triggering the build on your end?  I looked at a recent PR and it appears that CI builds are passing again, so hopefully this was just a one-time environment issue.

**Comment by SunSerega** [comment]
Alright, I guess it fixed itself. Feel free to close this if you think it doesn't make sense to investigate this issue further.

**Comment by bashbaug** [comment]
Thanks for confirming - this seems like a flaky environment problem, though it does seem to be happening more often.

If anyone is curious, we're looking at moving to a Khronos docker image for the OpenCL spec CI, which already has the right packages installed, so it should help these types of environment issues and might speed up CI a bit also.

**Comment by oddhack** [comment]
@bashbaug would you like me to make the PR for the docker image change? It's not difficult but I do have some EP in it. BTW, if we do this, expect some minor layout differences resulting from more recent asciidoctor versions used in the current image. They changed the default CSS and PDF layout options in very small ways which don't affect content, but do make direct comparisons difficult.

**Comment by oddhack** [comment]
@SunSerega this sort of transient failure happens occasionally just doing apt updates on my workstation, so no big surprise. One upside of using the Docker image is that it's a single point of failure at dockerhub rather than downloading a base OS image and then pulling dozens or hundreds of packages from multiple apt repositories, pypl, ruby gems, etc.
