### ISSUE TITLE
Macro Typos in Documentation: EPSILSON -> EPSILON

### ISSUE THREAD

**Issue by saschast** [KhronosGroup/OpenCL-Docs#1198]
https://github.com/KhronosGroup/OpenCL-Docs/blob/f37a8680e13a4ea965f33fbe3f944ca94c436705/OpenCL_C.txt#L5848
https://github.com/KhronosGroup/OpenCL-Docs/blob/f37a8680e13a4ea965f33fbe3f944ca94c436705/OpenCL_C.txt#L5919
https://github.com/KhronosGroup/OpenCL-Docs/blob/f37a8680e13a4ea965f33fbe3f944ca94c436705/OpenCL_C.txt#L5989
https://github.com/KhronosGroup/OpenCL-Docs/blob/f37a8680e13a4ea965f33fbe3f944ca94c436705/cxx/stdlib/limits.txt#L258
https://github.com/KhronosGroup/OpenCL-Docs/blob/f37a8680e13a4ea965f33fbe3f944ca94c436705/cxx/stdlib/limits.txt#L316
https://github.com/KhronosGroup/OpenCL-Docs/blob/f37a8680e13a4ea965f33fbe3f944ca94c436705/cxx/stdlib/limits.txt#L375

`FLT_EPSILSON` --> correct to `FLT_EPSILON`
`DBL_EPSILSON` --> correct to `DBL_EPSILON`
`HALF_EPSILSON` --> correct to `HALF_EPSILON`

**Comment by bashbaug** [comment]
Thanks!  We'll fix these.
