### ISSUE TITLE
Zero-width spaces in spec html

### ISSUE THREAD

**Issue by svenvh** [KhronosGroup/OpenCL-Docs#1214]
Various function names in the spec have zero-width spaces in them, e.g. `get_&#8203;sub_&#8203;group_&#8203;size`. It seems this was done deliberately in #950 :
```
+// Note: the Unicode "zero width space" (&#8203;) is used in some places to
+// cause long function names to break much more sensibly.
```

The zero-width spaces end up in the rendered html, which interferes with copy/pasting a function name from the html:
- Searches for that copied function name will not match actual occurrences of that function name in for example source code files.
- Pasting the copied function name into a source file includes the zero-width spaces, which will need to be removed.

**Comment by bashbaug** [comment]
I'll fix this - this was something I did a long time ago as part of the "extended subgroups" extension spec, probably before we observed that using the unicode "zero width spaces" in the HTML specs has some problems (see #393),
