### ISSUE TITLE
CL_DEVICE_CORE_TEMPERATURE_ALTERA = 0x40F3 - Invalid Value

### ISSUE THREAD

**Issue by lenoln** [KhronosGroup/OpenCL-Docs#122]
Hi, I'm trying to use this extension in my wrapper, but I always receive 'invalid value exception'. Somebody can help me?
` CLError err = OpenCL.clGetDeviceInfo(device, CLDeviceInfo.CL_DEVICE_CORE_TEMPERATURE_ALTERA, 0, IntPtr.Zero, ref param_value_size_ret)`

**Comment by oddhack** [comment]
@lenoln OpenCL-Registry is just a publication mechanism., not a working repo. Try in OpenCL-Docs instead.

**Comment by lenoln** [comment]
Sorry, and Thank you :D

**Comment by mkinsner** [comment]
Closing because I suspect that the extension wasn't supported on the device being used.  Please reopen if that isn't right, or if there are related questions!
