### ISSUE TITLE
Consider Disabling Asciidoctor Footer to Reduce Diffs

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#1222]
The SPIR-V working group is considering a PR that disables the asciidoctor "footer" to reduce diffs.

https://github.com/KhronosGroup/SPIRV-Registry/pull/268

We should consider doing the same in the OpenCL spec toolchain as well.  I know this will simplify reviews for the generated reference pages considerably, for example.

@oddhack, is this somethign that's been considered for other working groups (Vulkan)?

**Comment by oddhack** [comment]
Vulkan has not considered this. It is not causing issues for us that anyone has complained about, to my knowledge. SPIR-V might be doing something more aggressive in CI.

**Comment by oddhack** [comment]
To be clear, it's a perfectly reasonable thing to do if you're so inclined. It's just a stylistic point. For Vulkan, essentially every MR that isn't just about the toolchain is going to generate HTML diffs.
