### ISSUE TITLE
CPUs not showing up as opencl devices

### ISSUE THREAD

**Issue by goofyseeker311** [KhronosGroup/OpenCL-Docs#1270]
by the specification, all cpus (intel, amd, x86) should appear valid opencl devices.
nvidia gpus and amd igpu show up fine, but none of AMD ryzed 5000 series cpus show up in a debug listing.

is this a specification failure, or windows failure, drivers failure or platform vendor manufacturer problem?

self-answer: downloading and installing the intel opencl runtime for cpu works for amd cpus too.
https://www.intel.com/content/www/us/en/developer/articles/technical/intel-cpu-runtime-for-opencl-applications-with-sycl-support.html

**Comment by Oblomov** [comment]
pocl is another OpenCL platform that support CPUs. Mesa's rusticl with llvmpipe IIRC also does it. In general, whether or not CPUs show as device depends entirely on which platforms are installed, just like for any other device. It doesn't nor shouldn't depend on the OpenCL library itself.

**Comment by goofyseeker311** [comment]
opencl support should be on by default, not requiring any drivers installs

**Comment by goofyseeker311** [comment]
well better have a default driver than no driver.

**Comment by goofyseeker311** [comment]
A side note: should C99 array default initializers work, like:

```
float arr[5] = { HUGE_VALF};
```

is not working, only first element gets set to the specified value, and all the rest are set to zero.
also applies to vectors, only first element gets set to the initializer value.

**Comment by goofyseeker311** [comment]
A side note: barrier() is not sufficient for synchronized memory conditional write access by multiple workers at same time (thing z-buffer test and update).

**Comment by goofyseeker311** [comment]
another note: even if using struct and kernel function variable __attribute__ ((packed), an array pointer will not properly assign to the struct array pointer, so that structvar[x].element1 (etc), would work properly. ie assigning a float array to similarly packed struct from global variable. local test array pointer assigns properly to a local struct pointer, and each struct in the array is separately properly accessible.

**Comment by goofyseeker311** [comment]
any mention of "if one work item encounters [something], all work items need to encounter [something]" should be not necessary at all, because work items should all be independent from each other, in run-time, not in any kind of "warp" or default grouping.

this complicates fences and barriers logic, and if statement logic. unnecessarily.
