### ISSUE TITLE
Scope of invalid object detection

### ISSUE THREAD

**Issue by nikhiljnv** [KhronosGroup/OpenCL-Docs#1275]
The spec says https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#cl_khr_external_semaphore
clEnqueueWaitSemaphoresKHR returns one of the following errors:

    CL_INVALID_COMMAND_QUEUE if command_queue is not a valid command-queue.

There was a test added (seems like it is not there after recent changes). But, see line number 75 through 114 for test WaitInvalidCommandQueue here
https://github.com/KhronosGroup/OpenCL-CTS/commit/340b7c956a093cfe42e56ecc4e893ddb33877798#diff-9db37a7bea13efb24c41e17c056e5b880f171f6cc4b140b76bdd449de26bb495R114

The test tried to pass a command queue from a different device of a different platform to test invalid command queue scenario.
Not sure if this was discussed somewhere already, but that brings up a question on what is the scope of invalid pointers the implementations are expected to detect the validity of the command-queue (may be applicable to other scenarios for other OpenCL objects too) in order to return the expected error.

**Comment by bashbaug** [comment]
See related discussion in https://github.com/KhronosGroup/OpenCL-Docs/issues/482, especially https://github.com/KhronosGroup/OpenCL-Docs/issues/482#issuecomment-795685410.

The discussion in the issue led to the "valid object" definition in the OpenCL spec:
https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#valid-object-definition

In short: the only invalid command-queue we should be testing for is a `NULL` command-queue.

**Comment by nikhiljnv** [comment]
I think the below line from  https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#valid-object-definition covers the scenario and should be good enough for guidance.

"An OpenCL implementation must check for a NULL object to determine if an object is valid. The behavior for all other invalid objects is implementation-defined."

Closing the issue.
