### ISSUE TITLE
Add address space qualifier to OpenCL C++

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#13]
In OpenCL C++ explicit address spaces have to be used with classes. This might prevent porting existing OpenCL C code to C++ because address spaces will have to be rewritten.

On the other hand we allow address spaces with `__` prefix in Clang as toolchain only feature, because it's the cheapest way to implement address space classes correctly.

Would it make sense to add the address spaces into OpenCL C++ at least with __ prefix? Without the prefix it probably won't work unfortunately due to the conflict with C++ `private` class access modifier.

**Comment by keryell** [comment]
Yes, that seems like a useful OpenCL Next extension.

**Comment by keryell** [comment]
I have the feeling that with this extension it would allow an implementation of OpenCL C++ address-space classes as plain C++ classes.
The main problem is if we want some error feedback talking about the higher-level OpenCL C++ address-space classes instead of the gory implementation details using `__global` and so on, it has to be understood at the Clang level...

**Comment by AnastasiaStulova** [comment]
If SYCL had language extensions then this would be resolved easily. But considering that SYCL is said to be a library implementation it's not uncommon that developers will get lower-level errors that come from the internals of libraries if they violate API rules. I am not saying this is helpful! At least as soon as the content of errors is documented somewhere it should be possible to dig out details.

One problem I see is that if errors don't come from the standard C++ compiler but in the case of address spaces from the OpenCL compiler. That breaks the overall image of SYCL to be extension free C++ library. Then suddenly the errors that are given by the compiler are not compliant to anything in ISO C++.

I think what might help to say to the developers that SYCL is C++ syntax with modified semantic?

**Comment by kpet** [comment]
Closing this issue as there are no planned updates to the OpenCL C++ specification. Users of OpenCL interested in C++ support are encouraged to look at C++ for OpenCL:
- Language documentation: https://github.com/KhronosGroup/OpenCL-Docs/tree/master/cxx4opencl
- Clang support: https://clang.llvm.org/docs/UsersManual.html#c-for-opencl

Using the [SPIRV-LLVM-Translator](https://github.com/KhronosGroup/SPIRV-LLVM-Translator), it is possible to compile C++ for OpenCL down to SPIR-V modules that can be consumed by any OpenCL implementation that supports SPIR-V.
