### ISSUE TITLE
Clarifications to address spaces in C++ cast operators

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#14]
**A.** I believe we need some clarifications regarding AS in cast operations: `static_cast,` `const_cast`, `reinterpret_cast`. I assume they can't cast between different address space pointers? Is there any change to C++ rules needed for those wrt address spaces?

Also I believe we should add a separate cast operator for address space conversions only (let's say `asptr_cast`). By analogy to `const_cast` that only allows changing `const` qualifier, it would only allow the translation of address spaces. If combined translations are required multiple operators are to be used:
`private<D>& v; static_cast<B&>(asptr_cast<D&>(v))`

Regarding address space casts in s3.4.4:

**B.** Is `static_asptr_cast` expected to comply to the rules from **s5.2.9 [expr.static.cast]** of C++ spec for the pointee type transitively i.e. T from OpenCL = T from C++, U from OpenCL = v from C++?

**C.** Is `reinterpret_asptr_cast` expected to comply to the rules from **s5.2.10 [expr.reinterpret.cast]** of C++ spec for the pointee type transitively i.e. T from OpenCL = T from C++, U from OpenCL = v from C++?

**D.** Would it make sense to add a special `const_asptr_cast` too? I don't think `const_cast` will perform cast for the pointee type of the address space pointer class. I.e would `private_ptr<const int> v; const_cast<private_ptr<int>>(v)>` work correctly for const here?

Regarding implicit conversions:

**E.** Symmetrically to `dynamic_asptr_cast`, would it make sense to allow implicit conversions from generic address space pointers to address space pointer classes (except for constant)? This would have to be done for assignment, comparisons, copy/move constructors?

**Comment by kpet** [comment]
Closing this issue as there are no planned updates to the OpenCL C++ specification. Users of OpenCL interested in C++ support are encouraged to look at C++ for OpenCL:
- Language documentation: https://github.com/KhronosGroup/OpenCL-Docs/tree/master/cxx4opencl
- Clang support: https://clang.llvm.org/docs/UsersManual.html#c-for-opencl

Using the [SPIRV-LLVM-Translator](https://github.com/KhronosGroup/SPIRV-LLVM-Translator), it is possible to compile C++ for OpenCL down to SPIR-V modules that can be consumed by any OpenCL implementation that supports SPIR-V.
