### ISSUE TITLE
Alignment of Types for SPIR-V Kernels

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#147]
The OpenCL C spec has a section describing "Alignment of Types":

https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_C.html#alignment-of-types

This section describes assumptions compilers can make for OpenCL C kernels regarding alignments of loads and stores and alignments of kernel arguments.

It's possible I'm just looking in the wrong places, but I don't see similar text describing similar assumptions compilers can make for SPIR-V kernels, even though though I think this is intended and desirable.

Notes:

* I think this text probably belongs in the SPIR-V environment spec.
* There is an [Alignment Decoration](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#Decoration) in the SPIR-V spec, but I think this is intended to be used for specific alignments (e.g. `__attribute__((aligned(16)))`) and not to communicate default alignment assumptions.

**Comment by kpet** [comment]
I was about to file the same issue before I found this one. Agree this needs doing.

**Comment by bashbaug** [comment]
Fixed by #527.
