### ISSUE TITLE
Deducing address space for 'this' expr 

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#15]
`this` expr represents a pointer to an object. This is an invisible parameter passed to all methods and also can be used inside them to refer to the current object. However, the definition of the method is parsed and resolved (e.g. generated) independently of an object instantiation and therefore it's not known beforehand to which address space should the pointer of `this` point to.

Situation is more complicated if objects are created in different ASes: e.g. `constant` and `private`. 

The solution could be to use `generic` address space and then emit the address space conversion when passing the object into the method that expects `generic` address space pointer. This won't work for `constant` AS though due to disallowed conversion to `generic`.

Example:
```
void foo::bar(){this;}
...
constant foo f;
f.bar();// Error: bar(&f), but bar expects bar(generic foo *)
```

The [prototype compiler](https://github.com/KhronosGroup/SPIR/commit/0cfb6f7533d42ae3398a8574efd8abbdac88ac44) has a solution to this - overloading methods based on address space method qualifier. If the qualifier is present on the method then compiler will check against an address space of an object then resolving overloads of that method.

Example:
```
class foo
{
public:
  void bar() __private; // implies bar(__private foo*)
  void bar() __constant; // implies bar(__constant foo*)
};
```
The problem is that `this` is an invisible parameter to all methods and special operators including constructors, destructor, assignments, etc which makes it quite popular feature.

It is not very clear how to workaround the problem in tools without this language extension. The general idea of C++/C language is that everything is to be known before the current context. This allows efficient implementation of parser that doesn't have to keep entire AST in order fully resolve the expressions and generate IR. This is how Clang works for example. The complexity of changing it is very unclear.

Perhaps if this is left to the programmer, they can use templates/microprogramming. However, it doesn't feel to be a good solution.

**Comment by keryell** [comment]
Do we have also the same issue with the constructors, requiring 1 overload per constructor and per address space?

**Comment by keryell** [comment]
@agozillon I am interested by some solution for triSYCL too, since it is not implemented yet...

Probably a solution not requiring a `__generic` address space is better since:
- it would allow a C++ incremental extension for OpenCL Next on top of 1.x features (I am hearing TI requests here);
- it would work on SYCL 1.2.1 which does not have `__generic` address space.

For someone from AMD: how does it work with HCC? Do they have an equivalent of generic address space?

**Comment by AnastasiaStulova** [comment]
@keryell I raised another issue to track situation w implicit operators: https://github.com/KhronosGroup/OpenCL-Docs/issues/18

At least it doesn't need any syntax change I believe.

**Comment by kpet** [comment]
Closing this issue as there are no planned updates to the OpenCL C++ specification. Users of OpenCL interested in C++ support are encouraged to look at C++ for OpenCL:
- Language documentation: https://github.com/KhronosGroup/OpenCL-Docs/tree/master/cxx4opencl
- Clang support: https://clang.llvm.org/docs/UsersManual.html#c-for-opencl

Using the [SPIRV-LLVM-Translator](https://github.com/KhronosGroup/SPIRV-LLVM-Translator), it is possible to compile C++ for OpenCL down to SPIR-V modules that can be consumed by any OpenCL implementation that supports SPIR-V.
