### ISSUE TITLE
Inconsistent options definition in clBuildProgram and clCompileProgram

### ISSUE THREAD

**Issue by sanguinariojoe** [KhronosGroup/OpenCL-Docs#158]
The `options` argument for `clBuildProgram` (since OpenCL 1.1) and for `clCompileProgram` methods is defined as follows:

>  options
>     A pointer to a null-terminated string of characters that ...

However, in `clCompileProgram` the following chunk of example code  is provided:

```
clCompileProgram(program_A,
                 0, NULL, // num_devices & device_list
                 NULL, // compile_options
                 2, // num_input_headers
                 input_headers,
                 input_header_names,
                 NULL, NULL); // pfn_notify & user_data
```

where `options` takes a NULL value, which is not a pointer to a null-terminated string

**Comment by alycm** [comment]
Hello, thank you for the report.  I believe that the parameter description is incomplete and that the sample is legal.  Passing `NULL` to options is the same as passing `""`.

The CTS passes `NULL` in this situation a lot, so it is clearly okay for all implementations, an example:

The `conformance_test_basic` test for `if` does not specify the build option parameter to `create_single_kernel_helper` [here](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/basic/test_if.c#L126), a default value of `NULL` has been specified in the header [here](https://github.com/KhronosGroup/OpenCL-CTS/blob/0d96c198ee533616565901b675d8fc0c5a5b6c38/test_common/harness/kernelHelpers.h#L75), and this value reaches `clBuildProgram` [here](https://github.com/KhronosGroup/OpenCL-CTS/blob/0d96c198ee533616565901b675d8fc0c5a5b6c38/test_common/harness/kernelHelpers.c#L845).

I will modify the description of `options` to describe the behaviour of `NULL`.

**Comment by sanguinariojoe** [comment]
I'm agree, `NULL` seems totally fair.

Thank you!
