### ISSUE TITLE
[C++ for OpenCL] Document the language version macro?

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#168]
When compiling C++ for OpenCL Clang currently defines an `__OPENCL_CPP_VERSION__` macro. Do we want to describe this in the documentation to enable users to rely on it?

**Comment by AnastasiaStulova** [comment]
It is added in https://github.com/KhronosGroup/OpenCL-Docs/pull/262/files

**Comment by kpet** [comment]
@AnastasiaStulova Any reason you didn't close the issue?
