### ISSUE TITLE
Specify semantics of any() and all() for scalar inputs

### ISSUE THREAD

**Issue by StuartDBrady** [KhronosGroup/OpenCL-Docs#178]
The OpenCL C specification describes the `any()` and `all()` built-in functions as follows:

Function | Description
-- | --
int **any**(igentype _x_) | Returns 1 if the most significant bit in any component of _x_ is set; otherwise returns 0.
int **all**(igentype _x_) | Returns 1 if the most significant bit in all components of _x_ is set; otherwise returns 0.

This implies that the semantics of these functions have only been defined for vector types. What are the semantics for scalar types?

I would expect that `any(0) == false`, `all(0) == false`, `any(-1) == true` and `all(-1) == true)`, but it is not clear what `any(1)` and `all(1)` would evaluate to. Should these compile? (Scalar types are listed for _igentype_ in the second paragraph of _6.13.6 Relational Functions_.)

**Comment by bashbaug** [comment]
FWIW, for scalar types we will return 1 if the most significant bit of the scalar input is set; otherwise we return 0, for both `any` and `all`.  It looks like the SPIR-V LLVM Translator does the same:

https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/lib/SPIRV/OCL20ToSPIRV.cpp#L664

This means that both `any(1)` and `all(1)` return zero (false).

I guess this could be clarified to say something like:

> Returns 1 if the most significant bit of _x_ (for scalar inputs) or any component of _x_ (for vector inputs) is set; otherwise returns 0.

Does that sound better?

**Comment by StuartDBrady** [comment]
> FWIW, for scalar types we will return 1 if the most significant bit of the scalar input is set; otherwise we return 0, for both `any` and `all`. It looks like the SPIR-V LLVM Translator does the same:
> 
> https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/lib/SPIRV/OCL20ToSPIRV.cpp#L664

FWIW, clspv does the same, too.

> This means that both `any(1)` and `all(1)` return zero (false).

Agreed—that is what current implementations do, and what the conformance tests check for.

> I guess this could be clarified to say something like:
> 
> > Returns 1 if the most significant bit of _x_ (for scalar inputs) or any component of _x_ (for vector inputs) is set; otherwise returns 0.
> 
> Does that sound better?

That does sound better. However, I wonder if we should also deprecate the use of `any()` and `all()` with a scalar argument, as the semantics seem quite surprising.

**Comment by mantognini** [comment]
> I wonder if we should also deprecate the use of any() and all() with a scalar argument, as the semantics seem quite surprising.

I believe this would be something good to do, esp. before 3.0 final ratification.

**Comment by bashbaug** [comment]
#306 clarified the scalar behavior.  Did we want to consider deprecating the scalar functions in OpenCL C 3.0?  If so, please re-open this issue for more discussion - thanks!

**Comment by mantognini** [comment]
I personally haven't heard any argument against deprecation so I feel it should be considered.

**Comment by AnastasiaStulova** [comment]
Discussed on the teleconf Jun 23:
- Need a conclusive summary of the problem to help deciding whether depreciation is a way forward.

**Comment by mantognini** [comment]
My take and summary on this is:

The difference in semantics between scalar and vector overloads of these two builtin functions is non-obvious, error-prone and therefore can hurt users. Moreover, the scalar overloads don't bring value to the language because the same functionality is available using relational operators. They should be deprecated.

Users can write more explicit code by replacing `any(scalar_value)` with `scalar_value < 0`. This clearly evaluates to `false` when `scalar_value` is, for example, `1`. On the other hand, it is non-obvious that `any(1)` evaluates to `false`. Similarly for `all`.

**Comment by StuartDBrady** [comment]
I gather there is some need for clarification on this. Put simply, in OpenCL C:

* `any(1)` evaluates to 0.
* `all(1)` evaluates to 0.

This goes against the C language's use of integers as logic values. This is more than just a convention: the C language is entirely consistent in this regard.

That this is not just a theoretical issue, either. Given variables _x_ and _y_ with an equal value:

* `any(x == y)` evaluates to 0.
* `all(x == y)` evaluates to 0.

In vanilla C, 1 is the normalized truth value. In all parts of the language that use integers to represent logic values for the operands of an operation, any non-zero value is taken as being true, and 0 is the only value taken as being false. In all parts of the language that use integers to represent logic values for the result of an operation, 1 represents true and 0 represents false.

In OpenCL C, the same applies for scalars _except_ in the `any()` and `all()` builtins. Vectors are of course different, in that the most significant bit of a vector component is generally used to determine the logic value that it represents.

Ideally, the definition of the `any()` and `all()` builtins would have been altered prior to the publication of OpenCL 1.0, so that `any()` and `all()` each compare the value that is passed to them against 0 (e.g. `int any(int i) { return !!i; }`). However, it would not be appropriate to alter the semantics of these given that the CTS has ensured that implementations provide the behavior that has been clarified previously in this issue.

My view is that it would make sense to deprecate use of the `any()` and `all()` built-ins for scalar types. This would signify that the handling of `any()` and `all()` for the built-in scalar types would be subject to change in future versions of the OpenCL C specification (versions _above_ 3.0), it would make no immediate difference to OpenCL C 3.0 implementations, or for programs written using OpenCL C 3.0.

By doing so, this would:
* signify that it would be acceptable for implementations to emit a compiler warning (or have the facility for doing so) when the `any()` or `all()` builtins are used with a scalar input,
* allow removal of support for a scalar input for the `any()` and `all()` builtins in a future version of the OpenCL C language (but _not_ in OpenCL 3.0 itself),
* and eventually, allow reintroduction of support for a scalar input for the `any()` and `all()` builtins, such that these return the normalization of the value that is passed to them, so that these may be used as a convenience in code written to use arbitrary vector widths.

**Comment by bashbaug** [comment]
Thank you both @mantognini and @StuartDBrady for the detailed explanations.  Not sure about everyone else, but I'm convinced deprecation is the right thing to do.

Spec-wise, I think the tasks are to:

* Document in the descriptions of `any()` and `all()` that the scalar inputs are deprecated in OpenCL C 3.0.
* Document in the appendix in the API spec that these built-ins are deprecated with a summary of the rationale above.

I can create a PR with these changes for any further discussion.

We should also add a deprecation message in OpenCL C 3.0 Clang, which would provide the warning behavior described above.

**Comment by bashbaug** [comment]
We discussed this issue in the June 30th teleconference and agreed to deprecate scalar inputs for these built-in functions.  We will review and merge #336, which will close this issue.

**Comment by bashbaug** [comment]
@StuartDBrady did you have any additional comments regarding #336 or are you OK to merge it?  You didn't "approve" the PR so I wanted to be sure - thanks!

**Comment by StuartDBrady** [comment]
I have approved the PR, now.
