### ISSUE TITLE
Address space of implicit operators in C++

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#18]
C++ compiler implicitly generates some operators (constructors, destructor, assignments) if they are not provided explicitly.

For OpenCL C++, we need to clarify what address spaces should be generated (both for compiler impl and kernel developers). There are a number of options:

A. We can generate operators in each address space. This will impact the binary size. However, Clang only generates operators lazily based on their use. At least we won't end up with operators over unused address spaces.

B. We can provide operators with `generic` address space only, keeping binary size unchanged at a cost of dynamic address space translation. However, it won't work for `constant` AS. If `constant` AS is needed (or any other than `generic` AS to avoid dynamic AS translation), they would have to be explicitly defined in the source code.

C. We can generate operators in both `generic` and `constant` ASes. If other address space are needed to avoid dynamic translation they would have to be defined explicitly.

**Comment by kpet** [comment]
Closing this issue as there are no planned updates to the OpenCL C++ specification. Users of OpenCL interested in C++ support are encouraged to look at C++ for OpenCL:
- Language documentation: https://github.com/KhronosGroup/OpenCL-Docs/tree/master/cxx4opencl
- Clang support: https://clang.llvm.org/docs/UsersManual.html#c-for-opencl

Using the [SPIRV-LLVM-Translator](https://github.com/KhronosGroup/SPIRV-LLVM-Translator), it is possible to compile C++ for OpenCL down to SPIR-V modules that can be consumed by any OpenCL implementation that supports SPIR-V.
