### ISSUE TITLE
Missing Spec Description for conversion of half to image_channel_type: CL_UNORM_INT8 / CL_UNORM_INT16 / CL_SNORM_INT8 / CL_SNORM_INT16.

### ISSUE THREAD

**Issue by garimagu** [KhronosGroup/OpenCL-Docs#193]
Section 8.3 Image Addressing and Filtering: Conversion Rules.
The section on conversion of image write(or read) data to (or from) image_channel_types gives details of conversion to int/float/uint datatypes but not for half datatypes. It should be a part of the extension documentation.
It can be extrapolated from the conversion rules for float, but it should be explicitly given.
Reference: https://www.khronos.org/registry/OpenCL/specs/2.2/pdf/OpenCL_Ext.pdf
and https://www.khronos.org/registry/OpenCL/specs/2.2/pdf/OpenCL_C.pdf

**Comment by bashbaug** [comment]
I think I had a typo in my PR and this issue closed automatically by mistake.  Reopening.
