### ISSUE TITLE
Use type markup consistently in the CL XML file

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#196]
See: https://github.com/KhronosGroup/OpenCL-Docs/pull/192#issuecomment-577980012

Currently, the XML file uses the `<type>` markup is inconsistently around standard types such as `void`.  

Proposed solution: consistently use the `<type>` markup everywhere, regardless whether it is a standard type or an OpenCL type.

**Comment by Kerilk** [comment]
It was only omitted on `void` (`int` and `size_t` for instance are tagged with `<type>`). What I understood the first time I saw this was that, as `void` is not a type, rather the absence of one, there was no `<type>` tag.

Having `<type>` tags around everything should make things easier for tools so I support your solution.

**Comment by Kerilk** [comment]
I have not found a missing markup in recent versions of the xml file. Maybe this issue can be closed.

**Comment by bashbaug** [comment]
> I have not found a missing markup in recent versions of the xml file. Maybe this issue can be closed.

Agreed - I took a quick through the XML file and it looks this issue is resolved.

The APIs that accept function pointers are debatably still missing the `<type>` markup in the function pointer definitions, but if needed those could be addressed via a new issue.
