### ISSUE TITLE
Parameter Names to clSetEventCallback

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#198]
The parameter names for `clSetEventCallback` are inconsistent between the spec, headers, and XML file.  The [spec](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#clSetUserEventStatus) currently says:

```c
cl_int clSetEventCallback(
    cl_event event,
    cl_int command_exec_callback_type,
    void (CL_CALLBACK* pfn_notify)(cl_event event, cl_int type, void *user_data),
    void* user_data);
```

But, the description of `pfn_notify` describes `event_command_exec_status` instead of `type`.

The [headers](https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl.h#L1346) current have:

```c
extern CL_API_ENTRY cl_int CL_API_CALL
clSetEventCallback(cl_event    event,
                   cl_int      command_exec_callback_type,
                   void (CL_CALLBACK * pfn_notify)(cl_event event,
                                                   cl_int   event_command_status,
                                                   void *   user_data),
                   void *      user_data) CL_API_SUFFIX__VERSION_1_1;
```

Note `event_command_status` instead of `event_command_exec_status` or `type`.

The XML file currently does not include any parameters to the callback function, but this may change soon, see #196.

**Comment by alycm** [comment]
Note on the merged PR said

> The name event_command_status still doesn't seem great to me, especially in relation to command_exec_callback_type. At the very least I'd prefer to use status or type consistently.

I agree that the inconsistency between type/status isn't good.
