### ISSUE TITLE
Required image formats in embedded profile

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#201]
The unified specification doesn't document any required image format for implementations that support the embedded profile. The OpenCL 1.2 specification did have a list of required formats.

**Comment by kpet** [comment]
I've opened #202 to cover read_only and write_only images, taking the list of formats from the OpenCL 1.2 specification.

What about read_write images? This doesn't seem to be optional in the embedded profile. Should we at least require one format? We could require the intersection of the list of required formats for read_write images in the full profile and the list of required formats for the embedded profile.

**Comment by Jeremy-Kemp** [comment]
I think starting with the intersection of the required embedded profile formats with the required read_write formats for full profile sounds like a good direction to go in. 

We probably wouldn't want to require additional formats in read_write for embedded over what is required for read _or_ write.

**Comment by bashbaug** [comment]
I just merged #202.  I'm keeping this issue open though, until we've resolved the issue regarding read_write formats.

**Comment by bashbaug** [comment]
@kpet @Jeremy-Kemp , I think we fixed this as part of the OpenCL 3.0 spec changes.  The latest API spec says:

> For embedded profiles devices that support reading from and writing to the same image object from the same kernel instance (see CL_​DEVICE_​MAX_​READ_​WRITE_​IMAGE_​ARGS) there is no required minimum list of supported image formats.

Do you think that is sufficient to close this issue, or are additional changes needed?  Thanks!

**Comment by Jeremy-Kemp** [comment]
Yes, I think we can close this as we already addressed it. Thanks!

**Comment by bashbaug** [comment]
Great, thanks for confirming.  Closing!
