### ISSUE TITLE
The list of required image formats is incorrect for 1.x implementations

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#229]
All formats that were added in 2.0 are unconditionally required. The new formats should be required only for 2.x implementations.

**Comment by bashbaug** [comment]
Interesting.  To be clear, this is primarily referring to the `Minimum list of required image formats` tables, for both the full profile and embedded profile?

If I'm mentally doing the diff correctly between the OpenCL 2.x and OpenCL 1.x specs, the differences are only for the full profile, and are:

* OpenCL 2.x requires support for `CL_R`, `CL_DEPTH`, `CL_RG`, and `CL_sRGBA` image channel orders, in addition to the image channels required in OpenCL 1.2.  `CL_sRGBA` was a new image channel order in OpenCL 2.0.  The others were in OpenCL 1.2, but were optional.

* For `CL_RGBA`, OpenCL 2.x requires support for the `CL_SNORM_INT8` and `CL_SNORM_INT16` image channel data types in addition to the channel data types required in OpenCL 1.2.

There are no changes for the embedded profile or for the `CL_ABGR` image channel order.

Does this seem right?

**Comment by kpet** [comment]
Sounds about right to me.

We also should make it clearer that `Minimum list of required image formats: kernel read and write` only applies to 2.x.

**Comment by Jeremy-Kemp** [comment]
Yes, I think that looks correct. Embedded profile requirements remained the same between 1.x and 2.x.

There is some wording that has lead to a possible mis-interpretation of the spec for me that I'd like to clarify. The table has a note on `sRGBA` which says: `sRGB channel order support is optional for 1D image buffers`. 

Is the implication there that `sRGB` is in fact required, but only for types that aren't 1D image buffers? During my PR for [KhronosGroup/OpenCL-CTS/pull/629](https://github.com/KhronosGroup/OpenCL-CTS/pull/629) I muddled up `sRGB` and `sRGBA` so want to clarify.

**Comment by Jeremy-Kemp** [comment]
And also, the required `channel_data_type` for `sRGB` is missing entirely.

**Comment by bashbaug** [comment]
@kpet @Jeremy-Kemp I think we fixed this in the v3.0-Unified spec.  Can you please verify and close this issue if so?  Thanks!

**Comment by Jeremy-Kemp** [comment]
Yes thats correct, we can close this one (I don't have permission to do so).
