### ISSUE TITLE
Typo in return types of clEnqueueMapImage and clEnqueueMapBuffer

### ISSUE THREAD

**Issue by mantognini** [KhronosGroup/OpenCL-Docs#24]
The doc says that both `clEnqueueMapImage` and `clEnqueueMapBuffer` return `void` while they actually return `void*`.

https://github.com/KhronosGroup/OpenCL-Docs/blob/master/api/opencl_runtime_layer.txt#L1365
https://github.com/KhronosGroup/OpenCL-Docs/blob/master/api/opencl_runtime_layer.txt#L3004

**Comment by kpet** [comment]
Thanks for reporting this! Did a quick scan of the spec for `void`. There doesn't seem to be any other similar issues.
