### ISSUE TITLE
Enhancement: Permanent link to "latest" refpages

### ISSUE THREAD

**Issue by TSlivede** [KhronosGroup/OpenCL-Docs#251]
If external pages want to link to some part of the OpenCL reference pages, they currently have to link to a specific version of the reference pages like this:    
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clGetDeviceIDs.html    
After some years have passed, that link now points to the documentation of an outdated OpenCL version.

It would be nice, if there were a link, that always points to the current version like for example    
https://www.khronos.org/registry/OpenCL/sdk/latest/docs/man/html/clGetDeviceIDs.html or    
https://www.khronos.org/registry/OpenCL/sdk/current/docs/man/html/clGetDeviceIDs.html or
https://www.khronos.org/registry/OpenCL/sdk/docs/man/html/clGetDeviceIDs.html

----

It would also be nice, if the header of all reference pages (old ones and new ones) contained a drop-down-menu, that lets one switch to a newer or older version...

**Comment by bashbaug** [comment]
@outofcontrol, we exchanged a few emails describing this issue and possible fixes.  Is this something you can help with?

**Comment by Khronoswebmaster** [comment]
How well does this function now?https://www.khronos.org/registry/OpenCL/sdk/latest/docs/man/html/clGetDeviceIDs.html

**Comment by TSlivede** [comment]
Yes, it works! Perfect!

https://www.khronos.org/registry/OpenCL/sdk/latest/docs/man/html

-----

Is there any intention to also implement this?

> It would also be nice, if the header of all reference pages (old ones and new ones) contained a drop-down-menu, that lets one switch to a newer or older version...

If not (or not yet), then I'll close this issue and create a new one explicitly for that suggestion (even if there are no plans currently, an issue will act as an reminder, that at one point one could add that feature...).

**Comment by bashbaug** [comment]
Awesome!

Let's create a separate issue for the drop-down menu request.  Pinging @oddhack just in case he knows off-hand whether the online reference page toolchain supports something like this.

**Comment by TSlivede** [comment]
Done: https://github.com/KhronosGroup/OpenCL-Docs/issues/305
