### ISSUE TITLE
SPIR-V OpenCL environment spec does not describe Builtin decoration

### ISSUE THREAD

**Issue by Naghasan** [KhronosGroup/OpenCL-Docs#269]
The SPIR-V core specs reference the client API to describe Builtin decoration operand (see https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#BuiltIn) but the environment specs does not mention any of them.

Among the ambiguities:

- Kernel Execution Model related builtin decoration are not described (I'm not sure if more is needed to be said as SPIR-V core seems rather explicit)
- The environment spec does not specify which storage class an OpVariables should use when decorated by a Builtin decoration (leads to some ambiguities like here https://github.com/intel/llvm/pull/1581#discussion_r414731009)

**Comment by bashbaug** [comment]
I did some experiments with the current SPIR-V LLVM Translator to see what is being generated today, using the attached file:

* [builtins.cl.txt](https://github.com/KhronosGroup/OpenCL-Docs/files/4549060/builtins.cl.txt)

In short, all built-in variables are currently being declared in the **Input** storage class, which seems to make sense.  So, as far as changes to for the OpenCL SPIR-V environment spec, do we only need to say that built-in variables must be declared in the **Input** storage class?

If so, until we support a built-in variable in a different storage class, I think we can say that _all_ built-in variables must be declared in the **Input** storage class vs. listing them individually.  This simplifies the spec and is one fewer place to update when a new built-in is supported.  Does this sound reasonable?

Thanks!

**Comment by Naghasan** [comment]
I think it make sense, brings read-only, no uniformity assumption and no initializer.

**Comment by alycm** [comment]
I'm reopening this ticket because @pierremoreau has opened a [CTS PR](https://github.com/KhronosGroup/OpenCL-CTS/pull/769) to match the changes made in https://github.com/KhronosGroup/OpenCL-Docs/pull/278.

I hadn't realized that the change would run counter to older versions of tools.

I still think that the change is correct (the old use of `UniformConstant` doesn't make sense to me for builtins, most are not uniform).  But, e.g., if a spirv-val rule was added to check that built-in variables are in the `Input` class then that will reject SPIR-V produced by older versions of tools.

So this ticket is reopened to confirm that we're okay with that.  I.e., that older SPIR-V doesn't make sense and should be regenerated if possible.

**Comment by bashbaug** [comment]
Did the older tools allocate all built-in variables in the `UniformConstant` storage class or just some of them?

I think I could make a case that some of the built-in variables really are uniform and constant and hence could belong in the `UniformConstant` storage class - things like `get_num_groups()` / `NumWorkGroups`, for example.  Others are definitely not uniform and constant though - things like `get_local_id()` / `LocalInvocationId`.  If the older tools are only generating uniform and constant built-in variables in the `UniformConstant` storage class then perhaps we should try to accommodate them, but if they're generating all built-in variables in the `UniformConstant` storage class then they'll need to change to generate valid SPIR-V anyhow, and I'm inclined to say they should switch all built-in variables to the `Input` storage class instead.

FWIW, as best I can tell Vulkan requires all compute-related built-in variables to be in the `Input` storage class, including `NumWorkGroups` and `NumSubGroups`.

**Comment by alycm** [comment]
The Khronos SPIR-V generator in 2018 would use `UniformConstant` storage class for things like `get_global_id()`/`GlobalInvocationId`.  This is based on some old samples in my notes.  A recent build of the tool will use `Input` storage class.

I'm making no claim that that is desirable behaviour.  I can see a case for `get_num_groups()` / `NumWorkGroups` being `UniformConstant` storage class but as the SPIR-V specification explicitly mentions "OpenCL constant memory" for in the `UniformConstant` description is doesn't seem appropriate.

The thought that caused me to reopen this ticket is that there could be SPIR-V in the world that was valid before this change, but becomes invalid afterwards.  This may be an overly theoretical concern though, as the OpenCL CTS (https://github.com/KhronosGroup/OpenCL-CTS/pull/769) is my only example and once that PR merges that problem goes away.

So, if we're okay with the validator rejecting [*] SPIR-V produced by the Khronos generator a few years ago then there is nothing more to do.  Despite reopening this ticket I would be okay with that, presumably implementations that currently accept such input will continue to do so anyway, and future tools will follow the specification as it exists today.

[*] Of course assuming someone adds the check there.

**Comment by kpet** [comment]
I've created https://github.com/KhronosGroup/SPIRV-Tools/issues/3355 to cover changes to the SPIR-V validator.

**Comment by bashbaug** [comment]
> So, if we're okay with the validator rejecting [*] SPIR-V produced by the Khronos generator a few years ago then there is nothing more to do.

+1, I think closing this issue with no additional action is the right thing to do.

**Comment by alycm** [comment]
Okay, closing issue.
