### ISSUE TITLE
Denormal flushing clarification

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-Docs#276]
Currently the spec [states](https://github.com/KhronosGroup/OpenCL-Docs/blame/master/env/image_addressing_and_filtering.asciidoc#L771): 

> Support for denormalized numbers with single precision and half precision floating-point is optional. Denormalized single precision or half precision floating-point numbers passed as the input or produced as the output of single precision or half precision floating-point operations may be flushed to zero.

Are we saying here that denormal numbers may be flushed to zero for **all** floating-point operations, or just **some**?

Either way, I suggest tightening up the wording to make the statement less ambiguous. 

Something like:
> Support for denormalized numbers with single precision and half precision floating-point is optional. Denormalized single precision or half precision floating-point numbers passed as the input or produced as the output of **all** single precision or half precision floating-point operations may be flushed to zero.

Or:
> Support for denormalized numbers with single precision and half precision floating-point is optional. Denormalized single precision or half precision floating-point numbers passed as the input or produced as the output of **some** single precision or half precision floating-point operations may be flushed to zero.

**Comment by b-sumner** [comment]
A given operation "may" flush, not "shall" flush.  How does adding "all" or "some" change an implementation?

**Comment by Jeremy-Kemp** [comment]
Yes, you're right.

I've been thinking about this further since submitting and think I've conflated to issues that I was looking at which led to me creating this issue.

I will close this one as I don't think there is actually anything that needs modifying and was just my own confusion.
