### ISSUE TITLE
CLK_UNORM_SHORT_101010 should be CLK_UNORM_INT_101010

### ISSUE THREAD

**Issue by ijkmn** [KhronosGroup/OpenCL-Docs#287]
in Built-in Image Query Functions, CLK_UNORM_SHORT_101010 should be CLK_UNORM_INT_101010

**Comment by bashbaug** [comment]
Thanks!  I've created PR #291 to fix this.

I see we're also (likely?) missing an enum for `CLK_UNORM_INT_101010_2`, and I created issue #292 so we don't lose track of this.
