### ISSUE TITLE
D3D10 and D3D11 sharing documentation for OCL 1.2 missing error codes from OCL 1.1

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenCL-Docs#29]
(originally posted to OpenCL-Registry, but this is the right place for API issues - no idea if this is still relevant, though)

Moved from internal Bugzilla issue 11045:

OCL 1.2 documentation for d3d10 and d3d11 sharing on website is missing error codes from OCL 1.1.

load this:
http://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/cl_khr_d3d10_sharing.html

then load this:
http://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/cl_khr_d3d10_sharing.html

notice this is missing:

When the cl_khr_d3d10_sharing extension is enabled, this extends the list of allowable values in certain parameters of certain functions, as follows:

CL_CONTEXT_D3D10_DEVICE_KHR is accepted as a property name in the properties parameter of clCreateContext and clCreateContextFromType.
CL_CONTEXT_D3D10_PREFER_SHARED_RESOURCES_KHR is accepted as a value in the param_name parameter of clGetContextInfo.
CL_MEM_D3D10_RESOURCE_KHR is accepted as a value in the param_name parameter of clGetMemObjectInf.
CL_IMAGE_D3D10_SUBRESOURCE_KHR is accepted as a value in the param_name parameter of clGetImageInfo.
CL_COMMAND_ACQUIRE_D3D10_OBJECTS_KHR and CL_COMMAND_RELEASE_D3D10_OBJECTS_KHR are returned in the param_value parameter of clGetEventInfo when param_name is CL_EVENT_COMMAND_TYPE.
CL_INVALID_D3D10_DEVICE_KHR is returned by clCreateContext and clCreateContextFromType if the Direct3D 10 device specified for interoperability is not compatible with the devices against which the context is to be created.
CL_INVALID_D3D10_RESOURCE_KHR is returned by clCreateFromD3D10BufferKHR when resource is not a Direct3D 10 buffer object, and by clCreateFromD3D10Texture2DKHR and clCreateFromD3D10Texture3DKHR when resource is not a Direct3D 10 texture object.
CL_D3D10_RESOURCE_ALREADY_ACQUIRED_KHR is returned by clEnqueueAcquireD3D10ObjectsKHR when any of mem_objects are currently acquired by OpenCL.
CL_D3D10_RESOURCE_NOT_ACQUIRED_KHR is returned by clEnqueueReleaseD3D10ObjectsKHR when any of mem_objects are not currently acquired by OpenCL.

The same problem for D3D11, please fix both.

**Comment by bashbaug** [comment]
I've verified that all of the enums mentioned above are in the [latest Unified Extensions Spec](https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_Ext.html), for both D3D10 and D3D11, so I am closing this issue.
