### ISSUE TITLE
Assess suitability of OpenCL C 3.0 changes for implementing in open source tools

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#295]
The idea is to understand and gather the list of changes that would have to be made in the compiler, prototype to sufficient level of detail or implement directly upstream or initiate discussions with the upstream community where there are uncertainties.

The list of tools include - frontends (Clang), converters (SPIRV-LLVM Translator), etc.

**Comment by bashbaug** [comment]
Discussion in the June 23rd teleconference: Need a prototype demonstrating OpenCL C 3.0 compilation using open-source tools.

Commentary: A prototype exists.  I will find a link.

**Comment by AnastasiaStulova** [comment]
Sounds great! Just to clarify the prototype should be suitable for upstream implementation.

So I guess the way to go ahead is to start from some sort of review and then see if we need any discussion with open source tooling communities.

**Comment by AnastasiaStulova** [comment]
List of tools affected by OpenCL 3.0 changes:
- Clang
- SPIR-V Tools (likely validator and opt)

Action items required:
- List functionality that requires changes in tools (start from the list of optional features).
- Review prototype implementation from Intel, link to be provided by @bashbaug.
- Investigate what we need to change in SPIR-V Tools.

**Comment by bashbaug** [comment]
I think the discussion regarding OpenCL C 3.0 changes is ongoing in the tooling calls, but in case it is helpful, a patch demonstrating OpenCL C 3.0 feature macros in Clang may be found here:

https://github.com/intel/opencl-clang/commit/92f3f7f1a06f25fb13708f87c26b0fbf50924c96

**Comment by AnastasiaStulova** [comment]
The list of OpenCL 3.0 changes that affect tools:
- 3D image writes
- CL2.0/C11 atomic scopes
- CL2.0/C11 atomic ordering
- Generic address space (+BIFs overloads and addr space conversion BIFs)
- Devide-side enqueue
- Pipes
- Program scope variables in global memory
- Read/write images
- Subgroup BIFs
- WG collective BIFs
- RGBA vector access
- Extra memory fence BIF
- ULP requirements on BIFs
- NAN behavior

**TODO:** add spec references

**Comment by AnastasiaStulova** [comment]
Summary:
- Detailed investigation have been made for Clang
- There were no detailed investigations for OpenCL Tooling, however no concerns have been expressed either.
