### ISSUE TITLE
Address space conversion for nested pointer indirections

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#30]
When nested pointers are used with address space qualifiers what is the expected behavior for their conversions. Example in CL2.0:

```
private int * * p1;
int * * p2 = p1; // Are we expecting to perform the right address space conversion private->generic?
```

For OpenCL C we were accepting this code but generated `bitcast` where address space conversion was lost.

For OpenCL C++ the suggestion from the upstream community is to just disallow this conversion.

See Clang bug for more details: https://bugs.llvm.org/show_bug.cgi?id=39674

**Comment by AnastasiaStulova** [comment]
I think we need to update the spec to reflect the implementation in Clang.

**Comment by AnastasiaStulova** [comment]
We provide implementation in Clang as follows (https://reviews.llvm.org/D58236):
- Explicit conversions allowed for nested pointers with a warning.
- Implicit conversions are disallowed for nested pointers with an error.

**Example**

```
__global int** gl_ptrptr;
__generic int ** gen_ptrptr;

gen_ptrptr = gl_ptrptr; // error
gen_ptrptr = (__generic int **)gl_ptrptr; // warning
```

Do it make sense to document this behavior in the spec?

**Comment by bashbaug** [comment]
I initially thought the example above was just fine, but I eventually agreed it could be problematic. Here are some notes so I don't forget and in case it helps somebody else looking at this example.

First, I think it's easier to see what's happening to write the example as follows, even though it's not as common as the syntax above. This is equivalent code, much as `const int* p` is equivalent to `int const* p`:

```c
int __global * __private * gl_ptrptr;   // a pointer to a private memory pointer to a global int
int __generic * __private * gen_ptrptr; // a pointer to a private memory pointer to a generic int
```

Written this way, it's much more obvious that the assignment `gen_ptrptr = gl_ptrptr` is not an assignment of a global pointer to a generic pointer, since both `gl_ptrptr` and `gen_ptrptr` are pointers to the private address space. Rather, it's assigning a pointer-to-a-pointer to one address space (the global address space) to a pointer-to-a-pointer to a different address space (the generic address space). Since a pointer to one address space could have a different representation than than a pointer to another address space, this is not safe. Note, this also makes this case different than that for `const` or `volatile`.

All of that being said, generating an error in this case does feel a bit too strong. Is this case well-defined and correct?

```c
int __global * __private * gptr;            // a pointer to a private memory pointer to a global int
int __generic * __private * danger = gptr;  // a pointer to a private memory pointer to a generic int
int __global * __private * safe = danger;   // back to a pointer to a private memory pointer to a global int

safe[0][0] = 42;
```

If so:
* Should the default be a warning instead?
* Does it matter if we are compiling as C or C++?
* Should there be any warning with an explicit cast?

**Comment by b-sumner** [comment]
Two questions or concerns about these examples:  First, __generic is not an actual keyword, is it?  So if it is just there for clarity can we use something else like <generic>?  Second, no object can actually be allocated or reside in the generic address space, so a neither a "generic int" nor a "pointer to a generic int" can exist, can they?

**Comment by bashbaug** [comment]
Thanks, yes, I suppose the examples above should be interpreted as pseudo-code and not as strictly valid OpenCL C, although they are compile-able by Clang.

> First, __generic is not an actual keyword, is it? So if it is just there for clarity can we use something else like `<generic>`?

Correct __generic is not an actual keyword in OpenCL C.  It is "reserved for future use".

> Second, no object can actually be allocated or reside in the generic address space, so a neither a "generic int" nor a "pointer to a generic int" can exist, can they?

This one is trickier, and I thought about it before replying, but couldn't think of a better way to describe the generic address space case.  Maybe something like:

```c
// a pointer to a private memory pointer to an integer via the generic address space:
int /*generic*/ * __private * privptr_genptr;
```

That has more words but I think it better describes what's happening: the integer itself is allocated in one of the named address spaces, though the pointer points to it via the generic address space.

**Comment by AnastasiaStulova** [comment]
> All of that being said, generating an error in this case does feel a bit too strong. Is this case well-defined and correct?
> 
> ```c
> int __global * __private * gptr;            // a pointer to a private memory pointer to a global int
> int __generic * __private * danger = gptr;  // a pointer to a private memory pointer to a generic int
> int __global * __private * safe = danger;   // back to a pointer to a private memory pointer to a global int
> 
> safe[0][0] = 42;
> ```

This is safe to do however I can easily modify the example where compiler will generate incorrect binary.

```c
int __global * __private * gptr;            // a pointer to a private memory pointer to a global int
int __generic * __private * danger = gptr;  // a pointer to a private memory pointer to a generic int
int __local * __private * unsafe = danger;   // to a pointer to a private memory pointer to a local int
 
unsafe[0][0] = 42; // accessing global memory as if it would be local
 ```

I don't think this problem is unique to nested pointers though but rather exists for generic AS pointers overall. What can happen though is a situation like this:

```c
int __global * glob = ...;
int __global * __global * globglob = &glob;
int __generic * __generic * gengen = globglob;
int __local * loc = ...;
*gengen = loc; // we now have *globglob pointing to __local AS object
 ```

There is also another problem that we can currently only cast single pointers in different address spaces. So in Clang/LLVM we would use **bitcast** instruction for the nested pointers instead of **addrspacecast**. That means

```c
__global int * glob;
__generic int * gen = glob;
*gen = 1; // safe because we added adress translation operation

__global int *  __global int * globglob;
__generic int * __generic int * gengen = globglob;
**gengen = 1; //unsafe - wrong store instruction can be generated because no address space conversion has occurred.
 ```

> 
> If so:
> 
>     * Should the default be a warning instead?
>

After lengthy discussions with Clang community we have concluded that error will be more appropriate. The details are on the reviews but in short - implicit conversions are generally expected to be safe but for address space conversions it's not always the case.

>     * Does it matter if we are compiling as C or C++?

C is more permissive with pointer conversions than C++. However C++ rules assume that qualifiers don't introduce real representation differences and that operations on qualified types are compatible with operations on unqualified types. This is not the case with address spaces I believe as we might have theoretically even different instructions generated for accessing different address space regions. In fact in OpenCL we don't even have types that are not qualified by address space (apart from few exceptions).

Just to point out similar situation about upcast for nested pointers in C++ https://stackoverflow.com/questions/8026040/conversion-from-derived-to-base that is disallowed in C++.

> 
>     * Should there be any warning with an explicit cast?

**Comment by bashbaug** [comment]
@rolandschulz put together some examples that I thought were very useful so I'm passing them along: https://godbolt.org/z/caEywr

Note that these examples use the explicit `__generic` address space, which is valid in Clang but is not strictly valid OpenCL C, but I am leaving it for clarity.

In short, at least at the time of this writing, the Clang C++ for OpenCL compiler is mostly producing errors and warnings for address spaces that are consistent with errors and warnings for other types.  The one possible exception is (line 14):

```cpp
    __private int* i;
    __generic int** p = &i;       //OK but should be error
```

The OpenCL C compiler is debatably generating an error that should be a warning (line 11) and a warning with an explicit cast that should be OK (line 12), though:

```c
    __private int* i;
    __generic int** p = &i; //error but should be warning
    __generic int** p2 = (__generic int**)&i; //OK
```

Regardless, I do think it would be helpful to document this case in the OpenCL C spec.  @AnastasiaStulova will you create a PR with the proposed spec updates?

**Comment by AnastasiaStulova** [comment]
I believe this is now clarified in the spec:
> For nested pointers, implicit conversions between address spaces are disallowed. Explicitly casting between different address spaces in nested pointers is allowed but the use of such pointers can lead to incorrect behavior such as accessing invalid memory locations.
