### ISSUE TITLE
Are specialization constants forced on non-SPIR-V intermediate languages

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#303]
Issue https://github.com/KhronosGroup/OpenCL-Docs/issues/294, on whether specialization constants should be optional, states:

> Specialization constant concept don't exist yet in some other popular IR format i.e. LLVM. By making this feature non-optional we prevent using alternative to SPIR-V IR formats for OpenCL 3.0 in a compliant way.

I would state that a program compiled to an intermediate language that does not support specialization constants will contain zero specialization constants and thus calling `clSetSpecializationConstant` on such a program will return `CL_​INVALID_​SPEC_​ID` because the API specification says:

> Otherwise, it returns one of the following errors:
> CL_​INVALID_​SPEC_​ID if spec_id is not a valid specialization constant ID

And no value of `spec_id` can possibly be valid for a program that does not contain any specialization constants.

However, even if my interpretation is correct, this is relying on a second-order effect to ensure that specialization constants are optional for intermediate languages that have no such concept, which is not very clear to the reader.   A non-normative note could point out this property explicitly.

**Comment by bashbaug** [comment]
> thus calling `clSetSpecializationConstant` on such a program will return `CL_​INVALID_​SPEC_​ID`...

Yes, this is my expectation also.

> A non-normative note could point out this property explicitly.

This sounds reasonable.  We could also enhance this error condition so the program has to a) be created from an IL (this is the current error condition), and b) the IL has to support specialization constants (this is new):

> `CL_​INVALID_​PROGRAM` if _program_ is not a valid program object created from an intermediate language (e.g. SPIR-V).

I'm thinking of something like:

> `CL_​INVALID_​PROGRAM` if _program_ is not a valid program object created from an intermediate language (e.g. SPIR-V), or the intermediate language does not support specialization constants.

The last thing we could consider adding is a program object query for "number of specialization constants" or "maximum specialization constant index".  However, since there is no requirement for specialization constant indices to start at zero or to be contiguous, I'm not sure how useful this would be.

**Comment by AnastasiaStulova** [comment]
I would vote for an explicit rather than an indirect way to query this. It is much cleaner to the developers and avoids implementing unused APIs for vendors. We also can't expect that all developers will deduce everything we do and in the same way.

**Comment by alycm** [comment]
> I'm thinking of something like:
> > CL_​INVALID_​PROGRAM if program is not a valid program object created from an intermediate language (e.g. SPIR-V), or the intermediate language does not support specialization constants.

That does sound clearer, yes.

> The last thing we could consider adding is a program object query for "number of specialization constants" or "maximum specialization constant index". However, since there is no requirement for specialization constant indices to start at zero or to be contiguous, I'm not sure how useful this would be.

This is an interesting point.  `clGetProgramInfo`/`clGetProgramBuildInfo`/`clGetKernelArgInfo` currently allow a lot of information to be extracted about how a given program can be interacted with from the API.  But not the IDs, types and default values of specialization constants.

> I would vote for an explicit rather than an indirect way to query this. It is much cleaner to the developers and avoids implementing unused APIs for vendors. We also can't expect that all developers will deduce everything we do and in the same way.

That could work too.  Given it is a property of the IL rather than a device or a program it's a little awkward.  I think it would maybe be a device query that returns a list of `CL_TRUE`/`CL_FALSE` for all the ILs listed for `CL_​DEVICE_​ILS_​WITH_​VERSION`.

**Comment by bashbaug** [comment]
I just created PR https://github.com/KhronosGroup/OpenCL-Docs/pull/337 which adds the clarification described above.

We still need to decide if we want to add a query whether an IL or a program object supports specialization constants, or if the clarification above is all that is needed to close this issue.

**Comment by bashbaug** [comment]
We had a long discussion regarding this topic in the July 7th teleconference and concluded that the use case for a query for specialization constant support is not clear, especially given that there are currently no currently OpenCL-supported ILs without specialization constant support.

Without a clear use case we are closing this issue with no additional action.  We will reconsider a query if such a use case does materialize, such as if a vendor chooses to support an IL other than SPIR-V.
