### ISSUE TITLE
OpenCL 3.0 does not define any optional properties for buffers/images.

### ISSUE THREAD

**Issue by luoanquan** [KhronosGroup/OpenCL-Docs#310]
As we can see "OpenCL 3.0 does not define any optional properties for buffers/images", Why add two new API functions(clCreateBufferWithProperties/clCreateImageWithProperties) in OpenCL 3.0? what's the purpose?

**Comment by kpet** [comment]
The main goal with these is to improve extensibility. They make it much easier to develop clean extensions to clCreate{Buffer,Image}.

**Comment by alycm** [comment]
I agree with @kpet's comment, the properties are about extensibility.

Perhaps something could be added to the specification noting the absence, but to be honest I'm not sure how much that really helps the reader.

**Comment by bashbaug** [comment]
We did include a line in the spec noting the absence of new properties for buffers and images (buffers shown below):

> OpenCL 3.0 does not define any optional properties for buffers.

We don't describe why we added the APIs without defining any new properties though.  I suppose we could add a bit more info to the [change log appendix](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#_summary_of_changes_from_opencl_2_2_to_opencl_3_0) describing the intent behind the new APIs.  Would that be useful?

**Comment by bashbaug** [comment]
I just created #328, which adds a line to the change log appendix describing why we added these new APIs without defining any new properties.  Please take a look - thanks!
