### ISSUE TITLE
Clarification on event creation

### ISSUE THREAD

**Issue by raunraun** [KhronosGroup/OpenCL-Docs#312]
In several places there is text likes (event for clEnqueueNDRangeKernel)

> **event returns an event object that identifies this particular kernel-instance.** Event objects are unique and can be used to identify a particular kernel-instance later on. If event is NULL, no event will be created for this kernel-instance and therefore it will not be possible for the application to query or queue a wait for this particular kernel-instance. If the event_wait_list and the event arguments are not NULL, the event argument should not refer to an element of the event_wait_list array.

There is no exception for event creation if the clEnqueueNDRangeKernel fails.  I think this clarification should be added.

> event returns an event object that identifies this particular kernel-instance. Event objects are unique and can be used to identify a particular kernel-instance later on. If event is NULL **or the return code is not CL_SUCCESS**, no event will be created for this kernel-instance and therefore it will not be possible for the application to query or queue a wait for this particular kernel-instance. If the event_wait_list and the event arguments are not NULL, the event argument should not refer to an element of the event_wait_list array.

I believe the same problem exists in all APIs that return an event.

**Comment by kpet** [comment]
Agree, there's no way for an application to know whether it should refcount the event down for cleanup otherwise.
