### ISSUE TITLE
Is Description of OpenCL C "Features" Clear Enough?

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#330]
This was internal issue 218.

Is the generic introduction of what the new OpenCL C features and associated macros are sufficient?  Does it make it clear what a feature is?  Is there any confusion compared to extension pragmas (i.e. extensions are enabled by the programmer, features are enabled or not by the compiler).

**Comment by alycm** [comment]
Comment from @AnastasiaStulova that having a defined "name" per feature may help to reference them in the text: https://github.com/KhronosGroup/OpenCL-Docs/pull/358#discussion_r459071696

**Comment by AnastasiaStulova** [comment]
From OpenCL Tooling call today:
- We should explain the behavior that is represented by features and extensions (example - double)
- We should also explain difference between core otional extensions and extensions

**Comment by AnastasiaStulova** [comment]
I think this was closed accidentally.

**Comment by bashbaug** [comment]
> I think this was closed accidentally.

Yes, I agree, it closed automatically because it was linked with #372.  I think #372 should have been linked to #370 instead?  I'll fix the link, and close #370 manually.

**Comment by AnastasiaStulova** [comment]
PR: https://github.com/KhronosGroup/OpenCL-Docs/pull/387

**Comment by alycm** [comment]
https://github.com/KhronosGroup/OpenCL-Docs/pull/387 already addressed this issue and was merged, I'll close this issue.
