### ISSUE TITLE
Deprecation of clSetProgramReleaseCallback in 3.0

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#348]
The API call was added in 2.2 and is not supported in 3.0. We're likely to want to rename it to `clSetProgramDesctructorCallback` when we reintroduced the functionaltiy (see #346). Should we deprecate `clSetProgramReleaseCallback` in 3.0?

**Comment by bashbaug** [comment]
My 2c: we should deprecate `clSetProgramReleaseCallback` and the queries for `CL_​PROGRAM_​SCOPE_​GLOBAL_​CTORS_​PRESENT` and `CL_​PROGRAM_​SCOPE_​GLOBAL_​DTORS_​PRESENT` in OpenCL 3.0.

Rationale is:

* This will make it very clear that these feature are not supported in OpenCL 3.0 - see #347 .
* `clSetProgramReleaseCallback` is misleadingly named - see discussion in https://github.com/KhronosGroup/OpenCL-Docs/issues/187#issuecomment-655213389.

I will create a PR for discussion.  I think this may be as simple as identifying this API and enums as deprecated in the XML file?
