### ISSUE TITLE
Specification about derived implementations of pow and pown is bogus.

### ISSUE THREAD

**Issue by mantognini** [KhronosGroup/OpenCL-Docs#35]
When  _x_ < 0 and even _y_ derived implementations are required to call `log2(x)`, which is undefined on negative inputs.

https://github.com/KhronosGroup/OpenCL-Docs/blob/80c040b4ad54ec6211f2ef323e9dd7bd340dc8a5/OpenCL_C.txt#L9446-L9463

**Comment by bashbaug** [comment]
Good catch, there does appear to be a bug here.

Since either:

* x >= 0, or
* y is an even integer

Would it be correct to change `log2(x)` to `log2(fabs(x))` in these cases?

**Comment by bashbaug** [comment]
Note: The same issue is also in the SPIR-V environment spec and C++ kernel language specs, so whatever fix we make should be propagated to all three specs.

**Comment by mantognini** [comment]
> Would it be correct to change `log2(x)` to `log2(fabs(x))` in these cases?

I'd say yes as we would not gain much by splitting the description into three cases, namely (for `powr`):

1. For `x >= 0`, compute `exp2(y * log2(x))`
2. For `x < 0` and even `y`, compute `exp2(y * fabs(log2(x)))`
3. Else, compute `-exp2(y * fabs(log2(x)))`

It would makes things too verbose for little or no gain at all.

**Comment by bashbaug** [comment]
PR #36 fixes most of this issue, at least for negative x.  There is still an issue with x == 0 that needs to be resolved though, I think.

**Comment by mantognini** [comment]
I think this should be alright (although not obvious): `log(0)` is mathematically well defined, but in any case `powr(0, y)` is either explicitly undefined or part of the edge cases that are relaxed in this case.

**Comment by mantognini** [comment]
Closing this issue as #36 was merged.
