### ISSUE TITLE
OpenCL C 3.0 old atomic scope and ordering 

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#353]
In atomics prior to OpenCL 2.0 there was no definition of memory ordering and scope and therefore old atomics behaved in implementation defined manner wrt to these.

OpenCL 3.0 provides explicit behavior for old atomics wrt memory scope and ordering (see s6.13.11).
> These  were equivalent       to       atomic       operations       with       memory_order_relaxed       consistency,       and memory_scope_work_group scope.

Explicitly defining this might affect backward compatibility although technically it is less conservative and shouldn't invalidate existing  implementations it might not be a helpful behavior moving forward. The default implementations often assumed sequential consistency i.e. `atomic_add` in _**libclc**_ is implemented using `__sync_fetch_and_add` that isn't C11 builtin but clang maps it to sequential consistency equivalent of C11 atomic operation. In C11/OpenCL C 2.0 the default behavior is sequential consistency and device scope. Old applications that were developed might no longer run correctly for the new implementations or if old implementations upgrade the behavior to comply to the new standard. As a result, it might force vendors to maintain old flavor of old atomics or even two flavours if they are to be strictly compliant to the spec.

Old atomics even though deprecated are still found useful to the developers because they allow mixing regular operations on types with atomic operations more intuitively https://github.com/KhronosGroup/OpenCL-Docs/issues/66. Atomic types from C11 don't support this in an easy way (there use even with the regular operator still translate to atomic operations).

Could we change this behavior back to implementation-defined? We could add a query mechanisms to either language or API to allow developer to know scope/ordering explicitly if it is important enough.

**Comment by bashbaug** [comment]
I'm not sure what changing the definition to "implementation-defined" would accomplish.  On a spectrum from "fewest guarantees" to "most guarantees", a relaxed  atomic already provides the fewest memory consistency guarantees possible.  So, all changing to "implementation-defined" would do is allow an implementation to provide additional memory guarantees... which is already possible.

(Note, the memory scope is irrelevant for a relaxed atomic.  I think we can ignore it unless we decide to change the old-style atomic memory order, and I don't think anyone is advocating for a different memory order.)

**Comment by AnastasiaStulova** [comment]
> So, all changing to "implementation-defined" would do is allow an implementation to provide additional memory guarantees... which is already possible.

Can you elaborate how this can be done? Unless you mean that implementation could just decide to implement this differently? In which case they wouldn't strictly follow the spec and therefore there is very little value in specifying this.

> I think we can ignore it unless we decide to change the old-style atomic memory order, and I don't think anyone is advocating for a different memory order.

Looking at upstream tools I would assume most of implementation don't use relaxed model for old atomics.

**Comment by AnastasiaStulova** [comment]
I see very little value in atomics if they only support relaxed model. What was the motivation for adding them in at all? I don't think applications using old attomics will continue to compile in OpenCL 3.0 if the behavior is as per current spec.

**Comment by bashbaug** [comment]
> > So, all changing to "implementation-defined" would do is allow an implementation to provide additional memory guarantees... which is already possible.
> 
> Can you elaborate how this can be done?

Sorry about that, I omitted a word from my reply: I should have said memory _consistency_ guarantees.

Basically, if an implementation wants to provide stronger memory consistency guarantees (say, acquire-release, or sequentially consistency) for an OpenCL 1.x atomic they are free to do so.  This is overkill, and an application that relies on this behavior may not be portable to other implementations without the same memory consistency guarantees, but it is still conformant.

> I would assume most of implementation don't use relaxed model for old atomics.

I can't speak for all GPUs, but Intel GPU atomics are relaxed by default, and require specific fencing operations to provide stronger memory consistency guarantees.  Given that most shading languages don't have a formal memory model, I suspect relaxed consistency atomics are fairly common for many GPUs.

> I see very little value in atomics if they only support relaxed model. What was the motivation for adding them in at all?

Remember that relaxed consistency atomics still provide read-modify-write atomicity, so if a location in memory is initially zero and 100 work items each perform 100 relaxed atomic increments on that location in memory, the result is guaranteed to be 100 x 100 = 10000.  This means that relaxed consistency atomics are useful for bump allocators, histograms, etc.  There is plenty of OpenCL C 1.2 code (and other "shader-like" code) that safely uses relaxed consistency atomics for useful things.

**Comment by alycm** [comment]
> Old applications that were developed might no longer run correctly for the new implementations or if old implementations upgrade the behavior to comply to the new standard. As a result, it might force vendors to maintain old flavor of old atomics or even two flavours if they are to be strictly compliant to the spec.

If those old applications were assuming sequentially consistent atomics for OpenCL 1.2 then they were making assumptions beyond what the spec guaranteed.  Presumably the authors of those applications never cared because their programs worked on the implementations that they were interested in, and I don't see why those implementations would weaken their implementation of the legacy atomics now.

> Looking at upstream tools I would assume most of implementation don't use relaxed model for old atomics.

It depends on what a hardware device is capable of.

> What was the motivation for adding them in at all?

Well for applications and/or hardware that don't need stricter orders there may be performance advantages to relaxed order.  But why specify that the legacy atomics have relaxed order?  Because that's what they effectively were in OpenCL 1.2, there just wasn't a complete memory consistency model to express it.  OpenCL 3.0 is meant to be compatible with 1.2 class hardware (while still allowing more capable hardware to expose their additions).

Your original request of implementation defined would not be incompatible with 1.2 class hardware of course.  Defining the legacy atomic functions in terms of the 2.0 memory consistency model was not intended to represent a change, but to formalize their behaviour while not extending them.

**Comment by AnastasiaStulova** [comment]
Ok, I agree in principle we should aim at more precise definitions. However, I would argue we could confidently say we guarantee the backward compatibility with OpenCL 1.2 if we do so in this case. Certainly, applications that relied on sequential consistency will have to be changed if implementations will choose to follow the specification which is something we should encourage. Therefore the definitions should evolve in such a way the implementations are comfortable to follow them in a strict way.

I agree the portability was not achievable with old atomics however backward compatibility is still very valuable. If vendors now choose to be fully compliant to the spec they would be forced to break backward compatibility of applications that used to run on their device. So it seems there is no good approach here for such vendors.

Regarding **sequential** consistency: first of all, I don't think we should ignore the fact that the most popular open source implementation (_libclc_) maps old atomic to sequential consistency. This likely implies that vendors that derived from it will follow the same behavior and even if the code is not derived from the upstream implementation there might be a value in just following the upstream flow. At least we should take into account that until someone will change _libclc_ behavior it will likely be the case that compilation to SPIR-V using upstream flow won't be compliant to the OpenCL 3.0 definition. And it is not yet clear whether such change would even be accepted.

Secondly, I believe sequential consistency ordering has been chosen as default in C11 for a good reason. If we look at the definition from _cppreference_:

> A load operation with this memory order performs an acquire operation, a store performs a release operation, and read-modify-write performs both an acquire operation and a release operation, plus a single total order exists in which all threads observe all modifications in the same order.

This guarantees deterministic behavior and tools would, therefore, be very conservative wrt optimizations that lead to reordering. In practice, they will aim at preserving the original memory ordering as specified in the application source. Therefore, it is a much easier model for application and tool developers to use and reason about. It is also extremely helpful for debugging.

Overall, if the new definition requires a change in either implementations or applications to be compliant to the spec I don't think we can really say that it is backward compatible. And unless there is a good reason to fix this I would suggest to stay with an old definition. If there is a need for more clarity we could add a query to obtain information on the implemented behavior of atomics. Or if applications really need precise memory ordering behavior they can just use OpenCL v2.0 atomics.

**Comment by AnastasiaStulova** [comment]
I am wondering if in case we are not interested to force every vendor to implement old atomics with relaxed model we could just make the definition a bit weaker i.e. something like:

_For compliant implementations, it is sufficient to represent old atomics with `memory_order_relaxed` consistency, and `memory_scope_work_group` scope. However, implementations might choose more conservative approaches._

The only issues with this could be if any implementation doesn't comply to C11 logic at all and therefore even this definition wouldn't represent their approach adequately. Perhaps this is not very likely case though.

**Comment by bashbaug** [comment]
> I am wondering if in case we are not interested to force every vendor to implement old atomics with relaxed model we could just make the definition a bit weaker i.e. something like:
> 
> _For compliant implementations, it is sufficient to represent old atomics with `memory_order_relaxed` consistency, and `memory_scope_work_group` scope. However, implementations might choose more conservative approaches._

Just to be clear, this is already the case, and implementations are already free to implement any form of relaxed atomics with a stronger memory consistency guarantee if desired.  We don't need to change the spec to allow this.

**Comment by alycm** [comment]
Call 2020-07-21: We'll add some wording that makes it clear the `memory_order_relaxed` and `memory_scope_work_group` are effectively a minimum requirement for the legacy atomic operations.

**Comment by alycm** [comment]
A very simple change here: https://github.com/KhronosGroup/OpenCL-Docs/pull/368
