### ISSUE TITLE
Atomic Functions without scope aren't guarded by __opencl_c_atomic_scope_device

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#357]
Currently the explicit atomic functions are not guarded by feature macros (pending changes w.r.t. generics), but the specification says

> The functions that do not have `memory_scope` argument have the same semantics as the corresponding functions with the `memory_scope` argument set to `memory_scope_device`.

As` memory_scope_device` is not mandatory I think that that version of the builtin should be guarded by `__opencl_c_atomic_scope_device`.

A sentence such as the following to each of the explicit functions that take an order but not a scope should do it:

> Requires OpenCL C 2.0 or the `__opencl_c_atomic_scope_device` feature macro.

**Comment by alycm** [comment]
I've put this under "Needs WG discussion" to bring attention to this, but I hope that this will not be controversial.  I can have a PR with the change ready to go before hand.

**Comment by bashbaug** [comment]
+1, this sounds reasonable to me!

**Comment by alycm** [comment]
I've written the changes, I haven't created a PR as it builds right on top of https://github.com/KhronosGroup/OpenCL-Docs/pull/358

But you can see the changes here: https://github.com/alycm/OpenCL-Docs/commit/fa57be921e0508ca3e8f9dd365345d2223af0111

**Comment by alycm** [comment]
Discussed on call 2020-07-21: No objections, I'll just add the additional commit to https://github.com/KhronosGroup/OpenCL-Docs/pull/358 to avoid a chain of PRs.
