### ISSUE TITLE
OpenCL 3.0 improve optionality of image support

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#360]
Image support has been "optional" before OpenCL 3.0 but it has never been strictly defined what it actually means.

As a result in upstream tools we haven't implemented this properly and there is no functionality conditioned on this.

Since OpenCL 3.0 defines optionality explicitly would it make sense to have images in the list of feature macros i.e something like `__opencl_c_images` and also specify explicitly what functionality becomes optional with this? Then we can also provide adequate tooling for this.

**Comment by alycm** [comment]
I've put this under "Needs WG discussion".   I can see some advantages to this approach, though there is already the `__IMAGE_SUPPORT__` macro which achieves the same thing (even if it doesn't match the naming scheme).

My biggest concern about this feature macro is that it doesn't represent an actual OpenCL 3.0 change, so if is done for orthogonality what about other optional features, such as `double`, or `long` on EMBEDDED profile.   You end up with a lot of spec changes, and effectively two ways of describing the optionality of these "always been optional" features.

**Comment by AnastasiaStulova** [comment]
Yes, I believe the main motivation would be to improve the existing behavior indeed and add mode consistency. And as it became evident that we will be refactoring how optional OpenCL functionality is being supported in clang, it would be good to address as many known issues as possible so we don't have to refector it yet again in a few years time.

As for fp64 and fp16 I don't even think we implement anything else but an extension currently. Also looking at the current spec I am very confused about the behavior of doubles and halfs. For example in section 6.1.1 where we define type only doubles seems to be optional
> The   double   scalar   type   is   an   optional   type   that   is   supported   if   the   value   of   the CL_DEVICE_DOUBLE_FP_CONFIG device query is not zero.

But however it doesn't speak about either feature or extension macros.

However half seem to be mentioned as optional in section 6.13.15  "Work-group Collective Functions".

> [59] Only if the cl_khr_fp16 extension is supported and has been enabled.
> [60] Only if double precision is supported.

Where it appears to be an extension? Double however doesn't?

**Comment by alycm** [comment]
Call 2020-07-21: It was generally agreed that this is tidier.  @alycm will try to propose PR(s) with the changes.

I'll also have a think if there is anything else beyond images/doubles/long that are (sometimes) optional.  But if anyone else things of anything please list them here.

**Comment by alycm** [comment]
I'm starting to write this up.  The name for `__opencl_c_images` is obvious.  For double/long I'm currently using `__opencl_c_fp64` and `__opencl_c_int64` to match `cl_khr_fp64` and `cles_khr_int64`.

The  obvious alternatives are `__opencl_c_double` and `__opencl_c_long`.

**Comment by alycm** [comment]
Atomic longs are independently optional but only via extensions (`cl_khr_int64_base_atomics` and `cl_khr_int64_extended_atomics`).   So I don't think they need a feature macro, as all feature macros are currently for optional core features.

**Comment by bashbaug** [comment]
I think this can be closed now, as #372 is merged, but I'll keep it open another day or so just in case.
