### ISSUE TITLE
OpenCL 2.0 requirement for OpenCL 2.2 devices

### ISSUE THREAD

**Issue by PiotrFusik** [KhronosGroup/OpenCL-Docs#37]
[api/opencl_runtime_layer.txt](api/opencl_runtime_layer.txt#L4016) says:
> OpenCL 2.0 requires that the host and all OpenCL 2.2 devices support
coarse-grained sharing at a minimum.

How is it possible that OpenCL 2.0 makes a requirement for OpenCL 2.2 devices?

**Comment by mkinsner** [comment]
Thanks for reporting this.  I agree that it's a mistake in the spec.

My proposed fix is PR #57
