### ISSUE TITLE
Does OpenCL  C++ Kernel need to be supported in CL3.0 ? Is it a optional feature ?

### ISSUE THREAD

**Issue by luoanquan** [KhronosGroup/OpenCL-Docs#382]
OpenCL  C++ Kernel language is introduced in CL2.2. Do we have to support it in CL3.0，or a optional feature ? This does not seem to be described in the 3.0 spec

**Comment by bashbaug** [comment]
Hi @luoanquan ,

No, the OpenCL C++ kernel language from OpenCL 2.2 is not required in OpenCL 3.0.  Instead, the ecosystem has transitioned to the community-driven “C++ for OpenCL” initiative, which builds upon OpenCL C.
 
For more information, please refer to:

* The main [OpenCL landing page](https://www.khronos.org/opencl/), specifically the section “C++ for OpenCL Kernel Language”.
* The OpenCL 3.0 [slides](https://khr.io/ocl3slidedeck) from IWOCL, specifically slides 7 and 12.
* This Khronos [blog post](https://www.khronos.org/blog/new-and-enhanced-opencl-open-source-tools-resources) describing collaboration with the Clang and LLVM community.

Please feel free to reopen this issue if you have any additional questions - thanks!

**Comment by nicoljl** [comment]
@bashbaug , So what about the “C++ for OpenCL”, is it an optional feature for OpenCL 3.0?

**Comment by AnastasiaStulova** [comment]
Just a small update there is now an extension available for online compilation of C++ for OpenCL:
https://www.khronos.org/registry/OpenCL/extensions/ext/cl_ext_cxx_for_opencl.html
