### ISSUE TITLE
Resequence footnote numbering

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#386]
In a few PRs (https://github.com/KhronosGroup/OpenCL-Docs/pull/372, https://github.com/KhronosGroup/OpenCL-Docs/pull/385) I added additional footnotes without redoing the numbering.

Correct this with proper numbering, either by just manually doing it, or by trying out the Asciidoctor footnote feature [1] so that this doesn't need to be done again in the future.  The only downside of automatic numbering would be that the numbers won't be stable when changes are made -- but they're already potentially not stable, when manual changes are made.

[1] https://asciidoctor.org/docs/user-manual/#user-footnotes

**Comment by bashbaug** [comment]
I'm working on a change now that may add another footnote, which reminded me of this issue.

I think we should seriously consider moving to the Asciidoctor footnote feature to avoid needing to manually resequence footnotes in the future.  The OpenCL SPIR-V Environment specification uses Asciidoctor footnotes for its one footnote ([HTML link](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_Env.html#_footnoteref_1)) and it's pretty nice.  The only slight quirk is that it puts all of the footnotes at the bottom of the HTML document, but it includes links to the footnote itself and links back to the place where the footnote was used (presumably the first place, if the footnote is used multiple times), so it's pretty easy to navigate.

I can take a crack at this if it would be helpful.  One of the things we'd need to decide is whether we put all footnotes inline or whether we have a separate file of "externalized footnotes", but that's fairly minor and we could always switch later.

**Comment by bashbaug** [comment]
Small update / correction: The current Asciidoctor PDF toolchain turns footnotes into "endnotes", so they go at the end of the chapter and not at the bottom of the page.  See:

https://github.com/asciidoctor/asciidoctor-pdf/issues/85

I don't think that's any worse than our current "manual" footnotes, but it's a little quirky and not what I initially expected.  It doesn't sound like bottom-of-page footnotes will be supported for the Asciidoctor PDF toolchain anytime soon.
