### ISSUE TITLE
CL_COMMAND_SVM_MIGRATE_MEM not documented in normative 3.0 specification

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#391]
`CL_COMMAND_SVM_MIGRATE_MEM` is only mentioned once in Appendix E. It should be mentioned in the description for `CL_EVENT_COMMAND_TYPE`. Also we should say what command type is returned for `clEnqueueSVMMigrateMem` prior to 3.0. One option could be to say it's implementation-defined, another to require implementations report `CL_COMMAND_MIGRATE_MEM_OBJECTS`.

**Comment by bashbaug** [comment]
I believe `CL_COMMAND_SVM_MIGRATE_MEM` is described in the normative spec, at least as well as the other `CL_EVENT_COMMAND_TYPEs`.  See the bottom of the table cell, [here](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_EVENT_COMMAND_TYPE).

Admittedly this isn't a very good definition of _any_ of the command types.  It's also a very long table cell, which messes up the PDF rendering (it's possible this is why you didn't see it previously), so I've been thinking of ways to refactor it.  One idea I had was to add a separate table below this one that describes the `CL_DEVICE_COMMAND_TYPE` and the API call that generates it.  Does that sound reasonable?

As for pre-OpenCL 3.0 behavior, I believe our currently shipping, pre-OpenCL 3.0 implementations currently return `CL_COMMAND_MIGRATE_MEM_OBJECTS` for this query, but I think it's best to say implementation-defined before OpenCL 3.0.

**Comment by kpet** [comment]
Agree it's there in the source.

>It's also a very long table cell, which messes up the PDF rendering (it's possible this is why you didn't see it previously)

Yes, that's what's happened. The table line doesn't fit on a page and was cut short in the PDF.

> I believe our currently shipping, pre-OpenCL 3.0 implementations currently return CL_COMMAND_MIGRATE_MEM_OBJECTS for this query, but I think it's best to say implementation-defined before OpenCL 3.0.

I think that's what we do as well IIRC. Agree that implementation-defined is the safest but I still find it tempting to mandate `CL_COMMAND_MIGRATE_MEM_OBJECTS`. I don't think anyone would have done something else here really.
