### ISSUE TITLE
Zero width spaces break search in HTML version of specs in Firefox

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#393]
Searching for enum names in the HTML version of the specification is awkward due to the zero width spaces.  E.g. searching for `CL_DEVICE_NAME` fails due to the zero width spaces

However, search in the HTML version in Chrome is fine.  Search in the PDF version in the viewer I tried is fine.  In fact, even search in the PDF version in Firefox's embedded PDF view is fine!

There is a Firefox bug about this: https://bugzilla.mozilla.org/show_bug.cgi?id=389651

Replacing the zero width spaces with a `<wbr>` tags in the HTML output works in both Firefox and Chrome:

```sh
sed -i out/html/OpenCL_API.html -e 's/&#8203;/<wbr>/g'
```
However, adjusting the script that inserts `&#8203` into the Asciidoctor to use `<wbr>` instead breaks PDF rendering.

**Comment by bashbaug** [comment]
I've been playing around with this and I think we can solve this problem in one of two ways:

1. We could add the `sed` line above into the Makefile, to fixup the HTML files after generation.
2. We could modify the dictionary generation scripts to generate one attribute for HTML backends and another attribute for PDF backends:

```asciidoc
// CL_CHAR_BIT
ifdef::basebackend-html[]
:CL_CHAR_BIT_label: pass:q[`CL_<wbr>CHAR_<wbr>BIT`]
endif::basebackend-html[]
ifdef::backend-pdf[]
:CL_CHAR_BIT_label: pass:q[`CL_&#8203;CHAR_&#8203;BIT`]
endif::backend-pdf[]
:CL_CHAR_BIT: <<CL_CHAR_BIT,{CL_CHAR_BIT_label}>>
:CL_CHAR_BIT_anchor: [[CL_CHAR_BIT]]{CL_CHAR_BIT}
```

I tried using `ifndef` to effectively have an "HTML path" and a "non-HTML path" but it didn't seem to be working for me - I'll look into this a bit more if we decide to go this route.  I don't see an asciidoctor preprocessor `else`.

I also tried using the asciidoctor attribute `{zwsp}`, thinking this might expand differently for the HTML and PDF backends, but it doesn't look like it does, so this isn't a viable solution.
