### ISSUE TITLE
Querying CL_QUEUE_SIZE for non-Device Queues

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#402]
The current description for `clGetCommandQueueInfo(CL_QUEUE_SIZE)` is:

> Return the currently specified size for the device command-queue. This query is only supported for device command queues.

It's not clear what "this query is only supported for device command queues" means though.  Specifically:

* Is it an error to perform this query on a non-device queue?  If so, what should the error condition be?
* Or, does the query return a known quantity (such as `0`) for a non-device queue?
* Or, something else entirely?

FWIW, the current text in [Appendix H for Device-Side Enqueue](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#_device_side_enqueue) says that calling:

> clGetCommandQueueInfo, passing CL_​QUEUE_​SIZE... Returns 0 if the device associated with command_queue does not support On-Device Queues.

Depending how we resolve this issue we may need to update this text as well.

**Comment by kpet** [comment]
Other entry points that only accept a host queue only must return `CL_INVALID_COMMAND_QUEUE` when passed a device queue. Maybe we should do the same here? An application/framework/debugger could still disambiguate the failure from "the queue is corrupt or generally invalid" by performing another query.

**Comment by bashbaug** [comment]
I believe our current GPU implementation returns `CL_INVALID_VALUE` in this case, with the rationale that `CL_QUEUE_SIZE` is "not one of the supported values" for the passed-in command queue.  I think `CL_INVALID_COMMAND_QUEUE` could be justified as well; it just depends whether you're considering the command queue invalid for the query, or the query invalid for the command queue.

I think it would still be an upgrade to change the description for this query from "this query is only supported for device command queues" to "it is an error to query the queue size when the command queue is not a valid device command queue", even if we do not mandate a specific error value.

Shall I create a PR with these changes for additional discussion?  I will include an update to Appendix H to reflect that this query will return an error as well when On-Device Queues are not supported.

**Comment by bashbaug** [comment]
Discussed in the August 18th teleconference.  We will return an error when querying `CL_QUEUE_SIZE` for a host queue and the returned error will be `CL_INVALID_COMMAND_QUEUE`.
