### ISSUE TITLE
Atomic Capabilities Query Consistency

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#404]
A few questions came up in the review of the API consistency CTS test:

https://github.com/KhronosGroup/OpenCL-CTS/pull/875

For reference, the two atomic capability queries are:

* [CL_DEVICE_ATOMIC_MEMORY_CAPABILITIES](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#CL_DEVICE_ATOMIC_MEMORY_CAPABILITIES)
* [CL_DEVICE_ATOMIC_FENCE_CAPABILITIES](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#CL_DEVICE_ATOMIC_FENCE_CAPABILITIES)

Specific questions are:

* If the atomic capabilities query indicates support for `CL_DEVICE_ATOMIC_SCOPE_ALL_DEVICES`, must the capabilities query also indicate support for `CL_DEVICE_ATOMIC_SCOPE_DEVICE`?
* If the atomic capabilities query indicates support for `CL_DEVICE_ATOMIC_SCOPE_DEVICE`, must the capabilities query also indicate support for `CL_DEVICE_ATOMIC_SCOPE_WORK_GROUP`?

Additionally, we should consider:

* If the atomic capabilities query indicates support for `CL_DEVICE_ATOMIC_ORDER_SEQ_CST`, must the capabilities query also indicate support for `CL_DEVICE_ATOMIC_SCOPE_ACQ_REL`?
* If the atomic capabilities query indicates support for `CL_DEVICE_ATOMIC_ORDER_ACQ_REL`, must the capabilities query also indicate support for `CL_DEVICE_ATOMIC_SCOPE_RELAXED`?

**Comment by kpet** [comment]
Discussed on the 2020/08/18 teleconference: if we don't require weaker/narrower capabilities to be reported when stronger/wider are, then we could use their presence to mean that there is a performance advantage to using the weaker atomics/narrower scope. @alycm  observed that this would force applications who only require a weaker capability to test for the presence of stronger ones as well.

Is this worth doing? Would it be better to introduce additional queries to report information on the performance (e.g. preferred atomic scope or memory ordering)? Could library functions bridge the gap?

**Comment by alycm** [comment]
I was expecting that implementations would report all valid values, like with other CAPABILITIES or CONFIG queries.   But I'm not sure any of the other such queries exhibit the strict nesting seen with these queries (or if they do they report a single numeric maximum value, such as maximum work-group sizes).

Most programmers will have one version of their algorithm/kernel, it will need at least scope/order X/Y.  If all valid scope/order are reported then they can just check the X/Y they need.  If only the strongest/widest is guaranteed to be reported then they must check for X, or X+1, ... and Y, or Y+1, ...   This is of course very formulaic and there could be a helper function in the headers, I'm not sure how to indicate that it's there without referencing it in the spec though.

Some subset of programmers may have different versions of their algorithm/kernel depending on whether weaker/narrower capabilities provide a performance advantage or not (or auto-generate such kernels).  On some hardware the weaker/narrower form will provide advantages, on some they'll just map to the same instructions as the stronger/wider forms, reporting all supported modes obscures this information from the programmer.

In principle providing extra information to the second kind of programmer lets them make better choices.  In practice I suspect that programming at that level involves manual experiments/tuning per-device or some kind of auto-tuning approach.  I have no data on that though, and OpenCL of course already has many `CL_DEVICE_PREFERRED_FOO` queries.

My mild preference would be for CAPABILITIES queries to report the complete set of capabilities of a device, and in the future have separate PREFERRED queries to report the "strongest/widest form of the fastest option" or similar.
