### ISSUE TITLE
Error Codes for Unsupported Functionality

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#408]
When an optional feature is not supported in OpenCL 3.0 we currently use two classes of error codes.  See, for example, the error codes returned by pipe functions when pipes are not supported ([spec link](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#_pipes_2)):

* If a suitable error code did NOT exist in a prior version of OpenCL then the unsupported API returns `CL_INVALID_OPERATION`.  This is the case for `clCreatePipe`.
* If a suitable error code DID exist in a prior version of OpenCL then the unsupported API will return that error code instead.  This is the case for `clGetPipeInfo`, which returns `CL_INVALID_MEM_OBJECT`, since it is impossible to pass in a valid pipe object if pipes are not supported.

This issue is regarding the second item: Is it better to reuse existing error codes when a feature is not supported, limiting the error cases for e.g. `clGetPipeInfo`, or should we use a different error code instead to more clearly identify that the feature isn't supported?

**Comment by Kerilk** [comment]
From a loader perspective, it would be nice to have a unique unsupported feature error code. This error code could be used when the loader detects a call to an unsupported function (eg 2.2 API call for a 1.2 platform). This is not easily doable for now, but new loader strategies may facilitate this behavior.

**Comment by bashbaug** [comment]
It may be easier to review with a list of APIs that would be affected.  They are:

* clGetPipeInfo (Pipes)
* clCreateProgramWithIL, clSetProgramSpecializationConstant (IL Programs)

These APIs are not affected since they already return `CL_INVALID_OPERATION` when the feature is not supported:

* clEnqueueSVMFree, clEnqueueSVMMemcpy, clEnqueueSVMMemFill, clEnqueueSVMMap, clEnqueueSVMUnmap, clEnqueueSVMMigrateMem, clSetKernelArgSVMPointer, clSetKernelExecInfo (SVM)
* clSetDefaultDeviceCommandQueue (Device-Side Enqueue)
* clCreatePipe (Pipes)
* clCreateImage, clCreateImageWithProperties (Creating 2D Images from Buffers)
* clGetDeviceAndHostTimer, clGetHostTimer (Device and Host Timer Synchronization)
* clGetKernelSubGroupInfo (Subgroups)
* clSetProgramReleaseCallback (Program Initialization and Clean-Up Kernels)

So, it is a pretty small set of changes if we do decide to go this route.

**Comment by bashbaug** [comment]
Discussed in the August 25th teleconference.  We will return `CL_INVALID_OPERATION` consistently when the feature is unsupported.  I will create a spec PR to update the error descriptions for the three APIs above, and I will modify the feature consistency test to check for the updated error codes.

**Comment by bashbaug** [comment]
I've created #418 with these changes.

As mentioned on the PR, the one case where a different error code may be returned is for clGetPipeInfo, since ICD implementations cannot create a valid pipe memory object to query and get the ICD dispatch table from. In these cases, the ICD loader will return CL_INVALID_MEM_OBJECT before calling into the ICD implementation. Note that non-ICD implementations may return CL_INVALID_OPERATION unconditionally, and I've updated the error conditions for clCreateProgramWithIL and clSetProgramSpecializationConstant.

**Comment by bashbaug** [comment]
For record keeping purposes, there was quite a bit of additional discussion on the PR to resolve this issue, especially:

https://github.com/KhronosGroup/OpenCL-Docs/pull/418#discussion_r478742972

In short, on the PR we concluded that it would be possible to return `CL_INVALID_OPERATION` from `clGetPipeInfo` if an implementation doesn't support pipes even with an ICD implementation by calling into `clGetPipeInfo` using some other non-pipe memory object.  While this is true and enables an implementation that never supports pipes to return `CL_INVALID_OPERATION` unconditionally from `clGetPipeInfo`, it does pose a problem for an implementation that supports pipes for _some_ devices but not all.  In this case, the implementation needs to look up information from the pipe to determine if pipes are supported (the context, for example), but this becomes very awkward because the pipe isn't a valid pipe object, so it's much more natural to return `CL_INVALID_MEM_OBJECT` instead.

While we could special-case this scenario in our implementation it seems like more trouble than it's worth.  Therefore, I'd like to allow `CL_INVALID_MEM_OBJECT` as a valid error code from `clGetPipeInfo` when pipes are not supported, in addition to `CL_INVALID_OPERATION`.  This will require a change to the yet-to-be-merged CTS test at the very least, and also possibly a change to the spec appendix.  I don't think we need to make a change to the main spec text, since all of the error code descriptions are still valid and this is quite the corner case, but I'm open to a change to the main spec text also to clarify this scenario if it would be helpful.

**Comment by bashbaug** [comment]
Discussed in the September 8th teleconference.  We agreed to change the error code for `clGetPipeInfo` when pipes are not supported from `CL_INVALID_OPERATION` to `CL_INVALID_MEM_OBJECT` exclusively, to avoid the situation described above and to avoid having two valid error codes, even though it is a little inconsistent with other APIs that will return `CL_INVALID_OPERATION`.

My action items are:

* Update the spec PR to switch error codes.  I will do this shortly since this PR hasn't been merged yet.
* Update the CTS test to switch error codes.  This will require a new PR and I will file an issue to track it.
* File a post-3.0 issue to investigate options to improve error behavior for this scenario in the future.
