### ISSUE TITLE
Value returned for CL_MEM_PROPERTIES for sub-buffers

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#412]
There is currently no API call to create a sub-buffer with properties. What should CL_MEM_PROPERTIES return for sub-buffers? Are (some) properties inherited from the parent buffer?

**Comment by bashbaug** [comment]
I think there are two options that could make sense:

1. There are no properties returned for a sub-buffer created by `clCreateSubBuffer`, just like there are no properties returned for a buffer created using the traditional `clCreateBuffer`.  This leaves the door open for a future `clCreateSubBufferWithProperties`, if desired.  Note that if an application wants to query the properties of the parent buffer it can do so by querying the parent buffer using `CL_MEM_ASSOCIATED_MEMOBJECT` and then querying its properties directly.

2. The properties are inherited from the parent buffer, similar to the way some memory flags are inherited from the parent buffer.

I have a preference for (1) but I'd be OK with (2).  Are there any other options we should consider?

**Comment by kpet** [comment]
I have a strong preference for 1. It's simple and well-defined and we don't paint ourselves in a corner. I think inheriting properties could lead to awkward situations with extensions adding properties that would be nonsensical for sub-buffers.

**Comment by bashbaug** [comment]
I think we should just go with (1) then, unless someone wants to champion a different option.  Spec-wise I think this is as simple as adding a PR to add clCreateSubBuffer to the list of APIs that must return no properties:

> If memobj was created using clCreateBuffer, **clCreateSubBuffer**, clCreateImage, clCreateImage2D, or clCreateImage3D, or if the properties argument specified in clCreateBufferWithProperties or clCreateImageWithProperties was NULL, the implementation must return param_value_size_ret equal to 0, indicating that there are no properties to be returned.

I can get that out today.  We'd also want a CTS for this case.

**Comment by kpet** [comment]
Works for me. +1 on the CTS test.
