### ISSUE TITLE
clCreateImage USE_HOST_PTR clarification

### ISSUE THREAD

**Issue by raunraun** [KhronosGroup/OpenCL-Docs#417]
Between OpenCL 2.1 and 2.2 we added the following to clCreateImage:

> host_ptr is a pointer to the image data that may already be allocated by the application. **It is only used  to  initialize  the  image,  and  can  be  freed  after  the  call  to  clCreateImage.**

This seems to imply that USE_HOST_PTR is identical to COPY_HOST_PTR.  Is this intended?

**Comment by kpet** [comment]
That seems in direct contradiction with the description for `clEnqueueMapImage`:

>If the image object is created with CL_MEM_USE_HOST_PTR set in mem_flags, the following will be true:
>• The host_ptr specified in clCreateImage, clCreateImageWithProperties, clCreateImage2D, or
clCreateImage3D is guaranteed to contain the latest bits in the region being mapped when the
clEnqueueMapImage command has completed.

This is also not backwards compatible. This looks like a mistake to me.

**Comment by raunraun** [comment]
We probably need clarification for create from buffer too.  I think in that case USE_HOST_PTR  either is not allowed or behaves as COPY_HOST_PTR like the current description says.

**Comment by bashbaug** [comment]
For Khronos folks, the OpenCL 2.2 change was described in Bugzilla 15425.

I think this change was a mistake though and should be reverted.

The original Bugzilla concerned creating an image from a buffer, which is separate from `USE_HOST_PTR`.  We already disallow mixing `USE_HOST_PTR` and creating an image from a buffer via the following `clCreateImage` error condition:

> `CL_INVALID_VALUE` if an image is being created from another memory object (buffer or image) under one of the following circumstances: <snip> 3) _flags_ specifies `CL_MEM_USE_HOST_PTR` or `CL_MEM_ALLOC_HOST_PTR` or `CL_MEM_COPY_HOST_PTR`.

IMHO the sentence highlighted above should be removed:

> It is only used to initialize the image, and can be freed after the call to clCreateImage.

Are any additional changes needed, or is this sufficient?

**Comment by jlewis-austin** [comment]
I couldn't find any additional changes needed.
