### ISSUE TITLE
Error code from clCreateProgramWithIL when IL is not supported

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#422]
Currently appendix H says that `clCreateProgramWithIL` will:

> Returns CL_INVALID_VALUE if no devices in context support Intermediate Language Programs.

But other functions in a similar situation return `CL_INVALID_OPERATION`, including other `clCreateFoo` functions.  Should `clCreateProgramWithIL` also return `CL_INVALID_OPERATION` here?

Either leaving the error code as is or changing it, the error condition should also be added to the main body text for `clCreateProgramWithIL`.

**Comment by bashbaug** [comment]
#418 changes the error code for `clCreateProgramWithIL` to `CL_INVALID_OPERATION` for this case in both the main body text and in the appendix.  I think we'll be OK when it gets merged?

**Comment by alycm** [comment]
Of course, really not sure how I missed that, it was while reviewing that PR that though I noticed this point.
