### ISSUE TITLE
Allow clBuildProgram to return CL_COMPILER_NOT_AVAILABLE for IL programs

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#438]
Currently `clBuildProgram` has an error condition:

> CL_COMPILER_NOT_AVAILABLE if program is created with clCreateProgramWithSource and a compiler is not available i.e. CL_DEVICE_COMPILER_AVAILABLE specified in the Device Queries table is set to CL_FALSE.

I think this should be:

> CL_COMPILER_NOT_AVAILABLE if program is created with clCreateProgramWithSource **or clCreateProgramWithIL** and a compiler is not available i.e. CL_DEVICE_COMPILER_AVAILABLE specified in the Device Queries table is set to CL_FALSE.

Emphasis just for clarity here, not what would go in the specification.

I don't know if any existing 2.1 implementations support a compiler-less configuration, but if they do I don't see what else they could do for the `clCreateProgramWithIL` case.

**Comment by kpet** [comment]
Makes sense to me. We'll want tests for that as well. I've created https://github.com/KhronosGroup/OpenCL-CTS/issues/955.

**Comment by alycm** [comment]
I've realized that the CTS doesn't actually support the `CL_DEVICE_COMPILER_AVAILABLE` is `CL_FALSE ` while `CL_DEVICE_IL_VERSION` is `"SPIR-V_1.0"` case.   But I think that is a CTS issue rather than the combination being invalid.  CTS ticket: https://github.com/KhronosGroup/OpenCL-CTS/issues/956

**Comment by alycm** [comment]
I'm actually now wondering if `clSetProgramSpecializationConstant` should also return `CL_DEVICE_COMPILER_AVAILABLE`.   It's maybe not strictly required, but there is really no point setting a specialization constant if you cannot call `clBuildProgram`.
