### ISSUE TITLE
Representing conditional defines in the XML file

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#463]
There are a couple of places in the OpenCL extension headers where enums or types are conditionally defined.  A few examples:

https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl_ext.h#L32

```c
#if CL_TARGET_OPENCL_VERSION <= 110
#define CL_DEVICE_DOUBLE_FP_CONFIG                       0x1032
#endif
```

https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl_ext.h#L508

```c
#if !defined(CL_VERSION_2_1)
/* For OpenCL 2.1 and newer, cl_kernel_sub_group_info is declared in CL.h.
   In hindsight, there should have been a khr suffix on this type for
   the extension, but keeping it un-suffixed to maintain backwards
   compatibility. */
typedef cl_uint             cl_kernel_sub_group_info;
#endif
```

What is the best way to represent these conditions in the XML file?

Tagging @oddhack since perhaps there is already a convention we can borrow from other XML files.

**Comment by oddhack** [comment]
There isn't any existing schema for this. If I were doing this I'd approach it through the \<require> tag. While that normally requires an API extension to support the features inside the tag, you could add an attribute for something like \<require condition="CL_TARGET_OPENCL_VERSION <= 110"> and use that literal string in a generated preprocessor wrapper - or, if you needed the semantics of the condition to be comprehensible to an output generator, some more complex attribute grammar.

**Comment by bashbaug** [comment]
Closing for now - I'll reopen if something comes up in the review of #469.
