### ISSUE TITLE
SPIR-V Environment Spec Does Not Define Builtin Variables

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#466]
The SPIR-V specification says of many Builtin Variables

> See the client API specification for more detail.

But the SPIR-V environment spec does not define them.  If someone is already familiar with the concept at hand then I think in all instances they can infer which OpenCL builtin it is equivalent to from name or by a little fuzzy searching.  But for people less familiar having an explicit mapping seems helpful.

The Vulkan spec [fully defines](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#interfaces-builtin-variables) the appropriate builtin variables, but for OpenCL there is definitely the option of referring to OpenCL C semantics to avoid duplication.

List of builtin variables that I think apply (i.e. have no enabled capabilities or are enabled by the Kernel capability):
- NumWorkgroups
- WorkgroupSize
- WorkgroupId
- LocalInvocationId
- GlobalInvocationId
- LocalInvocationIndex
- WorkDim
- GlobalSize
- EnqueuedWorkgroupSize
- GlobalOffset
- GlobalLinearId
- SubgroupSize
- SubgroupMaxSize
- NumSubgroups
- NumEnqueuedSubgroups
- SubgroupId
- SubgroupLocalInvocationId

**Comment by alycm** [comment]
For interest, this came up locally when someone who was only familiar with OpenCL 1.2 saw `EnqueuedWorkgroupSize` for the first time, the SPIR-V specification pointed them to the client specification, but they couldn't find the name there.

**Comment by AlexeySachkov** [comment]
+1 here, we had a similar question during development of KhronosGroup/SPIRV-LLVM-Translator#690: how elements of `LocalInvocationId` are mapped to dimension indices in OpenCL ND-range index space? Looking at the spec right now I can't even find an info about what should be the type of variable marked with `LocalInvocationId`?

**Comment by bashbaug** [comment]
There is a lot of overlap between this issue and #279.  I agree there are improvements we could make in this area.

**Comment by alycm** [comment]
Yes, in fact #279 even contains the mapping I meant.

**Comment by bashbaug** [comment]
Is anything more needed here, or can we close this issue (by #279)?

**Comment by alycm** [comment]
Yes, this was resolved by #279, closing.
