### ISSUE TITLE
Enable links in the specification PDFs

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/OpenCL-Docs#47]
As mentioned in #6,  the new formatting of the specifications since OpenCL 2.2 rev.8 is really nice.

One missing feature would be to have links in the documentation:
* clicking on `clFinish` on page 32 could bring you to the page containing the documentation for that function;
* clicking on the page numbers or section names in the ToC should bring you to the pages containing them;
* clicking on links (for example on page 1, the Khronos’ adopters webpage) should open them in the browser;
* there are several words/concepts that are highlighted in blue, almost like an URL, but that actually do nothing (for example on page 12 under “Happens before”, “Memory Model: Memory Ordering Rules”): clicking on those could bring you directly to the referenced section (in this case, section 3.3.6 on page 42).

**Comment by bashbaug** [comment]
Great minds think alike - this is one of the spec improvements we discussed at last week's face-to-face, and we're looking at ways to enable this functionality.

**Comment by pierremoreau** [comment]
Awesome, looking forward to it!

**Comment by bashbaug** [comment]
I've made a fair amount of progress on feature.  It's not done yet, but I think I have enough to share, if you (or anyone else) would like to play around with the new linking.

My work is staged here.  Note that this is baselined on the "refpages" branch, which contains some other unrelated changes, so diff'ing against master will show more than just the changes for improved linking.

https://github.com/bashbaug/OpenCL-Docs/tree/api-enum-links

The basic idea is to use an updated cl.xml grammar to automatically build a "dictionary" of asciidoc attributes for APIs and enums, and then to use them in the spec to link to their definitions.  As an added bonus, this  enforces consistent formatting for APIs and enums, and makes it easy to identify misspelled or missing APIs or enums (you'll still see a few of these, as we figure out how to reconcile differences between the spec and the grammar).

I'm mostly interested in high-level comments right now, I think: Is this helpful? Is the formatting OK?

I know there are some "missing links" right now, particularly for error codes, so clicking on them currently does nothing.  We'll need to figure out what to do with them eventually.

Thanks!

Note, this is a compressed HTML file (github won't let me attached the HTML file directly):

* [OpenCL_API.tar.gz](https://github.com/KhronosGroup/OpenCL-Docs/files/2932799/OpenCL_API.tar.gz)

**Comment by pierremoreau** [comment]
Thank you for working on it! I’ll have a look at it over the weekend. :slightly_smiling_face:

**Comment by alycm** [comment]
Comment from Ben on extending this to the extension spec:
* https://github.com/KhronosGroup/OpenCL-Docs/pull/75#discussion_r282273061
* The API spec is mostly "self-contained", for the most part. Other than these two items in the appendix, I think the only linking is to other locations in the same doc.
* By contrast, I suspect the extension spec will contain links to the extension spec and to the API spec (and, possibly, to the OpenCL C spec). I'm not quite sure how to handle this yet...

**Comment by pierremoreau** [comment]
All missing features seem to have made it into the unified specification, so closing this issue.

Thank you a lot for all the hard work in making the specification more readable and allowing easier navigation within it!
