### ISSUE TITLE
Specification of __OPENCL_VERSION__ macro

### ISSUE THREAD

**Issue by StuartDBrady** [KhronosGroup/OpenCL-Docs#471]
The unified OpenCL C specification states that the predefined `__OPENCL_VERSION__` macro:

> Substitutes an integer reflecting the version number of the OpenCL supported by the OpenCL device. The version of OpenCL described in this document will have `__OPENCL_VERSION__` substitute the integer 300.

These two statements are contradictory.

For an OpenCL 2.1 implementation, the integer suggested by the former statement would be 210, and not 300. For future OpenCL versions, one would expect an `__OPENCL_VERSION__` greater than 300, even if the OpenCL C language specification is not updated.

Note that there are OpenCL 2.1 implementations that have passed conformance that defien `__OPENCL_VERSION__` as 200, and not 210.

Note also issue #249, which raises the issue of the lack of `CL_VERSION_2_1` and `CL_VERSION_2_2` macros in the OpenCL C specification. It is reasonable that there are not provided by OpenCL 2.0 implementations, but it is unclear if these should be defined for more recent versions of OpenCL.

**Comment by alycm** [comment]
I think that the definition of `__OPENCL_VERSION__` could just be

> Substitutes an integer reflecting the version number of the OpenCL supported by the OpenCL device.

I.e. delete the second contradictory line (I did this for `__OPENCL_C_VERSION__` but clearly missed this one).

> Note that there are OpenCL 2.1 implementations that have passed conformance that defien __OPENCL_VERSION__ as 200, and not 210.

Ah, that gets a bit tricky.  An OpenCL 2.1 implementation of course uses OpenCL C 2.0, which says to use 200.   So the implementation is following the word of the specification.  But my suggested wording would not cover that case, so to quote your comment on #249:

> If none of the OpenCL 2.1 or OpenCL 2.2 implementations actually define it as 210 or 220, then it may be best instead to define it as 200 for those versions, stating this discrepancy explicitly in the specification.

If that is what all 2.1 implementations do then that may be the pragmatic choice.

**Comment by bashbaug** [comment]
FWIW, our OpenCL 2.1 implementations appear to define `__OPENCL_VERSION__` as 210 (sorry!).

**Comment by StuartDBrady** [comment]
It's unclear to me how we should progress from this.

It may be worth considering deprecating `\_\_OPENCL\_VERSION\_\_` as it seems it cannot be safely relied upon, and it seems to be of little real use, anyway. However, I am unsure how this would be handled when using future versions of OpenCL together with old versions of OpenCL C. `\_\_OPENCL\_VERSION\_\_` is defined in all versions of OpenCL C going back to OpenCL 1.0, and `\_\_OPENCL\_C\_VERSION\_\_` was added in OpenCL 1.2.

Given that the Intel implementations define `\_\_OPENCL\_VERSION\_\_` as 210, I feel the specification should at least encourage the macro to be defined as 210 for all OpenCL 2.1 implementations. I also wonder if the specification should encourage `CL_VERSION_2_1` and `CL_VERSION_2_2` macros to be defined, even though this cannot be mandated. (Note: Clang's {{opencl-c-base.h}} does not define these macros.)

**Comment by bashbaug** [comment]
Note, if you're compiling offline to SPIR-V, you don't know what device you may ultimately be executing on.  In this case what would `__OPENCL_VERSION__` represent?  Likewise, what would a tool like clspv do for `__OPENCL_VERSION__`?

Could we deprecate `__OPENCL_VERSION__` and say that it must be defined but it has no dependable value, at least for newer OpenCL devices or OpenCL C versions (2.1 or newer? 3.0 or newer?)?  I can't recall seeing any code that uses it.

**Comment by AnastasiaStulova** [comment]
I would vote for deprecating it too as there is no sensible way to set it in the common open-source tools. As a result for example stand-alone clang can never be fully OpenCL compliant or implement OpenCL C fully.

**Comment by StuartDBrady** [comment]
I would agree with this.

Unfortunately, we would only get to deprecate it in OpenCL C. As it's part of the language, it would need to be defined when compiling OpenCL C 1.2 source with an OpenCL 3.0 driver.  In principle, we could make an exception and say that `__OPENCL_VERSION__` does not need to be defined when using an OpenCL 3.0 driver, but this would not be fully compatible with the previous behavior.

@bashbaug, does the Intel implementation define `CL_VERSION_2_1` and/or `CL_VERSION_2_2`.

**Comment by bashbaug** [comment]
> does the Intel implementation define `CL_VERSION_2_1` and/or `CL_VERSION_2_2`?

No, it doesn't look like we've defined either `CL_VERSION_2_1` or `CL_VERSION_2_2`, though interestingly it looks like we have defined `CL_VERSION_3_0`.

Sample kernel:

```c
kernel void Test( global uint* dst )
{
    int index = get_global_id(0);
    if (index == 0) {
        printf("__OPENCL_VERSION__ is %d, __OPENCL_C_VERSION__ is %d\n", __OPENCL_VERSION__, __OPENCL_C_VERSION__);
#if defined(CL_VERSION_2_1)
        printf("CL_VERSION_2_1 is %d\n", CL_VERSION_2_1);
#else
        printf("CL_VERSION_2_1 is NOT defined.\n");
#endif
#if defined(CL_VERSION_2_2)
        printf("CL_VERSION_2_2 is %d\n", CL_VERSION_2_2);
#else
        printf("CL_VERSION_2_2 is NOT defined.\n");
#endif
#if defined(CL_VERSION_3_0)
        printf("CL_VERSION_3_0 is %d\n", CL_VERSION_3_0);
#else
        printf("CL_VERSION_3_0 is NOT defined.\n");
#endif
    }
}
```

Without passing any special build options and with our [latest drivers](https://github.com/intel/compute-runtime/releases/tag/20.47.18513) this prints:

```
__OPENCL_VERSION__ is 300, __OPENCL_C_VERSION__ is 120
CL_VERSION_2_1 is NOT defined.
CL_VERSION_2_2 is NOT defined.
CL_VERSION_3_0 is 300
```

**Comment by bashbaug** [comment]
Proposal:

* When compiling online (e.g. via `clCreateProgramWithSource`) for OpenCL devices with version less than or equal to OpenCL 2.0, `__OPENCL_VERSION__` must be defined and must be the OpenCL version for the device.  This preserves backwards compatibility for earlier versions of OpenCL and OpenCL C.

* When compiling online for OpenCL devices with version greater than OpenCL 2.0, `__OPENCL_VERSION__` is deprecated. 
 It must be defined but may have any implementation-defined value.  This covers the differing behavior between shipping OpenCL 2.1 implementations and properly signals that this value should not be used in the future.

    * Note: we could require a specific value for OpenCL 3.0 devices if desired, but given comments about the usefulness of this macro and difficulties with offline compilation (see below) I think deprecating is fine.

* Similarly, when compiling offline where there is no OpenCL device and hence no OpenCL version, `__OPENCL_VERSION__` is deprecated, must be defined, but may have any implementation-defined value.  This covers any offline OpenCL C compiler such as clang, clspv, etc.

If this looks good next step is to translate the proposal into a spec language PR.

**Comment by bashbaug** [comment]
Proposed update to the second bullet above: change "must be defined but may have any implementation-defined value" to "must be defined but may have any implementation-defined value greater than or equal to `CL_VERSION_2_0`."

Also, note that in the third bullet the value of `__OPENCL_VERSION__` is a property of the tooling and outside of the scope of the spec, strictly speaking, though we could describe this scenario explicitly to avoid confusion.

Waiting for a thumbs-up and then I will start drafting the spec PR.

**Comment by AnastasiaStulova** [comment]
> update to the second bullet above: change "must be defined but may have any implementation-defined value" to "must be defined but may have any implementation-defined value greater than or equal to `CL_VERSION_2_0`."

 If kernel code contains something like

`#if __OPENCL_VERSION__ == CL_VERSION_1_2`

with this change, it is not conformant anymore so it might fail to compile? Perhaps we should avoid defining any concrete value?

**Comment by bashbaug** [comment]
> with this change, it is not conformant anymore so it might fail to compile?

Yes, this is true, however the same code may also fail to compile on an OpenCL 2.0 implementation, so I'd argue it's fundamentally broken and we don't need to worry about it.

The case I think we should consider is code that does this:

```c
#if __OPENCL_VERSION__ >= 120
```

This would break if we allowed any arbitrary implementation-defined value for `__OPENCL_VERSION__`, but would continue to work so long as we require a value greater than or equal to `CL_VERSION_2_0` == 200.

**Comment by StuartDBrady** [comment]
The proposals here make a good amount of sense to me. Before getting into the details, it might help to take stock of the situation:

* OpenCL 1.0/OpenCL 1.1 devices should not define `__OPENCL_VERSION__`.
* OpenCL 1.2 devices must define `__OPENCL_VERSION__` as 120.
* OpenCL 2.0 devices must define `__OPENCL_VERSION__` as 200.
* It is not specified as to how OpenCL 2.1 and OpenCL 2.2 devices should define `__OPENCL_VERSION__`, but we have instances of devices defining it as 200 and instances of 210 and 220.
* The OpenCL 3.0 specification seems to indicate that `__OPENCL_VERSION__` must be 300, even on hypothetical OpenCL 4.0 devices. This was clearly not the intent. We should read this instead as saying that OpenCL 3.0 devices must define `__OPENCL_VERSION__` of 300.
* When compiling into SPIR-V, there would be no obvious value to define `__OPENCL_VERSION__` as.
* The specifications do not state that the choice of language version via `-cl-std=` should in any way affect the definition of `__OPENCL_VERSION__`, but it is reasonable to assume that for some implementations, they might.

Essentially, I would like to see:

* Required behaviour for OpenCL 1.x/2.x devices should (continue to?) match existing implementations.
* Required behaviour for OpenCL 1.x/2.x should not be made overly permissive, i.e. it should not permit defining `__OPENCL_VERSION__` as 300 for an OpenCL 1.2 device.
* Deprecation of `__OPENCL_VERSION__` for OpenCL 3.0 onwards.
* Removal of (and forbidding of) the definition of `__OPENCL_VERSION__` for future OpenCL versions.

Furthermore, it would make sense to me for:

* OpenCL 2.1 devices to be required to define `__OPENCL_VERSION__` as either 200 or 210.
* OpenCL 2.2 devices to be required to define `__OPENCL_VERSION__` as either 200 or 220.
* OpenCL 3.0 devices not to be required to define `__OPENCL_VERSION__` at all, but to be permitted to define it as 300.

As @bashbaug has noted, though, that OpenCL 3.0 devices need not implement all of the functionality of OpenCL 2.x devices, so if a program tests `__OPENCL_VERSION__ >= 200`, then defining `__OPENCL_VERSION__` as 300 may falsely indicate to programs that all OpenCL 2.0 features are supported. Unless `__OPENCL_VERSION__` were to be defined as 120 for OpenCL 3.0 devices, there seems no way to avoid this. Defining `__OPENCL_VERSION__` as 120 might actually make a lot of sense for OpenCL 3.0 devices, but I am concerned that it is now too late. In any case, if `__OPENCL_VERSION__` is defined for OpenCL 3.0 devices, it would seem to make sense to require the definition to be either 120 or 300.

Essentially, if we just tighten up "arbitrary implementation-defined value" a little, the proposals seem good.

**Comment by StuartDBrady** [comment]
An unstated assumption here is that we're saying that `__OPENCL_VERSION__` was never _truly_ part of the language specification in the first place, and we're free to let the OpenCL device version determine whether/how it is defined. This seems to me to be the only reasonable path forwards.

**Comment by AnastasiaStulova** [comment]
While I agree that value `120` would make more sense for OpenCL 3.0, OpenCL 2.0 implementation will be broken if we define the value uniformly for every version. Even if OpenCL 3.0 is a way forward we shouldn't ignore that there are many OpenCL 2.0 conformant implementations that will continue to exist for some time so I am not sure I would be comfortable if we favor certain versions over others.

I feel the best approach might be just to document what this macro's original intent was - something like:
> The macro represents the version of the runtime (API) compiled for and will be set to `120` if compiled with OpenCL 1.2 runtime or `200`/`210`/`220` if compiled with OpenCL 2.0/2.1/2.2 runtime, `300` if compiled for OpenCL 3.0 runtime. If runtime is unknown i.e. for offline compilations into binary or IL, the macro is implementation-defined. 

I would also prefer if we add that for offline compilation it is not guaranteed whether the macro is defined so that the open-source tooling behavior is conformant.

**Comment by alycm** [comment]
As @StuartDBrady says, the "Essentially, I would like to see" part of his comment is just slightly tightening up @bashbaug's proposal.

Of the "Furthermore, it would make sense to me for:" comments I'm neutral on the 200/210/220 parts, but the suggestion for

> OpenCL 3.0 devices not to be required to define __OPENCL_VERSION__ at all, but to be permitted to define it as 300.

is a bit too rapid.  The deprecation alone seems safer, and for 1.2 backwards compatibility at least ensures that the macro is present (even if the value has changed).

**Comment by StuartDBrady** [comment]
> Of the "Furthermore, it would make sense to me for:" comments I'm neutral on the 200/210/220 parts, but the suggestion for
> 
> > OpenCL 3.0 devices not to be required to define **OPENCL_VERSION** at all, but to be permitted to define it as 300.
> 
> is a bit too rapid. The deprecation alone seems safer, and for 1.2 backwards compatibility at least ensures that the macro is present (even if the value has changed).

To clarify, I'm neutral whether OpenCL 3.0 devices should be required to define **OPENCL_VERSION** or not. When I said "it would make sense to me" I could perhaps have worded that as "I would not object if"... except if I used that wording, it might not be so clear that my viewpoint could potentially be changed.

Allow me to put it another way: I feel that OpenCL 3.0 devices should be _forbidden_ from defining **OPENCL_VERSION** as 0, 1, 110, 200, 210, 220 or 400. As it makes more sense to word things constructively, a few months ago I would have said that for OpenCL 3.0 devices, **OPENCL_VERSION** should be defined as 120, 300 or not at all. Now we are where we are, I would agree that it should probably be defined as 300 for OpenCL 3.0 devices, but deprecated.
