### ISSUE TITLE
Typo error in "3.2.1. Mapping work-items onto an NDRange" in OpenCL_API 3.0 spec

### ISSUE THREAD

**Issue by guoyinchen** [KhronosGroup/OpenCL-Docs#475]
"(wx, wy) = ( (gx sx Fx) / Sx, (gy sy Fy) / Sy )" should be changed to "(wx, wy) = ( (gx - Fx) / Sx, (gy - Fy) / Sy )" in below section
3.2.1. Mapping work-items onto an NDRange
Given a global ID and the work-group size, the work-group ID for a work-item is computed as:
(wx, wy) = ( (gx sx Fx) / Sx, (gy sy Fy) / Sy )

**Comment by bashbaug** [comment]
That's embarrassing!  I think there's an error in the preceding calculation as well.  I believe PR #476 fixes both of them - please take a look.  Thanks!
