### ISSUE TITLE
Discrepancy in clamp() definition for floating point types

### ISSUE THREAD

**Issue by EwanC** [KhronosGroup/OpenCL-Docs#49]
OpenCL_C.txt defines `clamp()` in terms of `fmin()`/`fmax()` https://github.com/KhronosGroup/OpenCL-Docs/blob/master/OpenCL_C.txt#L4739

However the [fp16](https://github.com/KhronosGroup/OpenCL-Docs/blob/master/ext/cl_khr_fp16.txt#L481) & [fp64](https://github.com/KhronosGroup/OpenCL-Docs/blob/master/ext/cl_khr_fp64.txt#L458) extensions define clamp in terms of `min()` & `max()`. This distinction affects the result when input `x` is NAN.

**Comment by bashbaug** [comment]
Interesting.  I'm guessing this is a typo, and the fp16 and fp64 extensions were supposed to be defined in terms of `fmin` and `fmax` as well.  This issue goes back as far as OpenCL 1.0 (!).

Note that when fp64 became an optional feature in the core OpenCL 1.2 spec, it added to the table of "common functions", which used `fmin` and `fmax`, vs. adding a separate special row using `min` and `max`.

One question for you and one for the OpenCL WG:

1. If we changed the extension docs to define `clamp` in terms of `fmin` and `fmax`, would this fix the discrepancy?

1. If we changed the extension docs to define `clamp` in terms of `fmin` and `fmax`, would this break anyone's shipping implementation?

For reference, here's the description for `fmin` (`fmax` is similar):

> Returns y if y < x, otherwise it returns x. If one argument is a NaN, fmin() returns the other argument. If both arguments are NaNs, fmin() returns a NaN.

vs. the description for `min` (`max` is similar):

> Returns y if y < x, otherwise it returns x. If x or y are infinite or NaN, the return values are undefined.

**Comment by EwanC** [comment]
Agree this looks like a typo. Using `fmin` and `fmax` terminology in the extension docs works for us and would fix the discrepancy.

**Comment by bashbaug** [comment]
I've create PR #53 that switches the description to `fmin` and `fmax`, if we decide that is the correct resolution to this issue.

**Comment by bashbaug** [comment]
In today's teleconference there was general agreement that we should switch the extension descriptions to use `fmin` and `fmax` as described in PR #53, but we are going to wait one more week to ensure this change won't break any shipping implementations.

**Comment by alycm** [comment]
PR #53 is merged, so closing this ticket.
