### ISSUE TITLE
Overlap formula not rendering correctly in API spec pdf

### ISSUE THREAD

**Issue by jlewis-austin** [KhronosGroup/OpenCL-Docs#494]
In 3.0.5, page 122, the CL_MEM_COPY_OVERLAP error description for clEnqueueCopyBuffer does not show the minus signs in the overlap inequalities:
_The regions overlap if src_offset ≤ dst_offset ≤ src_offset + size 1 or if dst_offset ≤ src_offset ≤ dst_offset + size 1._

**Comment by bashbaug** [comment]
The minus signs appear to be just plain missing from the spec source, so the HTML spec is affected as well.  I'll fix this.
