### ISSUE TITLE
Retrieving the link log in OpenCL >= 2.0

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/OpenCL-Docs#5]
In the OpenCL 1.2 specification, CL_PROGRAM_BUILD_LOG has the following description:

> Return the build, compile or link log for **clBuildProgram**, **clCompileProgram** or **clLinkProgram** whichever was performed last on *program* for *device*.
>
> If build status of *program* for device is CL_BUILD_NONE, an empty string is returned.

However, the later specifications (2.0, 2.1 and 2.2) all have the following description:

> Return the build or compile log for **clBuildProgram** or **clCompileProgram** whichever was performed last on *program* for *device*.
>
> If build status of *program* for device is CL_BUILD_NONE, an empty string is returned.

Is that an error or the expected behaviour?

Note that all other options to **clGetProgramBuildInfo** (for example CL_PROGRAM_BUILD_OPTIONS) still take **clLinkProgram** into consideration in the later specifications.

**Comment by bashbaug** [comment]
Yes, this is an error / omission, and it should be possible to retrieve the program build log after a call to clLinkProgram.  We'll get this fixed.

**Comment by pierremoreau** [comment]
Thanks for the confirmation, and for fixing it.

**Comment by pierremoreau** [comment]
Is there any update on when the specification will be fixed?

**Comment by pierremoreau** [comment]
Thank you for addressing this issue in the latest OpenCL 2.2 rev. 8 Specification.

Are there any plans on updating the OpenCL 2.0 and 2.1 Specifications as well?

**Comment by pierremoreau** [comment]
Friendly ping for fixing the OpenCL 2.0 and 2.1 Specifications.

**Comment by pierremoreau** [comment]
This has been addressed when moving to the unified specification; closing.
