### ISSUE TITLE
Clarification needed regarding overloads of atomic_fetch functions

### ISSUE THREAD

**Issue by StuartDBrady** [KhronosGroup/OpenCL-Docs#51]
In the OpenCL C 2.0 Specification § 6.13.11 Atomic Functions, in the subsection entitled "The atomic_fetch and modify functions", the following note appears:

> For **atomic_fetch** and modify functions with **key** = `add` or `sub` on atomic types `atomic_intptr_t` and `atomic_uintptr_t`, *M* is `ptrdiff_t`. For **atomic_fetch** and modify functions with **key** = `or`, `xor`, `and`, `min` and `max` on atomic types `atomic_intptr_t` and `atomic_uintptr_t`, *M* is `intptr_t` and `uintptr_t`.

I would like clarification of the statement regarding those functions with **key** = `or`, `xor`, `and`, `min` and `max`. Is this intended to be equivalent to the following statement? :

> For **atomic_fetch** and modify functions with **key** = `or`, `xor`, `and`, `min` and `max` on atomic types `atomic_intptr_t` and `atomic_uintptr_t`, functions with the following signatures are defined, together with the corresponding `_explicit` versions:
> ```
> intptr_t atomic_fetch_key(volatile atomic_intptr_t *object, intptr_t operand)
> uintptr_t atomic_fetch_key(volatile atomic_uintptr_t *object, uintptr_t operand)
> ```

Or, is it intended to be equivalent to the following statement? :

> For **atomic_fetch** and modify functions with **key** = `or`, `xor`, `and`, `min` and `max` on atomic types `atomic_intptr_t` and `atomic_uintptr_t`, functions with the following signatures are defined, together with the corresponding `_explicit` versions:
> ```
> intptr_t atomic_fetch_key(volatile atomic_intptr_t *object, intptr_t operand)
> intptr_t atomic_fetch_key(volatile atomic_intptr_t *object, uintptr_t operand)
> uintptr_t atomic_fetch_key(volatile atomic_uintptr_t *object, intptr_t operand)
> uintptr_t atomic_fetch_key(volatile atomic_uintptr_t *object, uintptr_t operand)
> ```

I note that in the C11 specification, it is stated in § 7.17.1.5 that *M* is `ptrdiff_t` for atomic address types. The previous statement to this makes reference to arithmetic operations, but does not state whether this includes or excludes the bitwise operations and the min and max operations. It is believable that the apparent limitation of the use of the `ptrdiff_t` type for *M* to the `add` and `sub` keys within OpenCL C attempts to correct an erratum in the C11 specification. If such an erratum is suspected, it may be worth following up with ISO/IEC JTC1/SC22/WG14.

**Comment by StuartDBrady** [comment]
Note that if functions with mixtures of signed and unsigned types for the min and max operations are intended in the specification (and I do not mean to imply whether this is the case), then it may make more sense to define the following functions:
```
intptr_t atomic_fetch_min(volatile atomic_uintptr_t *object, intptr_t operand)
uintptr_t atomic_fetch_max(volatile atomic_intptr_t *object, uintptr_t operand)
```
The functions listed above can all be implemented without the possibility of integer overflow of the returned value.

This is as opposed to the interpretation allowing mixtures of signed and unsigned types in my initial question, which would define instead:
```
uintptr_t atomic_fetch_min(volatile atomic_uintptr_t *object, intptr_t operand)
intptr_t atomic_fetch_max(volatile atomic_intptr_t *object, uintptr_t operand)
```
The former of these would result in integer overflow if the operand is negative, and the latter would result in integer overflow if the value pointed to is too large to be returned using the signed type.

**Comment by AnastasiaStulova** [comment]
The decision is not to support mixing the address types. I.e. the following overload wouldn't be valid

`uintptr_t atomic_fetch_min(volatile atomic_uintptr_t *object, intptr_t operand)`

**Comment by AnastasiaStulova** [comment]
Need conclusion on #65 to proceed.

**Comment by AnastasiaStulova** [comment]
**TODO**: update to the spec

**Comment by bashbaug** [comment]
Discussion summary:

The ambiguous sentence in the spec is:

> For atomic_fetch and modify functions with key = or, xor, and, min and max on atomic types atomic_intptr_t and atomic_uintptr_t, M is intptr_t and uintptr_t.

The proposed resolution is to explicitly disallow mixed signedness overloads.  A possible fix is:

> For atomic_fetch and modify functions with key = or, xor, and, min and max on atomic type atomic_intptr_t, M is intptr_t, and on atomic type atomic_uintptr_t, M is uintptr_t.

Note that Clang currently includes mixed-signedness overloads in some cases, specifically when 64-bit atomics are supported:

https://github.com/llvm/llvm-project/blob/master/clang/lib/Headers/opencl-c.h#L13491

This causes problems in practice though, such as: https://godbolt.org/z/dMG88s

So, removing the mixed-signedness overloads definitely seems like the right thing to do.

**Comment by AnastasiaStulova** [comment]
Btw will this only affect OpenCL 3 or other versions too?

Once this is changed in the spec we should create a clang bug to fix the implementation:
https://bugs.llvm.org/enter_bug.cgi?product=clang

**Comment by StuartDBrady** [comment]
> Btw will this only affect OpenCL 3 or other versions too?

My interpretation of this is that the specification was missing the "respectively", and that the header file in Clang is incorrect, due to misinterpretation of the specification. The specification had been intended to state:

> For **atomic_fetch** and modify functions with **key** = `or`, `xor`, `and`, `min` and `max` on atomic types `atomic_intptr_t` and `atomic_uintptr_t`, _M_ is `intptr_t` and `uintptr_t`, respectively.

However, I prefer @bashbaug's wording as it is more explicit.

So yes, this would affect all versions of OpenCL.

> Once this is changed in the spec we should create a clang bug to fix the implementation:
> https://bugs.llvm.org/enter_bug.cgi?product=clang

I'd be happy to do that.

**Comment by bashbaug** [comment]
Assigning to myself to create a PR with the changes described above.
