### ISSUE TITLE
Minimum version for opencl_unroll_hint attribute undocumented

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#536]
The specification (6.13.5) doesn't document a minimum version for the `opencl_unroll_hint` attribute. FWIW, CTS tests are only running on OpenCL 2.0 and later implementations.

**Comment by alycm** [comment]
`opencl_unroll_hint` was not in the 1.2 specification (rev 19), but is in OpenCL C 2.0 specification (rev 33).  So yes, OpenCL C 2.0 and later.

**Comment by bashbaug** [comment]
Discussed in the February 25th teleconference.  We're missing a version note for this feature, and it should be supported for OpenCL 2.0 and newer.  This is just a hint and implementations are free to ignore it, so there is no need for it to be any more optional, and CTS tests are already testing for it.

It'd also be a good idea to mention this in the changes from OpenCL 1.2 to 2.0 in [Appendix G](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#_summary_of_changes_from_opencl_1_2_to_opencl_2_0).
