### ISSUE TITLE
What state does a failed clSetKernelArg call leave kernel arguments in?

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#548]
The specification apparently says nothing about the state a failed call to `clSetKernelArg` leaves kernel arguments in? Are they (a few ideas):
1. Set to their previous value (or left unset)? This would put a high burden on implementations.
1. Forced unset? Probably the easiest for implementations and applications.
1. In an implementation-defined/undefined state? Leaves a lot of questions open. Is it valid to enqueue the kernel? Can applications ever be confident that a previously set argument still is? Is `clEnqueueNDRangeKernel` guaranteed to fail cleanly if arguments are invalid?

**Comment by kpet** [comment]
Discussed in the 2021/01/19 teleconference. Several classes of errors should be treated differently. In some cases (e.g. `CL_INVALID_KERNEL` or `CL_INVALID_ARG_INDEX`) it is clear that no state change should occur and we could easily provide strong guarantees to applications. In other cases, implementations can encounter an error after having already changed internal data structures which would make it hard to rollback changes and guarantee that the pre-existing arguments haven't changed as a result of the failed call to `clSetKernelArg`.

Next steps: categorise error codes and discuss again.

**Comment by jrprice** [comment]
I'll kick this off with a strawman that assumes most of the error codes are detectable early enough for us to be able to guarantee that they won't modify state in the spec. I've tested a couple of these cases on a few OpenCL implementations and this was indeed the case (i.e. I could still enqueue a kernel after clSetKernelArg failed), but that's far from exhaustive.

These errors are guaranteed to not modify state:
CL_INVALID_KERNEL
CL_INVALID_ARG_INDEX
CL_INVALID_ARG_VALUE
CL_INVALID_MEM_OBJECT
CL_INVALID_SAMPLER
CL_INVALID_DEVICE_QUEUE
CL_INVALID_ARG_SIZE
CL_MAX_SIZE_RESTRICTION_EXCEEDED
CL_INVALID_ARG_VALUE

These errors *may* modify state:
CL_OUT_OF_RESOURCES
CL_OUT_OF_HOST_MEMORY

Does anyone disagree with these categorizations?

**Comment by kpet** [comment]
You beat me to it :).

>I could still enqueue a kernel after clSetKernelArg failed

This doesn't mean that it's guaranteed to work or even that it will keep working on implementations that behave this way today.

Your proposed categorisation looks broadly fine to me.

I'm not sure about the first `CL_INVALID_ARG_VALUE` assuming they're taken in the order these error codes are listed in the 3.0 spec but that's mostly because what is precisely covered by that error code is unclear to me.

In cases where internal state may be modified, what do we want to say about set-ness (if that makes sense) of the arguments after the failed call to `clSetKernelArg`? I think we should require that the arguments be unset in that case so there is a guarantee that a call to `clEnqueueNDRangeKernel` would fail cleanly for example.

**Comment by jrprice** [comment]
> This doesn't mean that it's guaranteed to work or even that it will keep working on implementations that behave this way today.

Fair point.

> I'm not sure about the first CL_INVALID_ARG_VALUE assuming they're taken in the order these error codes are listed in the 3.0 spec but that's mostly because what is precisely covered by that error code is unclear to me.

Yes, this is a bit vague. To your point, one of my tests tries to pass an image object to a regular pointer argument - one OpenCL implementation returns `CL_INVALID_ARG_VALUE` and another returns `CL_INVALID_MEM_OBJECT`.

> I think we should require that the arguments be unset in that case so there is a guarantee that a call to clEnqueueNDRangeKernel would fail cleanly for example.

My suggestion was going to make this implementation-defined to keep implementation burden low ("if this error is returned, the kernel argument *may* have been invalidated"), but I'm also OK with the spec forcing the arg to be invalidated if that's what people prefer.

**Comment by bashbaug** [comment]
+1 for implementation-defined, especially since it will be hard to reliably generate one of the errors that may modify state.

**Comment by kpet** [comment]
True, this would be hard to test. Implementation-defined does mean that applications now need to know that they can't enqueue a kernel (or use any API call that relies on arguments being in a known state) on which a call to `clSetKernelArg` failed with _some_ error codes. It should be a fairly infrequent pattern so maybe it's not that bad.

**Comment by Kerilk** [comment]
To reflect what I said in the 2021-02-02 call, I think that a coherent and simple behavior, that allows simple error checking would be best. So I would lean toward:

> 2. Forced unset? Probably the easiest for implementations and applications.

I struggle to find a use case where I would have failed to set an argument and continue to proceed with an enqueue without taking additional measures to correct the situation.

**Comment by kpet** [comment]
Discussed in the 2021/02/02 teleconference:
- Concerns around making the behaviour implementation-defined. This case is likely to not be well-tested and a subsequent use of the kernel could result in crashes or hard-to-understand behaviour. Preference to unset the argument for which `clSetKernelArg` failed with one of the error codes for which mutating the kernel is allowed.
- Some implementers would rather keep the previous argument than unset arguments on failures for which modifying the state of the kernel is allowed.
- Proposal to allow either unsetting or keeping the previously set argument.
- Feedback from software vendors: applications are unlikely to handle this and unsetting might be the cleanest option.
- `clSetKernelArg` is performance-sensitive. We need to make sure that the success case remains fast but taking a performance hit in error cases is acceptable.

More discussions needed.

**Comment by kpet** [comment]
Discussed in the 2021/02/25 spec maintenance meeting. Tentative resolution: for errors that _may_ modify state, one of two behaviours is allowed:
- Keep the previous argument value so that it can be reused in further kernel enqueues
- Unset the argument such that a subsequent kernel enqueue fails with `CL_INVALID_KERNEL_ARGS` (recommended behaviour)
