### ISSUE TITLE
Use of .xyzw components in 8- and 16-element vectors

### ISSUE THREAD

**Issue by jrprice** [KhronosGroup/OpenCL-Docs#549]
Prior to OpenCL 3.0, the OpenCL C specification restricted use of the `.xyzw` vector components to vectors with <=4 components. Some cleanup to the "Vector Components" section performed in OpenCL 3.0 removed this restriction, and [CTS tests added in Sep'20](https://github.com/KhronosGroup/OpenCL-CTS/commit/02fc5809e37025e732faff768a4d8dde83628429) added test coverage for this.

In retrospect, it seems we don't have clear consensus in the working group as to whether this change was the right thing to do. The assumption at the time of the change was that this was a spec bug, and that all implementations would support this (Clang has for some time, for example). However, it's possible that some OpenCL implementations have enforced the restriction, especially since there was no CTS coverage until recently.

Options being considered:
1. Leave spec and CTS as is, asserting that this should always have been allowed.
2. Change the spec to keep the restriction for versions prior to 3.0 only (needs minor CTS work).
3. Revert the relaxation completely (needs spec and CTS changes).

Option 1 is the easiest (and is where my vote goes), but assumes that this doesn't break any shipping implementations that may not have run CTS recently. We should check this assumption in the WG if we decide to go this route.

**Comment by bashbaug** [comment]
I'm obviously a bit biased, in no small part becuase I wrote the CTS test linked above, but I vote for (1).  I would find it strange if 8-component and 16-component vectors were less capable than the smaller vectors (because they don't support the `.xyzw` syntax).

**Comment by Oblomov** [comment]
As a developer, I support 1. too. In fact, I wasn't even aware of the fact that older specs restricted their usage, I've always expected the `.xyzw` syntax to work with any vector width (of sufficient length), even though I've never actually _used_ it in practice for longer widths.

**Comment by bashbaug** [comment]
Thanks @Oblomov, your feedback is very valuable!

We discussed this in the February 25th teleconference and we're trending towards (1), but a few implementers wanted to double-check the behavior of their shipping implementations.  If we're OK with (1) we'll close this issue with no action needed.

**Comment by RuihaoZh** [comment]
Qualcomm is OK with option 1.

**Comment by bashbaug** [comment]
Closing this issue with no action required, as described above.
