### ISSUE TITLE
Unified SPIR-V Enviroment Spec Claims OpenCL 1.2 EP Must Support Pipes

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#55]
The unified OpenCL SPIR-V environment  spec says

> An OpenCL 1.2 Embedded Profile environment is guaranteed to support the following SPIR-V capabilities:
> * ...
> * Pipes
> * ...

The full profile section does not list Pipes, and Pipes weren't introduced into OpenCL until 2.0.   Suggested change is to just delete "Pipes" from the list.

**Comment by alycm** [comment]
Suggested change is in PR #56.

**Comment by bashbaug** [comment]
I just merged PR #56 so I am closing this issue.
