### ISSUE TITLE
OpenCL C: is sizeof(pipe) defined?

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#563]
See related CTS discussion: https://github.com/KhronosGroup/OpenCL-CTS/pull/1056#issuecomment-776763156

The OpenCL C spec doesn't currently say what the size of a pipe is.  Should it?

FWIW, in the current Clang implementation the size of a pipe is the same as the size of a pointer: https://godbolt.org/z/8xdbWz

The safest change is to specify that the size of a pipe implementation-defined, perhaps by adding pipe objects to this paragraph:

> The behavior of applying the sizeof operator to the bool, image2d_t, image3d_t, image2d_array_t, image1d_t, image1d_buffer_t, image1d_array_t, image2d_depth_t, image2d_array_depth_t, sampler_t, queue_t, ndrange_t, clk_event_t, reserve_id_t, and event_t types is implementation-defined.

**Comment by b-sumner** [comment]
I'd vote for that.  It was probably an oversight that pipes were not added there when pipes were introduced.

**Comment by AnastasiaStulova** [comment]
I agree, pipe should just go into that list.

**Comment by alycm** [comment]
Implementation defined makes sense to me.
