### ISSUE TITLE
Subgroups optionality clarification

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-Docs#568]
We're looking for some clarification around subgroups that has come up during the process of adding subgroups to an older device that does not support IFP.

The Subgroups section in "Appendix H (OpenCL 3.0 Backwards Compatibility)" currently states:

> `clGetDeviceInfo`, passing `CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS`
>
>Returns `CL_FALSE` if device does not support subgroups.

and

>`clGetDeviceInfo`, passing `CL_DEVICE_EXTENSIONS`
>
>Will not describe support for the `cl_khr_subgroups extension` if device does not support subgroups.

Our current interpretation of this is somewhat contradictory. If an implementation wished to support core subgroups but not the `cl_khr_subgroups` extension, `CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS` should be permitted to be `CL_FALSE` whilst still supporting subgroups.

Is our interpretation here correct - that a 3.0 implementation can support core subgroups, without IFP and without `cl_khr_subgroups`?

**Comment by bashbaug** [comment]
> Is our interpretation here correct - that a 3.0 implementation can support core subgroups, without IFP and without `cl_khr_subgroups`?

This matches my interpretation, yes:

* An OpenCL 2.1 or 3.0 device can support core subgroups with or without subgroup IFP.
* If an OpenCL 2.1 or 3.0 device does not support IFP then it cannot support the `cl_khr_subgroups` extension; in other words `cl_khr_subgroups` requires IFP.
* If an OpenCL 3.0 device does not support subgroups then it shall return `CL_FALSE` for `CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS`.

I'm open to suggestions to make this clearer - thanks!

**Comment by Jeremy-Kemp** [comment]
Thanks for clarifying.

In light of that, we'd like to propose the following changes:

Drop the statement:
>`clGetDeviceInfo`, passing `CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS`
>
>Returns `CL_FALSE` if device does not support subgroups.

Its valid for an implementation to support subgroups whilst not supporting IFP, so this device query is not a perfect indicator for overall subgroup support.

Regarding:
>`clGetDeviceInfo`, passing `CL_DEVICE_EXTENSIONS`
>
>Will not describe support for the `cl_khr_subgroups` extension if _device_ does not support subgroups.

We think there are two options for this one.

1. We could just drop the statement entirely. 
    1. The presence (or lack) of this extension should/does not impact an implementations ability to support core subgroups. In its current state, it reads as though core subgroups will not be present unless the extension is also present.
2. Alter the wording to: "Will not describe support for the `cl_khr_subgroups` extension if `CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS` returns `CL_FALSE` for _device_."

(I can open a PR if there is agreement about any proposed changes/alterations)

**Comment by bashbaug** [comment]
I'd prefer not to drop the statements above entirely since they're intended to document the expected behavior when the optional feature is not supported.  Do we need to make it clearer in the tables which rows are detection mechanisms to determine if the optional feature is available vs. which rows are implications when the feature is unsupported?

Informally, the first row is usually the detection mechanism ("May return XYZ indicating that feature foo is not supported") and subsequent rows are usually the implications ("Returns XYZ if feature foo is not supported"), but this is informal and perhaps not as clear as it could be.

**Comment by Jeremy-Kemp** [comment]
>Informally, the first row is usually the detection mechanism

I think this is really where the confusion stemmed from. If the reader (guilty) has not made the distinction between "feature is not supported" vs "**if** feature is not supported" then it can appear a little unclear.

I'll close this issue now as all the required detail is indeed already present. Thanks!

**Comment by bashbaug** [comment]
Should we add some variant of this text as a non-normative note in the intro to this appendix section?  I think that would be reasonable, and I agree the distinction is easy to miss:

> Informally, the first row is usually the detection mechanism ("May return XYZ indicating that feature foo is not supported") and subsequent rows are usually the implications ("Returns XYZ if feature foo is not supported"), but this is informal and perhaps not as clear as it could be.

**Comment by Jeremy-Kemp** [comment]
Yes I think this would be a useful clarification that could help reduce confusion around the nuances of described in the table(s).

Perhaps dropping the the wording after the clause?
>Informally, the first row is usually the detection mechanism ("May return XYZ indicating that feature foo is not supported") and subsequent rows are usually the implications ("Returns XYZ if feature foo is not supported")~~, but this is informal and perhaps not as clear as it could be~~.
