### ISSUE TITLE
cl_short min and max defines

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#58]
I initially filed this issue against the OpenCL headers, but perhaps it's actually a spec issue:

https://github.com/KhronosGroup/OpenCL-Headers/issues/43

In summary, the defines in the headers for cl_short minimum and maximum are:

````
#define CL_SHRT_MAX         32767
#define CL_SHRT_MIN         (-32767-1)
#define CL_USHRT_MAX        65535
````

In the spec, they are spelled out completely, e.g. `CL_SHORT_MAX`, so the spec and the headers are inconsistent.  However, in the OpenCL headers issue, we also observed that the defines in `<limits.h>` are abbreviated, e.g. `SHRT_MAX`.

Do we want to be consistent with `<limits.h>`, in which case the spec should be updated?  Or, do we want to spell out `SHORT` instead, in which case the headers should be updated?

**Comment by kpet** [comment]
I personally prefer the long names but changing the headers can break code, changing the spec can't... Consistency with `<limits.h>` seems desirable as well.

**Comment by b-sumner** [comment]
I vote for updating the spec and leaving the header as is.

**Comment by bashbaug** [comment]
I created PR #61 that renames these constants in the spec.

**Comment by bashbaug** [comment]
Closing this issue since the spec change was merged.
