### ISSUE TITLE
OpenCL3.0: Optionality of SPIR-V specialization constant support

### ISSUE THREAD

**Issue by jenatali** [KhronosGroup/OpenCL-Docs#602]
If I'm reading the specs correctly, I'm in a bit of a predicament at the moment.

I can support `cl_khr_il_program`, or the OpenCL 2.1 version of SPIR-V support, using my existing compiler infrastructure. However, to support OpenCL 2.2's SPIR-V required support, I need specialization constants, which requires improvements to the compiler.

I'd like to be able to have OpenCLOn12 run with both new and old versions of my compiler, at least for the time being. I'd also like it to claim support for OpenCL 3.0 (though not OpenCL *C* 3.0 without even more compiler improvements). As-is, when running with the new compiler, I can support OpenCL 3.0 and claim SPIR-V support, since I can implement specialization constants. With the old compiler, my options appear to be:
* Claim OpenCL 1.2 with the `cl_khr_il_program` extension. This might still be invalid because `cl_khr_il_program` is written targeting the CL 2.0 spec, so I'm not sure it's a valid extension to support on top of CL 1.2.
* Claim OpenCL 3.0 with SPIR-V, and just fail any attempt to set specialization constants.
* Claim OpenCL 3.0 without SPIR-V.

Is it intentional that OpenCL 3.0 requires specialization constants to be supported if SPIR-V is supported? Or should that be a separate piece of functionality, since it was added separately from IL programs and SPIR-V in general?

**Comment by bashbaug** [comment]
I recall discussing this in the working group and after quite a bit of debate we decided to require specialization constant support when SPIR-V is supported.  Some of our rationale was: all Vulkan implementations are requierd to support speciailization constants, so the implementation cost didn't appear so high that it was worth forking the ecosystem.

I wonder if it makes sense to develop some common tooling to "specialize" a SPIR-V module given a set of specialization constants to lower the cost of implementation further?  Tagging @dneto0 and @raunraun.

(There appears to be some specialization constant functionality in the [SPIR-V tools optimizer](https://github.com/KhronosGroup/SPIRV-Tools/#optimizer), but not a full "specializer" per se.)

**Comment by jenatali** [comment]
Understood. I don't expect to have real-world scenarios which use the older compiler interface, but wanted to keep it working because rebuilding the compiler is painful. So I think just not reporting SPIR-V support in that instance is probably fine for me. I just wanted to make sure that I was reading the spec correctly.

As for tooling for specialization constants, the SPIR-V tools optimizer does have what's needed, both to replace the default value of a specialization constant with another value, and to remove the "specialization" quality and replace them with actual constants - after that, regular optimizations are enough to completely specialize the module.
