### ISSUE TITLE
Behavior of CL_KERNEL_LOCAL_MEM_SIZE for local memory kernel arguments

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#612]
The description for `clGetKernelWorkGroupInfo(CL_KERNEL_LOCAL_MEM_SIZE)` says:

> Returns the amount of local memory in bytes being used by a kernel. This includes local memory that may be needed by an implementation to execute the kernel, variables declared inside the kernel with the __local address qualifier and **local memory to be allocated for arguments to the kernel declared as pointers with the __local address qualifier and whose size is specified with clSetKernelArg**.

Our implementation currently returns the size of local memory declared inside of the kernel, but not the size of any local memory kernel arguments (the part in **bold**).  I initially thought we should just consider this a bug and fix it, but it appears that other implementations have the same behavior.

Do we want to:

* Keep the spec as-is and fix the implementations?  This is debatably the right thing to do given that this text has been in the spec since OpenCL 1.0, but it means that many implementations in the wild are buggy.  Note: this also makes the value returned by this query non-invariant since it will depend on the value of a kernel argument, which is different than many (most? all?) of the other queries.
* Change the spec so the query returns only the size of local memory declared inside of the kernel and not the size of any local memory kernel arguments.  This reflects the behavior of the implementations I tested and keeps this query invariant, but it is a change to the documented behavior.

Any preferences?

Regardless, we clearly need a CTS test to cover this query!

**Comment by kpet** [comment]
FWIW, we're implementing this as per the spec and have been for many years. These are implementation bugs, unsurprising given the lack of CTS testing.

It's too late to change the spec, there's no knowing what applications have done with this and at least some implementations have followed the spec.

I've created https://github.com/KhronosGroup/OpenCL-CTS/issues/1235.

**Comment by pierremoreau** [comment]
>  Note: this also makes the value returned by this query non-invariant since it will depend on the value of a kernel argument, which is different than many (most? all?) of the other queries.

`CL_KERNEL_WORK_GROUP_SIZE` should be in the same boat, as the work group size most likely depends on the amount of local memory used including the local memory passed in as a kernel argument.

**Comment by bashbaug** [comment]
Thanks for the input, we'll fix this bug in our implementation.

Unless we want to clarify the spec to explicitly identify other queries that may be dynamic based on kernel arguments (e.g. `CL_KERNEL_WORK_GROUP_SIZE`, note that this is already explicitly stated for `CL_KERNEL_LOCAL_MEM_SIZE`) I think we can close this issue with no action required.

**Comment by bashbaug** [comment]
I don't see any reason to keep this issue open.  Thanks!
