### ISSUE TITLE
Missing error for wrong slice_pitch in clEnqueueReadImage

### ISSUE THREAD

**Issue by johnplate** [KhronosGroup/OpenCL-Docs#624]
The OpenCL spec lists the following requirement for the function `clEnqueueReadImage`:
"_slice_pitch_ in `clEnqueueReadImage` and _input_slice_pitch_ in `clEnqueueWriteImage` is the size in bytes of the 2D slice of the 3D region of a 3D image or each image of a 1D or 2D image array being read or written respectively. **This must be 0 if image is a 1D or 2D image.** [...]"

But _slice_pitch_ is not mentioned in the list of returned errors for these functions. What should a CL implementation do if _slice_pitch_ is not 0 for a 1D or 2D image? Return `CL_INVALID_VALUE`? Or ignore the error and return `CL_SUCCESS`?

If CL_INVALID_VALUE is returned, the CTS test `mem_host_flags` fails ...

**Comment by alycm** [comment]
`CL_INVALID_VALUE` would seem reasonable to me.

Our implementation does return `CL_INVALID_VALUE` for this case.  I just tested with an up-to-date CTS and we pass `mem_host_flags`, but perhaps the failure you see is connected to an optional type that we don't support.

However, the Intel GPU OpenCL implementation (which happens to be easy to run on my laptop) returns `CL_SUCCESS`.

**Comment by bashbaug** [comment]
> the Intel GPU OpenCL implementation (which happens to be easy to run on my laptop) returns `CL_SUCCESS`.

Yes, we don't seem to be checking for this condition in our CPU or GPU implementation.

I agree that `CL_INVALID_VALUE` seems reasonable and this is returned by at least one other implementation I tested.

**Comment by johnplate** [comment]
I found the root cause why the test failed for me. It gets the slice pitch from an earlier `clEnqueueMapImage`, which should 
 (but doesn't) return zero for a 1D image. I have reported that bug to NVIDIA. They didn't notice the bug so far, because they ignore the non-zero slice pitch in `clEnqueueReadImage`, so the test succeeds for them.
