### ISSUE TITLE
Add extra error condition to `clGetKernelSuggestedLocalWorkSizeKHR`

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-Docs#641]
Currently, there is no wording in the spec to describe an appropriate error code if `NULL` is given as the `suggested_local_work_size` argument to `clGetKernelSuggestedLocalWorkSizeKHR`.

We suggest the following wording:

> CL_INVALID_VALUE if suggested_local_work_size is NULL.

Alternatively a new error code could be added to cover this exact case.

**Comment by bashbaug** [comment]
Makes sense to me.  There are currently no other `CL_INVALID_VALUE` error codes returned by `clGetKernelSuggestedLocalWorkSizeKHR` so I don't think we need to introduce a new error code, and `CL_INVALID_VALUE` is used in other places in the spec when a value is `NULL` that shouldn't be.
