### ISSUE TITLE
Should vloada_half exist for scalars?

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#648]
See discussion:

* https://github.com/KhronosGroup/OpenCL-CTS/issues/1002
* https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/765

The latest versions of the spec are pretty clear that the scalar `vloada_half` does not exist, however:

* It did exist (by mistake?) in the OpenCL 1.1 spec (the description for vloada_half begins with "For n = 1, 2, 4, 8 and 16...").
* It is being tested (by mistake?) in the CTS tests, at least until https://github.com/KhronosGroup/OpenCL-CTS/pull/1293 is merged.
* It's accepted by many versions of Clang, e.g.: https://godbolt.org/z/PdsjsaaW3

Since it's in the CTS tests and Clang most existing implementations support it and there could be code in the wild that is using it.  Should we just support it?

Note that the scalar `vstorea_half` is NOT in the CTS tests but it is in Clang.  Should we support it too?

For Khronos folks, also see internal issue 259.

**Comment by alycm** [comment]
> It did exist (by mistake?) in the OpenCL 1.1 spec (the description for vloada_half begins with "For n = 1, 2, 4, 8 and 16...").

Currently the unified specification does not describe this fact.

**Comment by Kerilk** [comment]
While googling the issue I stumbled upon this page:
https://man.opencl.org/vloada_halfn.html

**Comment by StuartDBrady** [comment]
> While googling the issue I stumbled upon this page:
> https://man.opencl.org/vloada_halfn.html
> I don't know how relevant to the discussion it is though.

I see: this describes "vloada_half n", which should of course be "vloada_half<i>n</i>".  It starts with "For n = 1, 2, 4, 8 and 16", so includes the scalar case (although seemingly accidentally).

Note that there are separate pages for scalar vload_half and vstore_half, so the lack of a separate pages for scalar vloada_half and vstorea_half could be taken to imply that they were not intended to exist.

(Regarding the formatting of the <i>n</i>, the pages for vload_half<i>n</i> and vstore_half<i>n</i> are similar, and the page for vstorea_half<i>n</i> is even worse.  However, the vstorea_half</i>n</i> page only describes having n of 2, 3, 4, 8 and 16.)

**Comment by bashbaug** [comment]
We discussed this issue in the OpenCL teleconference on August 10th.  I think we decided:

* The spec is correct and there should not be a scalar `vloada_half` or a scalar `vstorea_half`.  The text in the OpenCL 1.1 spec was a mistake.
* We will merge the CTS PR to remove testing for `vloada_half` - https://github.com/KhronosGroup/OpenCL-CTS/pull/1293 (already done).
* We will remove both functions from the Clang header.

**Comment by AnastasiaStulova** [comment]
> Note that libclc in llvm-project will also need updating, but I do not intend to do this myself.

It would be nice to file a bug at least.

**Comment by StuartDBrady** [comment]
> > Note that libclc in llvm-project will also need updating, but I do not intend to do this myself.
> 
> It would be nice to file a bug at least.

Would anyone more closely involved with libclc like to volunteer for this?

**Comment by StuartDBrady** [comment]
There seems to be a minor discrepancy between the description here and discussion that has taken place, the OpenCL specifications and the CTS code that has now been removed.  The conclusion that the scalar `vloada_half` and `vstorea_half*` should not be tested and should be removed from Clang is unaffected by this, IMO, but to clear up any possible confusion, I will summarize this here.

The OpenCL 1.0 (non-unified) specification does not mention a scalar `vloada_half` function, nor does it mention scalar `vstorea_half*` functions.

The OpenCL 1.1 (non-unified) specification says "For _n_ = 1, 2, 4, 8 and 16" for both `vloada_halfn` and `vstorea_halfn*` functions, but if taken as written, this would have specified functions named `vloada_half1` and `vstorea_half1*`, which have never been declared in Clang, nor covered in conformance testing, in full or in part.

The OpenCL C 2.0 (non-unified) and OpenCL 3.0 (unified) specifications both say "For _n_ = 2, 4, 8 and 16", fixing the problem with the OpenCL 1.1 specification.

The CTS, however, included the code:
```
    // There is no aligned scalar vloada_half in CL 1.1
#if ! defined( CL_VERSION_1_1 ) && ! defined(__APPLE__)
    if (aligned && minVectorSize == 0)
        minVectorSize = 1;
```

The `minVectorSize` here is an the enumeration of the vector size, with enumeration values 0 ⇒ scalar, 1 ⇒ v2, 2 ⇒ v4, 3 ⇒ v8, 4 ⇒ v16, and 5 ⇒ v3.  Given the `#if`, the code was setting the minimum vector size to 2-elements for OpenCL versions _earlier_ than OpenCL 1.1, i.e. for OpenCL 1.0, only.  (Note: this is also done depending on the _API_ version as per `CL/cl_version.h`, not the language version.)  The code comment above this seems to say the opposite, i.e. that OpenCL 1.1 _doesn't_ have a scalar `vloada_half`, but that OpenCL 1.0 _does_—this comment should be disregarded entirely, IMO.

The CTS now sets a minimum `minVectorSize` value of 1 (i.e. 2-elements) when testing `vloada_halfn`, regardless of the OpenCL API version in use.

**Comment by bashbaug** [comment]
> The CTS now sets a minimum `minVectorSize` value of 1 (i.e. 2-elements) when testing `vloada_halfn`, regardless of the OpenCL API version in use.

Just to be extra-double-plus sure, this is the behavior we want, right?  No action required?

I've given up trying to figure out what the previous CTS code was trying to do, so as long as the current CTS code is correct I think we're all set.

**Comment by StuartDBrady** [comment]
> > The CTS now sets a minimum `minVectorSize` value of 1 (i.e. 2-elements) when testing `vloada_halfn`, regardless of the OpenCL API version in use.
> 
> Just to be extra-double-plus sure, this is the behavior we want, right? No action required?

Yeah, it's doubleplusgood, in my opinion. _No_ version of the specification ever provided these scalar functions under the names used in Clang and in the CTS, meaning any code relying upon them will have done so in error. The position for removing them from Clang and the CTS is in fact _more compelling_ than previously stated.

I have committed D108761 to the LLVM monorepo, with @AnastasiaStulova's approval of the change.

> I've given up trying to figure out what the previous CTS code was trying to do, so as long as the current CTS code is correct I think we're all set.

The current CTS code seems correct to me.

There _might_ be a case for introducing these scalar functions in some future version of the language for improved orthogonality, but note that there was never any testing for vstorea_half*, and mostly applications can simply use the following macro definitions if needed:
```
#define vloada_half      vload_half
#define vstorea_half     vstore_half
#define vstorea_half_rte vstore_half_rte
#define vstorea_half_rtz vstore_half_rtz
#define vstorea_half_rtp vstore_half_rtp
#define vstorea_half_rtn vstore_half_rtn
```

... or equivalent inline wrapper functions if necessary. In any case, introducing these that would be a discussion for another day.

I will leave this issue open for now pending discussion of the libclc change that is also required.

**Comment by bashbaug** [comment]
I don't think there's anything more for this group to do regarding this issue, and this issue has been open for well over a year.

There's a reference to a possible libclc change in the issue description, but if any libclc work is needed I think it should be tracked by a libclc issue.  Closing!
