### ISSUE TITLE
`clCompileProgram` validity with a program created from SPIR

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-Docs#659]
We're seeking clarification on the expected behaviour/steps required to compile and link a program created from a SPIR input (Note: **not** SPIR-**V** which is covered by wording regarding `clCreateProgramWithIL`)

We currently have these snippets of wording in the spec which we have interpreted to mean that calling `clCompileProgram` with a program object that was produced with `clCreateProgramWithBinary` where the supplied input was valid SPIR is an invalid operation:

> If program was created using clCreateProgramWithIL, then num_input_headers, input_headers, and header_include_names are ignored.

> CL_INVALID_OPERATION if program has no source or IL available, i.e. it has not been created with clCreateProgramWithSource or clCreateProgramWithIL.

However, our view is that a SPIR input _is_ valid IL and programs created with it via `clCreateProgramWithBinary` should be valid for use with `clCompileProgram`. If that explicitly by design, then is the expected behaviour that `clBuildProgram` must be called first, extracting binaries from that program and then re-creating a new program with those freshly extracted binaries?

There is a somewhat loosely related issue here: #520.

**Comment by bashbaug** [comment]
Interesting question.

If nothing else, I think we need to clean up the error description so it's more precise than "e.g. it has not been created with...".  One way to do that, I think, is to describe the behavior in terms of `CL_PROGRAM_BINARY_TYPE` ([link](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_PROGRAM_BINARY_TYPE)) and less about the API used to create the program.

I think we can go a couple of different ways here:

1. We take the spec literally.  The only valid programs for `clCompileProgram` are those with `CL_PROGRAM_BINARY_TYPE_NONE`, which is the program state immediately after calling `clCreateProgramWithSource` or `clCreateProgramWithIL`.
2. We take the interpretation above that SPIR input is valid for `clCompileProgram`, so the valid programs are those with either `CL_PROGRAM_BINARY_TYPE_NONE` or `CL_PROGRAM_BINARY_TYPE_INTERMEDIATE` (state added by the `cl_khr_spir` spec - [link](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#cl_khr_spir-additions-to-chapter-5)).
    a. Note, this is somewhat implied in the `cl_khr_spir` spec by "The program must be further processed with clCompileProgram or clBuildProgram."
    b. Note, we could either do this by relaxing the error condition in the SPIR spec to add `CL_PROGRAM_BINARY_TYPE_INTERMEDIATE` to the supported set of states, or we could describe the invalid states in the core spec.

I was about to say that if we go with (2) we should be sure to add CTS tests for this case, but it looks like we actually already test this!  See:

https://github.com/KhronosGroup/OpenCL-CTS/blob/v2021-08-16-00/test_conformance/spir/main.cpp#L6077

It's a little tricky to follow this test, but I do see programs created from SPIR that are compiled separately:

```
>>>> clCreateProgramWithBinary: context = 0x55ffbee2ab40, num_devices = 1
<<<< clCreateProgramWithBinary: returned 0x55ffbec4f410 -> CL_SUCCESS
Dumping program options to file (inject): /home/bashbaug/CLIntercept_Dump/test_spir/CLI_0000_00000000_0000_AE8EB66A_options.txt
>>>> clCompileProgram: program = 0x55ffbee2b040, pfn_notify = (nil)
<<<< clCompileProgram -> CL_SUCCESS
Dumping program options to file (inject): /home/bashbaug/CLIntercept_Dump/test_spir/CLI_0000_00000000_0000_AE8EB66A_options.txt
>>>> clCompileProgram: program = 0x55ffbec4f410, pfn_notify = (nil)
<<<< clCompileProgram -> CL_SUCCESS
>>>> clLinkProgram: context = 0x55ffbee2ab40, num_input_programs = 2, pfn_notify = (nil)
<<<< clLinkProgram: returned 0x55ffbec49980 -> CL_SUCCESS
```

So maybe it should be non-contentious to clarify that (2) is the desired behavior?

**Comment by Jeremy-Kemp** [comment]
Thanks for taking the time to investigate.

Internally, we were leaning towards updating wording in the SPIR extension spec to keep any changes self-contained to SPIR binaries themselves. That would align with point 2 above.

> b. Note, we could either do this by relaxing the error condition in the SPIR spec to add `CL_PROGRAM_BINARY_TYPE_INTERMEDIATE` to the supported set of states, or we could describe the invalid states in the core spec.

In the spirit of keeping changes within the SPIR spec, I'd think that adding wording to `clCompileProgram` to allow binaries whose state are `CL_PROGRAM_BINARY_TYPE_INTERMEDIATE` should make this case explicitly defined and resolve the ambiguity.

> I was about to say that if we go with (2) we should be sure to add CTS tests for this case, but it looks like we actually already test this!

Good find :). We'd missed this having taken a quick pass over CTS to find this case. This should give some confidence that modifying wording to the SPIR spec will not break any existing implementations.

**Comment by cycheng** [comment]
I have a question, regarding clCreateProgramWithBinary ([link](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#_creating_program_objects
))

> The program binaries specified by binaries will be loaded into the program object. They contain bits that describe one of the following:
> - a program executable to be run on the device(s) associated with context,
> - a compiled program for device(s) associated with context, or
> - a library of compiled programs for device(s) associated with context.

Does the spir binary goes to the first category?

**Comment by bashbaug** [comment]
> Does the spir binary goes to the first category?

I thikn SPIR binaries are in their own category.

The way I look at this is that there are five possible [states](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_PROGRAM_BINARY_TYPE), although only four of them can be entered via `clCreateProgramWithBinary`:

1. `CL_PROGRAM_BINARY_TYPE_NONE`: no program binary exists, output of `clCreateProgramWithSource` or `clCreateProgramWithIL`.
2. `CL_PROGRAM_BINARY_TYPE_INTERMEDIATE`: added by `cl_khr_spir`, possible output of `clCreateProgramWithBinary`.
3. `CL_PROGRAM_BINARY_TYPE_COMPILED_OBJECT`: output of `clCompileProgram` or `clCreateProgramWithBinary`.
    * I think this is your second category.
4. `CL_PROGRAM_BINARY_TYPE_LIBRARY`: output of `clLinkProgram` or `clCreateProgramWithBinary`.
    * I think this is your third category.
5. `CL_PROGRAM_BINARY_TYPE_EXECUTABLE`: output of `clBuildProgram` or `clLinkProgram`.
    * I think this is your first category.

Side note: this is an area of the spec that would benefit greatly from some pictures / diagrams!

**Comment by cycheng** [comment]
Thanks for the explanation! Very clear to me :)
