### ISSUE TITLE
Katex css and js files missing in OpenCL extensions

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenCL-Docs#677]
Many pages in the OpenCL/exntesions directory appear to be linking to non-existant Katex files (e.g.: https://www.khronos.org/registry/OpenCL/extensions/arm/cl_arm_controlled_kernel_termination.html):

- https://www.khronos.org/registry/OpenCL/extensions/katex/contrib/auto-render.min.js
- https://www.khronos.org/registry/OpenCL/extensions/katex/katex.min.css
- https://www.khronos.org/registry/OpenCL/extensions/katex/katex.min.js

On at least one page (possible more), some tables have very wide columns (see first table under 'Modifications to the OpenCL API Specification' on this page https://www.khronos.org/registry/OpenCL/extensions/arm/cl_arm_controlled_kernel_termination.html)

If reasonable, and the working group deems the code still readable, replace the following CSS would resolve this issue:

```
word-wrap: break-word;
```

with:

```
word-break: break-word;
```

**Comment by neiltrevett** [comment]
Paging @bashbaug and adding to next week's agenda

**Comment by bashbaug** [comment]
We have some katex stuff in the registry for the specs, e.g.:

https://github.com/KhronosGroup/OpenCL-Registry/tree/main/specs/3.0-unified/katex

Do we need to do something similar for the extensions?  Should we try to consolidate to one katex or are we fine sprinkling them around?

I'll play with `word-break: break-word;` and see how things look.

**Comment by outofcontrol** [comment]
Using one katex means the browser will use the cached version once loaded.

**Comment by bashbaug** [comment]
I tried `word-break: break-word;` and while it fixed the very wide tables I don't think the wrapping was readable:

![Screenshot from 2021-09-24 15-41-12](https://user-images.githubusercontent.com/14812095/134746766-f36f7392-2ed0-4612-a36f-4ea638a58645.png)

For the other specs we have scripts to generate asciidoctor attributes with zero-width spaces to break types and defines in good places - typically after an underscore.  It'd probably be easiest to wire this up for the extension specs also, unless there's some other clever CSS change we could try.

For katex, I think the path of least resistence will be to include a separate katex for the extensions as a short-term fix.  We could look at consolidating in the future but I'm not sure if it's worth it.  Note that we already have a separate katex for the 2.2 specs and the 3.0 specs:

* https://github.com/KhronosGroup/OpenCL-Registry/tree/main/specs/2.2/katex
* https://github.com/KhronosGroup/OpenCL-Registry/tree/main/specs/3.0-unified/katex

Same goes for Vulkan:

* https://github.com/KhronosGroup/Vulkan-Web-Registry/tree/main/specs/1.2-extensions/katex
* https://github.com/KhronosGroup/Vulkan-Web-Registry/tree/main/specs/1.2-khr-extensions/katex
* https://github.com/KhronosGroup/Vulkan-Web-Registry/tree/main/specs/1.2/katex
* ...

I can create a PR to add an extension katex if this is what we want to do.

**Comment by oddhack** [comment]
> For katex, I think the path of least resistence will be to include a separate katex for the extensions as a short-term fix. We could look at consolidating in the future but I'm not sure if it's worth it. Note that we already have a separate katex for the 2.2 specs and the 3.0 specs:

I believe this is an artifact of where the extension HTML documents are published. As generated by the 'html' target they are in the same directory as the API / language specs and should just work, but in the registry they are under extensions/VENDOR/*.html rather than specs/3.0-unified/html. You should be able to work around this by changing KATEXDIR locally for the extension HTML builds to e.g. ../../specs/3.0-unified/katex, similarly to how the refpages do it:

> $(MANHTMLDIR)/%.html: KATEXDIR = ../../katex

But you would only want to do this for the registry install, else the locally generated refpages won't have access to the locally installed katex when viewed locally. Maybe the right answer would be a conditional in the Makefile and an explicit build script that targets the registry repository clone.

Ideally we could just refer to the katex CDN instead of local copies, or at least a single Khronos-wide copy - we've previously run into problems with getting blocked by the CDNs due to excessive traffic originating from our specs, and doing this would also make it impossible to see math rendered offline correctly, which has always been a significant constraint at least for Vulkan.

A final workaround is to update the repository .htaccess to rewrite extensions/katex/* -> specs/3.0-unified/katex/* .

**Comment by outofcontrol** [comment]
We can host a copy of the katex on our own CDN (cdn.khronos.org), which is backed by Amazon Web Services. The only downside I can think of at this time, for hosting our own copy anywhere, is that others could use our copy of Katex for their own projects, with Khronos footing the traffic bill. At this time, we do not see this behaviour, and hopefully we won't.

**Comment by outofcontrol** [comment]
> For the other specs we have scripts to generate asciidoctor attributes with zero-width spaces to break types and defines in good places - typically after an underscore. It'd probably be easiest to wire this up for the extension specs also, unless there's some other clever CSS change we could try.

Possibly a good use case for &lt;wbr&gt; tag https://caniuse.com/wbr-element? Either via JS injection or modifying the ASCII code. This works as expected without modifying CSS:

```
<td class="tableblock halign-left valign-top">
    <p class="tableblock">
        <code>CL_<wbr>DEVICE_<wbr>CONTROLLED_<wbr>TERMINATION_<wbr>CAPABILITIES_<wbr>ARM</code>
    </p>
</td>
<td class="tableblock halign-left valign-top">
    <p class="tableblock">
        <code>cl_<wbr>device_<wbr>controlled_<wbr>termination_<wbr>capabilities_<wbr>arm</code>
    </p>
</td>
```

**Comment by bashbaug** [comment]
I created a PR that adds the katex files for extensions if we decide to go that route: https://github.com/KhronosGroup/OpenCL-Registry/pull/105

Regarding:

> Possibly a good use case for <wbr> tag https://caniuse.com/wbr-element?

That's exactly what the scripts do - they parse the XML file and create asciidoctor attributes for OpenCL types and enums that insert the `<wbr>` tag in the right places.  It's been working well for the OpenCL API spec, OpenCL C spec, and OpenCL SPIR-V environment spec, and we've just started using it in the extensions spec as well, though we haven't used it for the extensions specs yet.  I think it would be fairly straightforward to add it though, and it'd be yet another encouragement for vendors to include their extensions in the XML file!

Script reference: https://github.com/KhronosGroup/OpenCL-Docs/blob/master/scripts/gen_dictionaries.py#L126

**Comment by oddhack** [comment]
> I created a PR that adds the katex files for extensions if we decide to go that route: [KhronosGroup/OpenCL-Registry#105](https://github.com/KhronosGroup/OpenCL-Registry/pull/105)
> 
> Regarding:
> 
> > Possibly a good use case for  tag https://caniuse.com/wbr-element?
> 
> That's exactly what the scripts do - they parse the XML file and create asciidoctor attributes for OpenCL types and enums that insert the `<wbr>` tag in the right places. It's been working well for the OpenCL API spec, OpenCL C spec, and OpenCL SPIR-V environment spec, and we've just started using it in the extensions spec as well, though we haven't used it for the extensions specs yet. I think it would be fairly straightforward to add it though, and it'd be yet another encouragement for vendors to include their extensions in the XML file!
> 
> Script reference: https://github.com/KhronosGroup/OpenCL-Docs/blob/master/scripts/gen_dictionaries.py#L126

ISTM doing a .htaccess redirect is a better short-term bet - if you let me know the directory katex needs to be rooted at from the point of view of the extension HTML, I can set that up.

**Comment by oddhack** [comment]
Also, AFAICT none of the extensions actually *use* katex for anything at this point, so it's solely to pacify the link checkers :-)

**Comment by bashbaug** [comment]
> ISTM doing a .htaccess redirect is a better short-term bet - if you let me know the directory katex needs to be rooted at from the point of view of the extension HTML, I can set that up.

Works for me!  What do you need to know exactly?  I did a diff between the [katex](https://github.com/KhronosGroup/OpenCL-Docs/tree/master/katex) in this repo and the [katex](https://github.com/KhronosGroup/OpenCL-Registry/tree/main/specs/3.0-unified/katex) for the 3.0-unified spec in the OpenCL-Registry repo and they're identical, if that is helpful?

> Also, AFAICT none of the extensions actually _use_ katex for anything at this point, so it's solely to pacify the link checkers :-)

Yeah, this could be a chicken-and-egg problem though.  Now we'll at least have the option of using katex in the extension specs :-)

**Comment by bashbaug** [comment]
I believe this issue has been fixed by @oddhack's .htaccess redirects.  Can we close it?

**Comment by outofcontrol** [comment]
Agree.
