### ISSUE TITLE
Contradiction in clRetainDevice and clReleaseDevice

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#68]
The description of `clRetainDevice` says:

> clRetainDevice returns CL_SUCCESS if the function is executed successfully or the device is a root-level device.

But, in the list of error codes, it also says that it may return:

> CL_INVALID_DEVICE if device is not a valid sub-device created by a call to clCreateSubDevices.

`clReleaseDevice` is has a similar contradiction.  To resolve the contradiction I think the error condition should be removed, so it is valid to retain and release a root-level device.

**Comment by AlexeySachkov** [comment]
At the same time `clReleaseDevice` says that:

> If _device_ is a root level device i.e. a cl_device_id returned by *clGetDeviceIDs*, the _device_ reference count remains unchanged. 

https://github.com/KhronosGroup/OpenCL-Docs/blob/00422daf5dc013f21ab633479577c7cc225150e2/api/opencl_platform_layer.txt#L1328

Looks like error condition should be extended with something like: or if device is not a valid root level device

**Comment by bashbaug** [comment]
> Looks like error condition should be extended with something like: or if device is not a valid root level device

Good point.  `CL_INVALID_DEVICE` should still be a possible error code for `clRetainDevice` and `clReleaseDevice`, but only if *device* is not a valid device.  In other words, the error condition should be the same as for e.g. `clGetDeviceInfo`:

> `CL_INVALID_DEVICE` if *device* is not valid.
