### ISSUE TITLE
Whitespace formatting of `union` in `cl_image_desc`

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#682]
PR https://github.com/KhronosGroup/OpenCL-Docs/pull/671 synchronized scripts with Vulkan-Docs.

This has resulted in an odd whitespace change in the generated `cl_image_desc` struct in section 5.3.1.2.

Old:

![image](https://user-images.githubusercontent.com/2613275/134988482-afbf8307-c338-48e3-b246-d86aa2bf300c.png)

New:

![image](https://user-images.githubusercontent.com/2613275/134988511-542c03d0-646d-456c-aa51-db92e684cafd.png)

HTML diff:

```diff
@@ -11500,10 +11500,10 @@
     size_t                image_slice_pitch;
     cl_uint               num_mip_levels;
     cl_uint               num_samples;
-    <span class="keyword">union</span> {
+<span class="keyword">union</span> {
         cl_mem buffer;
         cl_mem mem_object;
-    };
+    }    ;
 } cl_image_desc;</code></pre>
 </div>
 </div>
```

I suspect that fixing this will be trivial, I just didn't have time to look right now.

**Comment by oddhack** [comment]
I'll fix it - may take a few days to get to.
