### ISSUE TITLE
`memory_scope_all_devices` missing from memory model description

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#697]
I was going to add `memory_scope_all_devices` to the `memory_scope` enum list in the reference pages: https://github.com/KhronosGroup/OpenCL-Docs/blob/bf8eccfacb2c543608e3867b9ae72cebaf00f674/man/static/enums.txt#L541-L547

But I realized that `memory_scope_all_devices` is completely absent from the memory model description, so it should be added everywhere (or described as an alias and assumed everywhere).

I do not believe such a change would be functional, as the enum is present in the OpenCL C specification.

**Comment by bashbaug** [comment]
IIRC the intent was that `memory_scope_all_devices` is an alias for `memory_scope_all_svm_devices`, and this is what is described in the OpenCL C spec:

`memory_scope_all_devices` | An alias for `memory_scope_all_svm_devices`. Requires support for OpenCL C 3.0 or newer and the `__opencl_c_atomic_scope_all_devices feature`.
:-- | :--

If this is the case, I think fixing this issue may be as simple as:

1. Clarify in the glossary that `memory_scope_all_svm_devices` and `memory_scope_all_devices` are equivalent and interchangeable.
2. Likewise, clarify in the OpenCL 2.0 memory model that `memory_scope_all_svm_devices` and `memory_scope_all_devices` are equivalent and interchangeable.

Then I think we can safely add the enum to the reference pages also.

Seem reasonable?

**Comment by alycm** [comment]
Yes that was the intent and what OpenCL C says, your proposed steps make sense.

**Comment by bashbaug** [comment]
PR #713 was merged.  I think this could be closed now?

**Comment by alycm** [comment]
Agreed, https://github.com/KhronosGroup/OpenCL-Docs/pull/713 resolved this, closing.
