### ISSUE TITLE
Allow passing non-generic pointers to vload/vstore in SPIR-V for OpenCL 1.2

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/OpenCL-Docs#7]
Currently, the OpenCL extended instruction set mandates **vload** to take generic pointers, and generic or constant pointers for **vstore**, regardless of the OpenCL version. However, generic pointers were only introduced in OpenCL 2.0 (and the OpenCL SPIR-V environment specification does mention the **GenericPointer** capability only starting from OpenCL 2.0), so one would end up with features in the SPIR-V that are not supported by the API, in an OpenCL 1.2 environment.

The OpenCL SPIR-V environment specification, the OpenCL extended instruction set or the OpenCL extension specification for OpenCL 1.2, should tweak the definition of **vload** and **vstore** when using *cl_khr_il_program* in OpenCL 1.2, to not take generic pointers, but instead accept private, local and global ones.

**Comment by bashbaug** [comment]
Hi @pierremoreau, this does sound like a bug, particularly for _cl_khr_il_program_ and OpenCL 1.2.  We're discussing the best way to resolve this issue in the OpenCL Working Group.

**Comment by pierremoreau** [comment]
Thanks @bashbaug for bringing this up to the OpenCL WG.

**Comment by pierremoreau** [comment]
Did the OpenCL WG have the opportunity to discuss this issue?

**Comment by pierremoreau** [comment]
Friendly ping, has this been discussed by the OpenCL WG? I skimmed through the newly released specification (OpenCL 2.2 rev. 8) but couldn't find any difference on the matter.

**Comment by pierremoreau** [comment]
Okay, great! Now the only thing left regarding this issue is to teach SPIRV-Tools validator about it; I’ll do that later.
Thanks!
