### ISSUE TITLE
Value returned for CL_IMAGE_ROW_PITCH and CL_IMAGE_SLICE_PITCH queries

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#763]
Both queries are currently defined rather loosely and the value returned by implementations is not validated by the CTS.

Taking the example of `CL_IMAGE_ROW_PITCH`, it is currently defined as:

> Return calculated row pitch in bytes of a row of elements of the image object given by image.

What "calculated" means isn't made explicit in the description for the query itself but several other sections of the specification describe that pitch "calculation" as "element size * width" which is indeed what most implementations seem to return for the query.

There are cases where a user can observe a linearly tiled representation of the image with a pitch that's different from this "calculated" pitch:
- When an image is created with a host pointer and `image_row_pitch` is set by the application to a non-zero value that is different from the calculated pitch
- When an image is created from a buffer and `image_row_pitch` is set by the application to a non-zero value that is different from the calculated pitch
- When an image that was not created with a host pointer is mapped for host access (the pitch is chosen and returned by the implementation).

This means an application that queries `CL_IMAGE_ROW_PITCH` may get a value back that has no relationship to any observable layout of the image data which makes that query essentially useless. The lack of CTS testing means that returning any value has been considered "conformant" so far.

I suggest we redefine those queries such that they return the pitches used for all application visible linearly tiled representations of the full image's data and update the CTS to require implementations adhere to the new behaviour:
- The data pointed to by an image's host pointer
- The data in a buffer the image was created from
- The mapped view of the image (when the entire image is mapped)

**Comment by bashbaug** [comment]
> * The data pointed to by an image's host pointer
> * The data in a buffer the image was created from
> * The mapped view of the image (when the entire image is mapped)

Can you say a bit more what the use-case is for the first item - the data pointed to by an image's host pointer?  Is this referring to the layout in the host_ptr when the image is created?  If so, we might need to be a little careful here, because the passed-in image pitch could remain useful for a CL_MEM_USE_HOST_PTR image, but wouldn't necessarily remain relevant for a CL_MEM_COPY_HOST_PTR image because the image data may be laid out differenlty when it is copied.

Regarding the last item, is there any requirement that mapping the image will return the same image pitch each time?  I think it will for a CL_MEM_USE_HOST_PTR image (though interestingly, this is listed among the items that "must be true" for clEnqueueMapImage), and it _probably_ will be for other images, but I don't see that this is a requirement.

I suppose this is my long-winded way of saying: I agree that the current definitions are loosely defined, but without a clear use-case in mind I'm not sure how to change them to make them more useful.

**Comment by jlewis-austin** [comment]
I agree that the use case for these queries is a key ingredient. The use of "calculated" in the description implies it's basically a helper query to do the computation for you based on image dimensions and format.
It feels arguably more useful for them to describe the layout which would be produced by clEnqueueMapImage, though as Ben notes, that would imply a guarantee that pitches returned by mapping are consistently predictable.
#674 also addresses ambiguity in how "calculation" is defined for the buffer to image case, where CL_DEVICE_IMAGE_PITCH_ALIGNMENT comes into play.

**Comment by kpet** [comment]
I was not coming to this from the point of view of specific use-cases per-se but rather observing that the definition of the queries was loose, that the CTS was not validating the results and, more importantly, that the value returned was in some case not linked to any pitch observable by or useful to applications.

> Is this referring to the layout in the host_ptr when the image is created?

Yes and the view of the data that is updated during map operations when CL_MEM_USE_HOST_PTR is used.

> If so, we might need to be a little careful here, because the passed-in image pitch could remain useful for a CL_MEM_USE_HOST_PTR image,

That's precisely one of the inconsistencies I'm highlighting and why I think the queries should return a pitch that corresponds to the application-observable layout of the image.

>but wouldn't necessarily remain relevant for a CL_MEM_COPY_HOST_PTR image because the image data may be laid out differenlty when it is copied.

Agree that an implementation might want to use a different layout internally and that's why I'm proposing that the values returned be clearly specified to only apply to application-observable linearly tiled views of the image data.

>Regarding the last item, is there any requirement that mapping the image will return the same image pitch each time?

I agree it's not a requirement and we could only guarantee this when the entire image is mapped. If we can agree to this, it would simplify the number of layouts an application has to care about but a) maybe that would take too much freedom away from implementations b) we have a clearly specified mechanism to specify pitches in that case.

>I think it will for a CL_MEM_USE_HOST_PTR image

Yes and that is required by the specification.

>without a clear use-case in mind I'm not sure how to change them to make them more useful.

Not really a use-case but with my proposal (possibly with the image mapping case dropped) would:
- Remove the inconsistencies between the value returned and the actual observable layout which would remove one source of confusion. At present one can create an image with a row pitch set to a given value, query the row pitch of that image and get a different value back, not great for clarity/consistency.
- Remove the need for applications to keep track of the pitches they passed. For example, if an application creates an image from a buffer, it may need to remember the pitches and pass them alongside the buffer/image. With this change it could query them back from the image.
- Guarantee that the behaviour of these queries is consistent across the OpenCL ecosystem going forward. At present an implementation that returns "42" always will be considered conformant.

>The use of "calculated" in the description implies it's basically a helper query to do the computation for you based on image dimensions and format.

Agree and that's what most of the implementations I've tested seem to be doing.

**Comment by kpet** [comment]
2022/03/08 teleconference: we decided to not require the pitches returned by `clEnqueueMapImage` when mapping an entire image created without `CL_MEM_USE_HOST_PTR` be the same as the pitches returned by `CL_IMAGE_ROW_PITCH` and `CL_IMAGE_SLICE_PITCH`. `clEnqueueMapImage` has a clear mechanism to return pitches for the mapping, this would only apply to the case where the entire image is mapped and would take freedom away from implementations for no clear benefits to applications.
