### ISSUE TITLE
Unify API Specification

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#77]
It seems a good idea to produce a unified OpenCL API specification that describes the OpenCL API for all versions of OpenCL.  This is in contrast to the current approach of having a separate specification per version.

Rationale:
* The OpenCL SPIR-V environment, and OpenCL extension and SPIR-V specifications are already unified and this is working well.
* Multiple versions of OpenCL are still be actively implemented and used, but the vast majority of specification fixes and clarifications are applied to the latest version.

I have already started prototyping this locally.  General points:
* Short introductory section describing the unified aspects.
* Use "missing before X.Y" and "deprecated by X.Y" language, roughly following the SPIR-V specification.
* Reintroduce descriptions previously removed due to deprecation.
* Investigating if cl.xml can be used to auto-generate some of the markers.
* More general "notes" for the architectural chapter on which version introduces features being discussed.

**Comment by alycm** [comment]
I have made a very small number of initial changes for how I think this could look: https://github.com/KhronosGroup/OpenCL-Docs/pull/78

Rendered PDF of that branch is attached here for convenience (can't seem to attach HTML to a GitHub issue): [OpenCL_API.pdf](https://github.com/KhronosGroup/OpenCL-Docs/files/3170333/OpenCL_API.pdf).

Immediate next steps are:
1. Try to use cl.xml to autogenerate the API entry point annotation.
2. Introduce macros to ensure that the language and formatting is consistent.

Any comments already welcome.

**Comment by alycm** [comment]
I'm coming back to this now, I've just pushed changes to https://github.com/KhronosGroup/OpenCL-Docs/pull/78 to auto-generate text for which version added or deprecated each API entry point based on cl.xml.

I'm not entirely sure if the automatic generation is worthwhile, my concern is that each deprecation note should probably reference the intended replacement feature, which is not information that can be taken from cl.xml.

The current script was just a quick thrown together thing, quite possibly a final solution would integrate with the existing generation scripts.

Next step is to re-add the functions that aren't present in the 2.2 text due to deprecation.

**Comment by oddhack** [comment]
> I'm coming back to this now, I've just pushed changes to #78 to auto-generate text for which version added or deprecated each API entry point based on cl.xml.
> 
> I'm not entirely sure if the automatic generation is worthwhile, my concern is that each deprecation note should probably reference the intended replacement feature, which is not information that can be taken from cl.xml.

Not at present (I did import the DEPRECATED macros from the CL headers into cl.xml, but the scripts don't do anything with them). But with minor XML schema and scripting enhancements, it could. We have a plan in Vulkan to make these enhancements, for similar reasons to yours, and perhaps that work could be reused. Take a look at issue 1802 in the internal gitlab vulkan repo and comment there, if this is of interest. I am keeping the schema and codebases synced up between XR, Vulkan, and CL, so these capabilities will eventually be available to CL anyway, but you might have some additional requirements to feed into the process.

**Comment by alycm** [comment]
I'm going to close this, there are a few outstanding tickets, but the primary task is complete.
