### ISSUE TITLE
Update extension spec to show cl_khr_extended_versioning promoted to core

### ISSUE THREAD

**Issue by jlewis-austin** [KhronosGroup/OpenCL-Docs#771]
cl_khr_extended_versioning functionality is promoted to core in 3.0, but there's no notes in [37. Extended versioning](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#cl_khr_extended_versioning) or [Appendix A: Extensions Promoted to Core Features](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#_extensions_promoted_to_core_features) to that effect.

**Comment by bashbaug** [comment]
There is one minor difference between cl_khr_extended_versioning and the equivalent functionality in core OpenCL 3.0 (relating to CL_DEVICE_OPENCL_C_NUMERIC_VERSION_KHR), but I still agree we should include this extension in Appendix A.

We should also update the [Quick Reference](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#_quick_reference) table, probably with text like there is for cl_khr_subgroups?

Something like:

> Core Feature in OpenCL 3.0 (with minor changes)

**Comment by jlewis-austin** [comment]
Good point, that makes sense to me.
