### ISSUE TITLE
cl_khr_extended_async_copies documents non-existant arguments

### ISSUE THREAD

**Issue by kbenzie** [KhronosGroup/OpenCL-Docs#774]
When reading the [cl_khr_extended_async_copies](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#cl_khr_extended_async_copies) spec language, I noticed a couple of oddities.

---

In the description of `async_work_group_copy_2D2D`, in the paragraph:

> The behavior of async_work_group_copy_2D2D is undefined if the num_elements_per_line or **src_stride** or **dst_stride** values cause the src or dst addresses to exceed the upper bounds of the address space during the copy.

**src_stride** and **dst_stride** are mentioned, however there are no arguments with these names in the `async_work_group_copy_2D2D` function signature. This paragraph seems to match one in the [`async_work_group_strided_copy`](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#async-copies) description in the core spec.

I think this paragraph could be completely removed.

---

In the description of `async_work_group_copy_3D3D`, in the paragraph:

> The behavior of async_work_group_copy_3D3D is undefined if the **src_total_size** or **dst_total_size** or src_offset or dst_offset values cause the src or dst addresses to exceed the upper bounds of the address space during the copy.

**src_total_size** and **dst_total_size** are mentioned, however there are not arguments with these names in the `async_work_group_copy_3D3D` function signature. I've not found any reference to these in the code spec, perhaps they are vestigial from a previous iteration of the extension spec?

I think this paragraph could be modified to remove mentions of these non-existent arguments:

> The behavior of `async_work_group_copy_3D3D` is undefined if the *src_offset* or *dst_offset* values cause the *src* or *dst* addresses to exceed the upper bounds of the address space during the copy.

**Comment by ayalz** [comment]
Thanks for spotting these discrepancies, which stem from modifying the addressing to use absolute “[src_|dst_]total_[line_length|plane_area]” parameters instead of relative “[src|dst]_stride” parameters, when moving from provisional to non-provisional versions. In the latter, addressing also considers newly introduced “offset” parameters. In general, _all_ parameters contribute to the computation of addresses and may lead to undefined behavior due to exceeding upper bounds, so propose to fix by simplifying the comments as follows:

Replace
>The behavior of async_work_group_copy_2D2D is undefined if the num_elements_per_line or src_stride or dst_stride values cause the src or dst addresses to exceed the upper bounds of the address space during the copy.
>The behavior of async_work_group_copy_2D2D is undefined if the src_total_line_length or dst_total_line_length or src_offset or dst_offset values cause the src or dst addresses to exceed the upper bounds of the address space during the copy.

with the simpler
>The behavior of async_work_group_copy_2D2D is undefined if the source or destination addresses exceed the upper bounds of the address space during the copy.

, and replace
>The behavior of async_work_group_copy_3D3D is undefined if the src_total_size or dst_total_size or src_offset or dst_offset values cause the src or dst addresses to exceed the upper bounds of the address space during the copy.

with the simpler
>The behavior of async_work_group_copy_3D3D is undefined if the source or destination addresses exceed the upper bounds of the address space during the copy.
