### ISSUE TITLE
cl_khr_terminate_context: Device property type and related constant missing

### ISSUE THREAD

**Issue by dertseha** [KhronosGroup/OpenCL-Docs#813]
The extension `cl_khr_terminate_context` ([documentation here](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#cl_khr_terminate_context)) specifies the `cl_device_info` of `CL_DEVICE_TERMINATE_CAPABILITY_KHR`.

This device property should be, as per documentation, of type `cl_device_terminate_capability_khr`, be a bit-field, and have currently one constant defined: `CL_DEVICE_TERMINATE_CAPABILITY_CONTEXT_KHR`.

Neither the xml, nor [the extension header](https://github.com/KhronosGroup/OpenCL-Headers/blob/7f216e8aa5317a71d91bed7edc83f3620dff763d/CL/cl_ext.h#L549-L563) declare these two.

I assume the [XML file](https://github.com/KhronosGroup/OpenCL-Docs/blob/46090155cc32baa68057d5f58a5bc7a302af3b33/xml/cl.xml) of this repository is the ultimate source of truth, which is why I am filing this issue here.

Side note: Comparing with the `cl_ext.h` from the Intel OpenCL SDK, which provides OpenCL 2.2, this information is missing there as well.

What is the state of this extension? Should these types & constants be defined, or is there a different way to acquire them?

**Comment by bashbaug** [comment]
Good catch, yes, `CL_DEVICE_TERMINATE_CAPABILITY_CONTEXT_KHR` does appear to be missing from both the XML file and the headers.  The (bitfield?) type `cl_device_terminate_capability_khr` is also missing.

I'm guessing code like this is correct (h/t @Oblomov):
https://github.com/Oblomov/clinfo/blob/master/src/ext.h#L235

This is something we should fix.  Should be straightforward assuming we're in agreement what the type and value should be.

**Comment by dertseha** [comment]
Thank you for the confirmation.

I'm also under the impression that it should be of type `cl_bitfield` (inferred to from the description text) and the one constant have the value of `(1 << 0)` (based on being the common starting point).
With Oblomov coming to the same assumption, that's two independent votes for that.

Is there a way to find out if any (major) runtime implements this, other than querying them? I did so for Intel CPU, Intel Graphics, and NVIDIA - none had it. Because if there's no known implementation, we can't break anyone's system.

**Comment by bashbaug** [comment]
> Is there a way to find out if any (major) runtime implements this, other than querying them? I did so for Intel CPU, Intel Graphics, and NVIDIA - none had it. Because if there's no known implementation, we can't break anyone's system.

I just had a look at the OpenCL gpuinfo.org database and I don't see any devices supporting this extension.

https://opencl.gpuinfo.org/listextensions.php

**Comment by alycm** [comment]
I was trying to do some archaeology on who may have implemented this extension, I didn't find anything beyond it being referenced in WebCL, but issue 15971 in the legacy internal bugzilla pointed out that:

We're also missing a value for the `CL_TERMINATED_KHR` execution status.  Logically that could either be `0x4` as the next available execution status, or it could be an error code.

Note that there is already a `CL_CONTEXT_TERMINATED_KHR` error code, but the extension specification text definitely refers to a separate `CL_TERMINATED_KHR` execution status.
