### ISSUE TITLE
transition CI to GitHub actions

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#832]
This repo is still using Travis to build the specs and perform consistency checks.  At some point it would be good to transition to GitHub actions instead.  We may be able to follow some of the same patterns used by Vulkan:

https://github.com/KhronosGroup/Vulkan-Docs/blob/main/.github/workflows/CI.yml

**Comment by kpet** [comment]
Also see https://github.com/KhronosGroup/OpenCL-Docs/issues/556 which links to a first attempt I'd made there: https://github.com/KhronosGroup/OpenCL-Docs/tree/actions (this was stalled on figuring out how to handle deployments IIRC).

**Comment by bashbaug** [comment]
Ah, thanks, I should have searched for a similar issue before adding this one.

Closing as a duplicate of #556.  Thanks!
