### ISSUE TITLE
consider adding the OpenCL logo to HTML specs

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#838]
We currently have the OpenCL logo on the front page of our PDF spec but not on our HTML spec.  The asciidoctor toolchain makes it a little awkward to add a logo to the HTML specs but the latest Vulkan spec figured out a way to do it:

https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html

Do we want to do something similar for the OpenCL specs?  If so, I have changes in a branch that are ready to go, modulo some final editorial tweaking.

**Comment by neiltrevett** [comment]
Strong +1 - important from both branding and trademark protection perspectives.
