### ISSUE TITLE
Invalid link for "missing before" etc reference page notes

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#849]
Now that the "missing before" and "deprecated by" version notes are included in the reference pages those words are links in the HTML to an anchor that doesn't exist in the reference page.  In the specification they link to the section that defines what they mean.

The most stylistically consistent thing to do would be to just not have those links in the reference page.

This is handled for existing words that are links (entry point names, error codes, etc) by having two dictionaries of macros.  One with links and one without.  Adding a `{missing-before}` and `{deprecated-by}` entry to those dictionaries may be the simplest way to handle this.

**Comment by bashbaug** [comment]
Possible dup of https://github.com/KhronosGroup/OpenCL-Docs/issues/726?

(I did a quick scrub of the issues yesterday so this was top of mind!)

**Comment by alycm** [comment]
Yes!  And it was even me that filed the issue.
