### ISSUE TITLE
Address space of return type

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#85]
Currently OpenCL C spec mentions that arguments to a function are implicitly in private addr space.

> The generic address space name for arguments to a function in a program, or local variables of a function is __private. All function arguments shall be in the __private address space.

Does this not apply to a return type? The spec further state that

>  There is no address space for function return values. Using an address space qualifier in a
> function return type declaration will generate a compilation error, unless the return type is
> declared as a pointer type and the qualifier is used on the points-to address space.

However, even if we don't allow explicitly qualifying the return type wouldn't it make sense to apply "generic" address space for a return type just the same as for arguments?

**Comment by b-sumner** [comment]
Do you mean that when compiling for 2.0, a function returning a pointer without an explicit address space should return a generic pointer?  Isn't that already what happens?

**Comment by AnastasiaStulova** [comment]
Sorry I was not precise. This bug covers non-pointer types. And by "generic" address space I mean implicitly qualified as private (just as arguments).

**Comment by b-sumner** [comment]
Thanks for clarifying.  There is only one possible address space for return values and that is the private address space, since each work item can call the function with different arguments, and receive different results.

**Comment by AnastasiaStulova** [comment]
TODO: need clarification in the spec.

**Comment by bashbaug** [comment]
Moving to the maintenance board - will be addressed by #405.

**Comment by AnastasiaStulova** [comment]
Closing this because we now have the following statement:
> * All function arguments as well as return values are in private address
    space.
