### ISSUE TITLE
`CL_DEVICE_HANDLE_LIST_KHR` used for many different purposes

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#864]
`CL_DEVICE_HANDLE_LIST_KHR` is used for the following purposes:
- Valid `cl_semaphore_info_khr` value, as passed to `clGetSemaphoreInfoKHR`
- Valid property value for `cl_semaphore_properties_khr`
- Valid property value for `cl_mem_properties`

This breaks naming conventions, creates a precedent for an enum with the same value but different meanings. Do we want to resolve this? We could:
- Do nothing.
- Introduce aliased so names have well defined purposes but all use the same enum value.
- Allocate dedicated enums for each purpose.

**Comment by nikhiljnv** [comment]
Thanks. Some comments -
This breaks naming conventions --> Agreed. CL_DEVICE_* is misleading for object property/info.
creates a precedent for an enum with the same value but different meanings --> May be in the sense that the same enum is passed to both semaphore as well as memory properties and as well as clGet*Info query. But, semantically it means the same thing, right i.e. List of devices that the object is associated with. Am I missing anything?

Second proposal (Introduce aliased names) seem reasonable and should help keep backwards compatibility in tact. 
While third option (Allocate dedicated enums for each purpose) looks much cleaner, a couple of issues -

- Will break backwards compatibility
- May lead to larger pool of enums for similar properties for different objects (Although, we already have [CL_MEM_CONTEXT](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_MEM_CONTEXT), [CL_QUEUE_CONTEXT](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_QUEUE_CONTEXT) etc which serve similar purpose)

Should we consider creating a new set of enum categories CL_OBJECT_* to represent common properties/attributes of objects that can be used across cl_mem, cl_command_queue, cl_semaphore_khr ? May be this will help avoid duplicating names for similar purpose.

**Comment by bcalidas** [comment]
We think the meaning is consistent in each of these usages. We don't have a problem with creating dedicated enums but we would recommend leaving the usage of CL_DEVICE_HANDLE_LIST_KHR unchanged.

**Comment by bashbaug** [comment]
Regarding the first two usages described in this issue:

> * Valid `cl_semaphore_info_khr` value, as passed to `clGetSemaphoreInfoKHR`
> * Valid property value for `cl_semaphore_properties_khr`

There are a few other enums that are used both as a "property" and as a "query", for example `CL_QUEUE_PROPERTIES`, `CL_QUEUE_SIZE`, and `CL_SAMPLER_NORMALIZED_COORDS`.  Should this type of reuse be acceptable?

**Comment by bashbaug** [comment]
Proposal:
* Define two new named enums to disambiguate usage: one for semaphores and one for memory objects.
* We will only define two new named enums, and will reuse the enum for the property and the query, consistent with the other parts of the spec.
* We will probably reuse the current enum value for one of the two new enum names, but we can discuss on the PR whether we define two new enum values, or use the current enum value for both new enum names.

I have the action item to propose a PR with these changes.

**Comment by nikhiljnv** [comment]
Closing as discussed in memory subgroup call on Sept 19, 2023.
