### ISSUE TITLE
Clarify Dedicated allocation requirements for external memory sharing

### ISSUE THREAD

**Issue by nikhiljnv** [KhronosGroup/OpenCL-Docs#866]
Clarify if external memory being imported in OpenCL needs to be created as a dedication allocation or not.

**Comment by bcalidas** [comment]
Is this in the context of importing allocations from Vulkan?

**Comment by nikhiljnv** [comment]
Just capturing some thoughts from the discussion during 05/16 teleconference -
1. Yes, the notion of dedicated vs non-dedicated memory essentially comes from Vulkan. 
2. As far as OpenCL specs are concerned,  we may need to clarify the expectations from base spec
- If memory to be imported from Vulkan is required to be dedicated
- How does dedicated vs non-dedicated memory affect inference scenarios
- What happens for corner cases where non-dedicated memory gets bound to different types of VkBuffer/VkImage at different point of time in its lifetime? Whether OpenCL continues to assume the same type/format that was specified at the time of import? Whether such memory needs to be reimported with appropriate type/format in order to match latest VkBinding?
Whether some of the scenarios with multiple bindings of the same Vk memory should be treated as application errors?
- Similar cases if the same memory is bound to different buffers/images at the same time.

**Comment by bcalidas** [comment]
Our input is that OpenCL does not need to be aware of whether the Vulkan memory is dedicated or not. The limitation comes from Vulkan. Some Vulkan  implementations will require that memory being exported is dedicated. 

If the Vulkan memory gets rebound, it could definitely bring up some problematic issues. Our input is that we should leave the spec as is and make it the application's responsibility to re-import into a new buffer/image should this happen. We can add a note to developers clarifying their expectations.

**Comment by nikhiljnv** [comment]
If some Vulkan implementations will require that memory being exported is dedicated, then it is automatically restricting the nature of memory being imported into OpenCL to be dedicated.
If that is the case, should we narrow down the scope of the base extension to assume that the memory being imported is always dedicated and handle non-dedicated memory import separately.
Currently, there is no way to distinguish between the two cases and the memory being dedicated or not seems to have direct implication in terms of ability to deterministically infer and support certain kind of layouts.

**Comment by bcalidas** [comment]
Would it be sufficient to state in the OpenCL spec, that should an imported mem_object be rebound to a different buffer/image in the external API, the OpenCL mem_object must be released and newly imported mem_object must be created.

This puts the responsibility of managing non-dedicated allocations ( where available for the exporting API) on the application.

**Comment by bashbaug** [comment]
> Would it be sufficient to state in the OpenCL spec, that should an imported mem_object be rebound to a different buffer/image in the external API, the OpenCL mem_object must be released and newly imported mem_object must be created.

Interesting idea.  Is this something we could detect and return an error for, or is this a case where behavior is undefined (or implementatation-defined) if it occurs?

Detecting an error seems challenging, though it might be possible in some cases as part of `clEnqueueAcquireExternalMemObjectsKHR`.

As an aside, we may want to be a little more precise what what an application can and cannot do via the external API while the memory object is acquired by OpenCL.  Currently, we just say: "Applications must release the memory objects that are acquired using clEnqueueReleaseExternalMemObjectsKHR before using them through any commands in the other API."

It would also be great to hear from application developers whether this restriction is acceptable.

**Comment by bcalidas** [comment]
An implementation could not reliably determine that an imported mem object had been rebound in an external API.  Therefore, correct usage of the APIs must be an application's responsibility. Most use cases will not need dynamic rebinding of memory. This should be considered a reasonable requirement.

**Comment by bashbaug** [comment]
> An implementation could not reliably determine that an imported mem object had been rebound in an external API. Therefore, correct usage of the APIs must be an application's responsibility.

OK, so this will be a case of undefined behavior.

I'm guessing we should make a spec update to say this explicitly, then?

**Comment by bcalidas** [comment]
We pushed a spec PR that makes this explicit.  In short, imae attributes are acquired at the time an image is cretaed and are not dynamically updated.

https://github.com/KhronosGroup/OpenCL-Docs/pull/970

**Comment by nikhiljnv** [comment]
Closing as discussed on memory subgroup call of October 17, 2023.
