### ISSUE TITLE
Invalid links to OpenCL spec docs in html description

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/OpenCL-Docs#87]
There is online version of the spec, example:
https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/enqueue_kernel.html

That seems to contain invalid links, example:
https://www.khronos.org/registry/cl/specs/opencl-2.1-openclc.pdf#page=162

Should we make sure to maintain the URL correctly or switch to just reference spec sections instead?

**Comment by bashbaug** [comment]
I don't think the OpenCL 2.1 C language spec PDF ever existed, so this has probably been a bug for some time.

Some possible solutions are:

1. Fix/regenerate the man pages to link to the correct OpenCL C spec instead.
1. Setup an HTML redirect so the link above redirects to the correct spec.  We do this already for old OpenCL 2.0 C language spec links:

https://www.khronos.org/registry/cl/specs/opencl-2.0-openclc.pdf redirects to:
https://www.khronos.org/registry/OpenCL/specs/2.2/pdf/OpenCL_C.pdf

I suspect (2) is easier, though (1) is debatably the right thing to do.

**Comment by oddhack** [comment]
> @oddhack, this issue was filed against the OpenCL 2.1 man pages. In summary, the link to the OpenCL C spec appears to be broken, and points to:
> 
> https://www.khronos.org/registry/cl/specs/opencl-2.1-openclc.pdf (which doesn't exist)
> 
> instead of:
> 
> https://www.khronos.org/registry/OpenCL/specs/2.2/pdf/OpenCL_C.pdf, or
> 
> https://www.khronos.org/registry/cl/specs/opencl-2.0-openclc.pdf, which links to the spec above.
> 
> How hard would it be to regenerate the man pages with the corrected link? Note that these are the "old" docbook-based man pages, and are not the "new" asciidoc-based man pages. Thanks!

It isn't hard to change the link, but that's only the first layer. The links from the 2.1 refpages land on specific page numbers in the PDF, and the page numbers were inserted manually when Kathleen & Dave originally constructed the pages (see xhtml/pageNumberLookup.rb), and those numbers are no longer correct. I haven't checked, but I suspect that's true of links into some of the other 2.1 spec documents from refpages, too - basically pageNumberLookup.rb needed to be updated when the PDF specs had pages shift around.

I don't think the effort to get the page numbers correct is justified. We could either fix the C language spec link (with wrong page numbers), or entirely remove the page numbers and just point at the beginning of the document. What would the WG like to see?

**Comment by bashbaug** [comment]
> I don't think the effort to get the page numbers correct is justified. We could either fix the C language spec link (with wrong page numbers), or entirely remove the page numbers and just point at the beginning of the document. What would the WG like to see?

We'll discuss this in next week's teleconference.

FWIW, I'd personally be fine fixing the spec link and removing the page numbers in the older docbook-generated reference pages.  I'd rather spend time making the newer asciidoc-generated reference pages amazing, so we all can use them instead..

**Comment by bashbaug** [comment]
Hi @oddhack, we discussed this issue in our teleconference and agreed that the effort to update the page numbers is not justified, but we would like to update the link and remove the page numbers.  Is this something you can do?  Let us know if you have any additional questions - thanks!

**Comment by oddhack** [comment]
@bashbaug see https://github.com/KhronosGroup/OpenCL-Registry/pull/65 . If you'll give this an upvote, I'll go ahead and merge it - I don't think a full WG review is required.

Note that all of the refpage links out to primary specs (not just those to the OpenCL C spec) drop the page numbers now.

**Comment by bashbaug** [comment]
The changes in https://github.com/KhronosGroup/OpenCL-Registry/pull/65 work for me - thanks!
