### ISSUE TITLE
Clarify on error code on clCreateBuffer failure with SVM buffer

### ISSUE THREAD

**Issue by tgowtham** [KhronosGroup/OpenCL-Docs#875]
The spec mentions below on the buffer allocation with a *host_ptr* from `clSVMAlloc`.

> If [clCreateBuffer](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#clCreateBuffer) or [clCreateBufferWithProperties](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#clCreateBufferWithProperties) is called with a pointer returned by [clSVMAlloc](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#clSVMAlloc) as its host_ptr argument, and [CL_MEM_USE_HOST_PTR](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_MEM_USE_HOST_PTR) is set in its flags argument, [clCreateBuffer](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#clCreateBuffer) or [clCreateBufferWithProperties](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#clCreateBufferWithProperties) will succeed and return a valid non-zero buffer object as long as the size argument is no larger than the size argument passed in the original [clSVMAlloc](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#clSVMAlloc) call

In the case of an invalid *size* argument being used between `clSVMAlloc` and `clCreateBuffer`, the spec is little unclear on what would be the error code that needs to be returned. `CL_INVALID_BUFFER_SIZE` seems to be a reasonable choice but then again the description for `CL_INVALID_BUFFER_SIZE` is very specific on the values of `size` for error scenario

> [CL_INVALID_BUFFER_SIZE](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_INVALID_BUFFER_SIZE) if size is 0 or if size is greater than [CL_DEVICE_MAX_MEM_ALLOC_SIZE](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_DEVICE_MAX_MEM_ALLOC_SIZE) for all devices in context.

Is `CL_INVALID_BUFFER_SIZE` a reasonable option for error code here, if it is can we add that to the spec.

**Comment by bashbaug** [comment]
This makes sense for me, and the implementations I've checked that return an error for this case seem to be returning CL_INVALID_BUFFER_SIZE.  Note though, not all implementations seem to be checking for this error case...

I've added this to our project board.  Assuming we agree that CL_INVALID_BUFFER_SIZE is the proper error code this should be a straightforward PR.

**Comment by tgowtham** [comment]
Thanks. Will wait on confirmation.
