### ISSUE TITLE
Clarify binary semaphore reset behavior for cl_khr_semaphore.

### ISSUE THREAD

**Issue by bcalidas** [KhronosGroup/OpenCL-Docs#883]
Binary semaphores must be in the correct state before they can be signaled or waited on. Clarify semaphore state transitions and when semaphores may be safely re-signaled or re-waited on.

**Comment by bcalidas** [comment]
At a high level binary semaphores must be in the correct state  for use in signal and wait commands. Semaphores can be in one of the following states -

- Reset state 
- Pending signal state
- Pending wait state
- Signaled state.

Semaphores are in the reset state when created . The other states can be explained as follows.

- A semaphore of the type CL_SEMAPHORE_TYPE_BINARY_KHR will be in the pending signal state when a clEnqueueSignalSemaphoreKHR command that references them is in the ready state or running state.
- A semaphore of the type CL_SEMAPHORE_TYPE_BINARY_KHR will be in the signaled state when a clEnqueueSignalSemaphoreKHR command that references them has reached the ended state or the complete state.
- A semaphore of the type CL_SEMAPHORE_TYPE_BINARY_KHR will be in the pending wait state when a clEnqueueWaitSemaphoreKHR command that references them is in the ready state or the running state.
- A semaphore of the type CL_SEMAPHORE_TYPE_BINARY_KHR will return to  the reset state when a clEnqueueWaitSemaphoreKHR command that references them has reached the ended state or the complete state.

**Comment by bcalidas** [comment]
When the clEnqueueWaitSemaphoreKHR command called on one or more semaphore objects of the type CL_SEMAPHORE_TYPE_BINARY_KHR, has reached the ended state, the corresponding semaphore objects are unsignaled and their state is reset. 
- A subsequent clEnqueueWaitSemaphoreKHR command on these semaphores may not transition to ready state without the semaphores having first transitioned to either a pending signal or signaled state.  Violation of this rule may lead to implementation-defined behavior.

- When the clEnqueueSignalSemaphoreKHR command called on one or more semaphore objects of the type CL_SEMAPHORE_TYPE_BINARY_KHR, has reached the ended state, the corresponding semaphore objects are signaled, and their state is set to signaled. 
- 
- A subsequent clEnqueueSignalSemaphoreKHR command on these semaphores may not transtion to ready state without the semaphores having first transitioned to either a pending wait or reset state. A Violation of this rule may lead to implementation-defined behavior.

**Comment by bashbaug** [comment]
Thanks for writing this up.  This is one of those interesting issues where the more you think about it the more interesting it gets.

Intuitively, I think I'd like to write code like this, which ping-pongs between two queues using semaphores to express the cross-queue dependencies:

```c++
    kernel.setArg(0, b1);   // dst
    kernel.setArg(1, b0);   // src
    q0.enqueueNDRangeKernel( kernel, cl::NullRange, cl::NDRange{gwx} );
    clEnqueueSignalSemaphoresKHR(q0(), 1, &semaphoreq0q1, NULL, 0, NULL, NULL);

    clEnqueueWaitSemaphoresKHR(q1(), 1, &semaphoreq0q1, NULL, 0, NULL, NULL);
    kernel.setArg(0, b0);   // dst
    kernel.setArg(1, b1);   // src
    q1.enqueueNDRangeKernel( kernel, cl::NullRange, cl::NDRange{gwx} );
    clEnqueueSignalSemaphoresKHR(q1(), 1, &semaphoreq1q0, NULL, 0, NULL, NULL);

    clEnqueueWaitSemaphoresKHR(q0(), 1, &semaphoreq1q0, NULL, 0, NULL, NULL);
    kernel.setArg(0, b1);   // dst
    kernel.setArg(1, b0);   // src
    q0.enqueueNDRangeKernel( kernel, cl::NullRange, cl::NDRange{gwx} );
    clEnqueueSignalSemaphoresKHR(q0(), 1, &semaphoreq0q1, NULL, 0, NULL, NULL);

    clEnqueueWaitSemaphoresKHR(q1(), 1, &semaphoreq0q1, NULL, 0, NULL, NULL);
    kernel.setArg(0, b0);   // dst
    kernel.setArg(1, b1);   // src
    q1.enqueueNDRangeKernel(kernel, cl::NullRange, cl::NDRange{ gwx });
    clEnqueueSignalSemaphoresKHR(q1(), 1, &semaphoreq1q0, NULL, 0, NULL, NULL);

    clEnqueueWaitSemaphoresKHR(q0(), 1, &semaphoreq1q0, NULL, 0, NULL, NULL);
    kernel.setArg(0, b1);   // dst
    kernel.setArg(1, b0);   // src
    q0.enqueueNDRangeKernel(kernel, cl::NullRange, cl::NDRange{ gwx });

    q0.flush();
    q1.flush();
    q0.finish();
```

For now at least, a full sample with this snippet can be found here:

https://github.com/bashbaug/SimpleOpenCLSamples/blob/32100307b5027bb66a34783fe3c18f2f3369a7c2/samples/11_semaphores/main.cpp#L155

I believe this code could very easily be incorrect (specifically, implementation-defined) based on the definitions above though, because the commands in the two queues could very easily remain "queued" until the explicit flush.  Even if explicit flushes were inserted, say, after each of the calls to clEnqueueSignalSemaphoresKHR(), this still wouldn't be enough to guarantee correctness, because the explicit flush will only guarantee that the semaphores are "submitted", not necessarily that they are "ready" or "running".

Do we really need the semaphore signal command to be "ready" or "running" (or further along, like "ended" or "complete") to be in the "pending signal" (or "signaled") state?  This seems rather difficult to guarantee without some other synchronization mechanism...

**Comment by bcalidas** [comment]
In the most recent discussion  on this issue, we have considered moving the requirements for semaphore state from the ready to the running state.


- When the clEnqueueWaitSemaphoreKHR command called on one or more semaphore objects of the type CL_SEMAPHORE_TYPE_BINARY_KHR, has reached the ended state, the corresponding semaphore objects are unsignaled and their state is reset.

- A subsequent clEnqueueWaitSemaphoreKHR command on these semaphores may not transition to submitted state without the semaphores having first transitioned to either a pending signal or signaled state. Violation of this rule may lead to implementation-defined behavior.

-  A semaphore of the type CL_SEMAPHORE_TYPE_BINARY_KHR will be in the pending signal state when a clEnqueueSignalSemaphoreKHR command that references them is in the submitted state, ready state or running state.

- A semaphore of the type CL_SEMAPHORE_TYPE_BINARY_KHR will be in the signaled state when a clEnqueueSignalSemaphoreKHR command that references them has reached the ended state or the complete state.

For these rules to work, user events must be disallowed when using semaphores. This would apply to both the clEnqueueSignalSemaphoreKHR and clEnqueueWaitSemaphoreKHR and the commands that these depend on.

**Comment by bcalidas** [comment]
Listing some open topics from the previous discussion.

1) Should semaphore states be merged so that we end up with only 2 states - pending signal and pending wait.
 >>> This could be problematic since the spec treats the -1 value for a sync fd as a semaphore that is in signaled state. It might be better to retain all 4 semaphore states.

2) Should EnqueueSignalSemaphore or EnqueueWaitSemaphore commands perform an implicit flush. 
>>> When the semaphores are used on the same queue a flush would not always be needed. It might be better to require the application to flush the queue after EnqueueSignalSemaphore or  EnqueueWaitSemaphore as necessary.

**Comment by bashbaug** [comment]
> When the semaphores are used on the same queue a flush would not always be needed.

This seems like a corner case.  Is this a usage model we should be designing around?  I agree this is valid but I'm having trouble seeing how this could be useful - thanks!

**Comment by bcalidas** [comment]
Working through an example of cross (in-order) queue semaphore usage with the new rules

semaphoreX -> starts in reset state

clEnqueueSignalSemaphore ( queue0, semaphoreX, ...,  &eventA) ; 
Flush(queue0);
 wait until eventA enters SUBMIITED state

clEnqueueWaitSemaphore (queue1, semaphoreX, ... &eventB) // valid since semaphoreX is now in pending signal or signaled state
Flush (queue1);
 wait until eventB enters SUBMIITED state

clEnqueueSignalSemaphore ( queue0, semaphoreX, ...,  &eventC) ;  // valid since semaphoreX is now in pending wait or reset state.

** When used correctly, semaphore state is determined by the event state of the most recent Signal or Wait command that acts on the semaphore.

**Comment by bashbaug** [comment]
Summary of offline discussion: could we add new semaphore queries to determine whether a semaphore signal has been submitted (and hence is in a pending signal state, safe to be waited upon) and whether a semaphore has been waited upon (and hence is safe to signal again)?

Short code snippet:

```c++
    kernel.setArg(0, b1);   // dst
    kernel.setArg(1, b0);   // src
    q0.enqueueNDRangeKernel( kernel, cl::NullRange, cl::NDRange{gwx} );
    clEnqueueSignalSemaphoresKHR(q0(), 1, &semaphoreq0q1, NULL, 0, NULL, NULL);
    //q0.flush();   // TBD: is this needed?
    do {
        clGetSemaphoreInfoKHR(semaphoreq0q1, CL_SEMAPHORE_PENDING_SIGNAL_KHR,
            sizeof(cl_bool), &pending_signal, nullptr);
        //if (pending_signal == false) q0.flush();  // Possible optimization?
    } while (pending_signal == false);

    clEnqueueWaitSemaphoresKHR(q1(), 1, &semaphoreq0q1, NULL, 0, NULL, NULL);
    //q1.flush();   // TBD: is this needd?
    do {
        clGetSemaphoreInfoKHR(semaphoreq0q1, CL_SEMAPHORE_PENDING_WAIT_KHR,
            sizeof(cl_bool), &pending_wait, nullptr);
        //if (pending_wait == false) q1.flush();    // Possible optimization?
    } while (pending_wait == false);
    kernel.setArg(0, b0);   // dst
    kernel.setArg(1, b1);   // src
    q1.enqueueNDRangeKernel( kernel, cl::NullRange, cl::NDRange{gwx} );
    clEnqueueSignalSemaphoresKHR(q1(), 1, &semaphoreq1q0, NULL, 0, NULL, NULL);
```

Things we would still need to consider and decide if we do this:
* What are the initial states for these queries?
* Do we need an explicit flush?
* Should all of this happen automatically as part of the signal or wait operations, or is it worth keeping the signal and wait decoupled from the queries and the loop?
* Keep in mind how any decisions we make today for binary semaphores will affect timeline semaphores in the (hopefully!) near future.

A compilable sample demonstrating this syntax is here (for now):
https://github.com/bashbaug/SimpleOpenCLSamples/blob/61bcc83761848b0264bf7064fb73fe7d65421e15/samples/11_semaphores/main.cpp#L166

**Comment by bcalidas** [comment]
Here are the notes from our testing with the binary semaphore pending signal and pending wait queries.

1) With the use of GetSemaphoreInfo queries that test the semaphore  for pending signal and pending wait states, an application may safely determine if a semaphore  is safe to use in a signal or wait command. The conformance tests were modified to use these queries and this approach worked even when user events were in the mix. 

2) The semaphores were created initially in pending wait state and they ping pong between pending signal and pending wait.

3) Even with the new semaphore state queries, an application must be careful not to call EnqueueSignal or EnqueueWait back to back on the same semaphore. In other words, EnqueueSignal and EnqueueWait commands must alternate.

4) When the semaphore is imported from an external API, the semaphore state will only be reliably known to OpenCL if the most recent command that acts on the semaphore is from OpenCL. Once again signal and wait commands must alternate. 
So something like - 
  // external API work

 clEnqueueWaitSemaphore (sem1);
 clGetSemaphoreInfo ( sem1, CL_SEMAPHORE_PENDING_WAIT_KHR); // This query returns a valid result since we have called clEnqueueWaitSemaphore and we are testing for Pending Wait state.

****
The prototyping also raised some additional questions which are listed here.

a) From the point of view of spec simplicity, it would be easiest to mandate the following behavior
    // semaphore sem1 starts off in pending wait state
   clEnqueueSignalSemaphore (q1, sem1,..);
   //     application must check if sem1 is in pending signal state
  clEnqueueWaitSemaphore (q2, sem1)  // sem1 mut be in pending signal state

However this may require application behavior that is unnecessarily conservative.  For instance, the sem1 state might need to be in pending signal only when the clEnqueueWaitSemaphore reaches submitted (or ready ) state. 

With that in mind, would it be better to define semaphore state requirements at the point where clEnqueueSignalSemaphore / clEnqueueWaitSemaphore commands reach submitted (or ready ) state. In this context, the semaphore state queries are only provided for developer convenience. 

b) If a developer is constructing a task graph by enqueueing commands to out of order queues, the idea of dynamically checking for semaphore state prior to enqueuing the next command may not be attractive. In this case, should we provide mapping of semaphore state to the state of the most recent EnqueueSignal or EnqueueWait commands. This would allow the developer to bypass the semaphore state queries. For example, a developer could conservatively infer that the semaphore would be in pending signal state if the previously enqueued  clEnqueueSignalSemaphore command was in one of running,  ended or completed states.

**Comment by keryell** [comment]
> For now at least, a full sample with this snippet can be found here: https://github.com/bashbaug/SimpleOpenCLSamples/blob/61bcc83761848b0264bf7064fb73fe7d65421e15/samples/11_semaphores/main.cpp#L166

@bashbaug I do not understand what you mean with these `q0()` and `q1()` in your code snippet by looking at https://github.khronos.org/OpenCL-CLHPP/classcl_1_1_command_queue.html

**Comment by bashbaug** [comment]
> I do not understand what you mean with these `q0()` and `q1()` in your code snippet [...]

Sorry about that, this syntax is used to mix code that primarily uses the OpenCL C++ bindings (so `cl::CommandQueue` and `q.enqueueNDRangeKernel(...)`) with code that hasn't been enabled throught the OpenCL C++ bindings just yet (like `clEnqueueSignalSemaphoresKHR`).  Basically, for an OpenCL C++ object (like `cl::CommandQueue`) the `operator()` gives you the underlying OpenCL object (so `cl_command_queue`).

Written with only the C OpenCL APIs, my code snip is essentially:

```c
    clSetKernelArg(kernel, 0, sizeof(b1), &b1);  // dst
    clSetKernelArg(kernel, 1, sizeof(b0), &b0);  // src
    clEnqueueNDRangeKernel(q0, kernel, 1, NULL, &gwx, NULL, 0, NULL, NULL);
    clEnqueueSignalSemaphoresKHR(q0, 1, &semaphoreq0q1, NULL, 0, NULL, NULL);
    ...
```

**Comment by bcalidas** [comment]
We applied the concept of clEnqueueSignalSemaphoreKHR not returning until the binary semaphore was in a pending signal state  and clEnqueueWaitSeamphoreKHR not returning until the binary semaphore was in a pending wait state. We were able to adapt our implementation and all of the relevant conformance tests and confirm that this approach works. We are also able to confirm that this allows for performant binary  semaphore implementations and usage for both in-order and out-of-order queues. 

We will be pushing a spec PR and conformance test PRs soon.

An added advantage, we were able to update the spec language without needed to explicitly mention the virtual semaphore states - pending signal and pending wait. The resulting guidance to developers on when it is safe to re-signal or re-wait on a semaphore is much cleaner.

The example from above now looks like this.

kernel.setArg(0, b1);   // dst
    kernel.setArg(1, b0);   // src
    q0.enqueueNDRangeKernel( kernel, cl::NullRange, cl::NDRange{gwx} );
    clEnqueueSignalSemaphoresKHR(q0(), 1, &semaphoreq0q1, NULL, 0, NULL, NULL); 
          // semaphoreq0q1 is now safe to wait on
    clEnqueueWaitSemaphoresKHR(q1(), 1, &semaphoreq0q1, NULL, 0, NULL, NULL);
         // semaphoreq0q1 is now safe to re-signal on
    kernel.setArg(0, b0);   // dst
    kernel.setArg(1, b1);   // src
    q1.enqueueNDRangeKernel( kernel, cl::NullRange, cl::NDRange{gwx} );
    clEnqueueSignalSemaphoresKHR(q1(), 1, &semaphoreq1q0, NULL, 0, NULL, NULL);
       // semaphoreq1q0 is now safe to wait on

**Comment by keryell** [comment]
> Basically, for an OpenCL C++ object (like `cl::CommandQueue`) the `operator()` gives you the underlying OpenCL object (so `cl_command_queue`).

Oh I see. This was the missing information about `operator()` I completely forgot about! Thanks.

**Comment by bcalidas** [comment]
The test PR that reflects this change is  https://github.com/KhronosGroup/OpenCL-CTS/pull/1675

**Comment by nikhiljnv** [comment]
Closing as discussed on Aug 22 subgroup call.
