### ISSUE TITLE
Add Semaphore Re-Import mechanism to cl_khr_external_semaphore_sync_fd

### ISSUE THREAD

**Issue by bcalidas** [KhronosGroup/OpenCL-Docs#888]
Sync fd semaphores must be in pending signal state before the fd  can be exported.  This means that in common usage across OpenCL and an external API, the semaphore must be continously released and a new semaphore Created.

Proposing a command to re-import semaphores for the Sync Fd handle type. This matches an API command that Vulkan has as well.

cl_int clImportSemaphoreSyncFdKHR(
    cl_semaphore_khr sema_object,
    int fd);

This switches the usage pattern from something like 

//Vulkan
CreateSyncFDSemaphore
    Submit Work
SignalSemaphore
Export Sync Fd

//OpenCL
CreateSemaphore from imported Sync Fd
Wait Semaphore 
      Submit Work
Release Semaphore

//Vulkan
       Submit Wortk
Signal Semaphore 
Export Sync Fd

//OpenCL
CreateSemaphore from imported Sync Fd
Wait Semaphore 
      Submit Work
Release Semaphore
......

To

//Vulkan
CreateSyncFDSemaphore
    Submit Work
SignalSemaphore
Export Sync Fd

//OpenCL
CreateSemaphore from imported Sync Fd
Wait Semaphore 
      Submit Work

//Vulkan
       Submit Work
Signal Semaphore 
Export Sync Fd

//OpenCL
Import Semaphore
Wait Semaphore 
      Submit Work

**Comment by bcalidas** [comment]
We considered re-import via ClCreateSemaporeKHR. However that could create confusion between the use of clCreateSemapore to create a  new semaphore and the use of clCreateSemaphore for re-import. We'll also have to find a way to pass in the current cl_semaphore_khr to clCreatesemaphore which would then have to return it. The overall flow seems very odd. The main objective of clImportSemaphoreSyncFdKHR() is to allow OpenCL to use a single cl_semapore_khr object across multiple frames.

**Comment by paulfradgley** [comment]
Simplifies a common use-case without adding much complexity to the API.
Seem good to me.

**Comment by nikhiljnv** [comment]
The spec PR is merged as part of #939.
CTS PR is here - https://github.com/KhronosGroup/OpenCL-CTS/pull/1854
OpenCL Header PR is here - https://github.com/KhronosGroup/OpenCL-Headers/pull/237

Is there anything left to track on this issue? Or can this be closed? We can continue to track CTS and Headers changes on above PRs.

**Comment by nikhiljnv** [comment]
Closing as discussed in OpenCL memory subgroup call on December 5th, 2023. Will track CTS and Headers changes on respective PRs.

**Comment by nikhiljnv** [comment]
https://github.com/KhronosGroup/OpenCL-Headers/pull/244 is merged. 
https://github.com/KhronosGroup/OpenCL-Headers/pull/237 is cancelled.
