### ISSUE TITLE
Missing `CL_COMMAND_BUFFER_CONTEXT_KHR` query

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#898]
All API objects support a query to obtain the context they were created within but command buffers currently do not. Is this intentional?

**Comment by EwanC** [comment]
I think this is probably an oversight, I can't remember any particular reason for omitting it. A command-buffer doesn't take a `cl_context` on creation, but neither does a `cl_kernel` and you can still query the context directly from `clGetKernelInfo`. So agree we should provide a `CL_COMMAND_BUFFER_CONTEXT_KHR` context query.

**Comment by kpet** [comment]
Yeah, it can be done via the command queue query but I agree that we should add a direct query. Symmetry with other objects is desirable. Thanks!
