### ISSUE TITLE
Is coarse-grained buffer SVM a required OpenCL 3.0 feature? 

### ISSUE THREAD

**Issue by pjaaskel** [KhronosGroup/OpenCL-Docs#912]
There are conflicting sentences related to this feature:

On page 35 (3.3.3) of https://registry.khronos.org/OpenCL/specs/3.0-unified/pdf/OpenCL_API.pdf it says:

> Coarse-Grained buffer SVM is required in the core OpenCL specification. The two finer grained approaches are optional features in OpenCL.

While on page 80 (CL_DEVICE_SVM_CAPABILITIES query) it says:

> The mandated minimum capability for an OpenCL 2.0, 2.1, or 2.2 device is CL_DEVICE_SVM_COARSE_GRAIN_BUFFER. For other device versions there is no mandated minimum capability.

(original discussion: https://github.com/pocl/pocl/issues/1093#issuecomment-1243945825)

**Comment by bashbaug** [comment]
SVM is not required for OpenCL 3.0.  This is a bug and the sentence cited above on page 35 should be updated (I thought I got all of these but apparently I missed one!).  I'll fix this.
