### ISSUE TITLE
Behaviour of `clCreate{Buffer,Image}WithProperties` when `CL_DEVICE_HANDLE_LIST_KHR` is provided but no external memory handle is

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Docs#916]
`CL_DEVICE_HANDLE_LIST_KHR` can be passed to `clCreateBufferWithProperties` or `clCreateImageWithProperties` to restrict which devices in the context import the external memory described by an external memory handle. The specification does not however state what happens when `CL_DEVICE_HANDLE_LIST_KHR` is provided (especially if the list does not contain all the devices that are part of the context) but no external memory handle is provided. A few possible options:
1. Ignore the device list.
2. Restrict which devices can use the memory object even though it wouldn't be imported (feels weird to introduce this with `cl_khr_external_memory`).
3. Report an error. We could add a rule stating that an external memory handle must be provided when `CL_DEVICE_HANDLE_LIST_KHR` is and require implementations to report `CL_INVALID_PROPERTY` otherwise.
4. Report an error when the device list does not contain all the devices that are in the context.

I think I have a preference for option 3. Thoughts?

**Comment by bashbaug** [comment]
(3) makes sense to me.  We could always relax the error condition if some other layered extension wants to do more with a `CL_DEVICE_HANDLE_LIST`, like that described in (2).
