### ISSUE TITLE
CL_DEVICE_COMMAND_BUFFER_NUM_SYNC_DEVICES_KHR not consistent with CL_DEVICE_COMMAND_BUFFER_SYNC_DEVICES_KHR

### ISSUE THREAD

**Issue by aharon-abramson** [KhronosGroup/OpenCL-Docs#924]
Regarding [this](https://github.com/KhronosGroup/OpenCL-Docs/blob/41fefb4b58cf2f046ca0f15a1853505823fbdb36/ext/cl_khr_command_buffer_multi_device.asciidoc?plain=1#L182), the description of CL_DEVICE_COMMAND_BUFFER_NUM_SYNC_DEVICES_KHR isn't consistent with CL_DEVICE_COMMAND_BUFFER_SYNC_DEVICES_KHR: whereas the latter includes sub-devices, the former doesn't.
I believe this isn't intentional.

**Comment by EwanC** [comment]
Good spot, created https://github.com/KhronosGroup/OpenCL-Docs/pull/925 the rectify this.

**Comment by EwanC** [comment]
Closing this issue as done now that https://github.com/KhronosGroup/OpenCL-Docs/pull/925 is merged
