### ISSUE TITLE
Links from 2.2 refpages don't open properly

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenCL-Docs#93]
Reported by Neil Trevett: When opening HTML links in the new OpenCL 2.2 refpages, they just result in a blank pane instead of the target document. Probably the right thing to do here is add target= attributes on the hyperlinks, so they open in a new tab. However, some people find this annoying, so raising the issue before deciding how to proceed.

**Comment by neiltrevett** [comment]
As discussed and agreed on OpenCL call of 2Jul19 - opening in a new Tab is acceptable behavior - so lets go ahead with adding target= attributes on the hyperlinks

**Comment by oddhack** [comment]
I've updated the refpages in the registry now, after the spec was regenerated with proper anchors, and AFAICT the links are opening properly in a new window.
