### ISSUE TITLE
Clarify dependencies between cl_khr_semaphore and cl_khr_external_semaphore

### ISSUE THREAD

**Issue by nikhiljnv** [KhronosGroup/OpenCL-Docs#944]
cl_khr_semaphore provides basic support for semaphore creation and wait/signal operations on them.
cl_khr_external_semaphore provides mechanism to import semaphores into OpenCL and export semaphores from OpenCL.
While being able to export semaphores from OpenCL requires OpenCL to be able to create semaphores and for some semaphore handle types like SYNC_FD, semaphores inherently require both import and export functionalities to work properly, for some other semaphore handle types (like OPAQUE_FD and WIN32) semaphores can be independently imported and/or exported. 
So, for implementations just willing to support importing semaphores in OpenCL, semaphore creation is strictly not required.

cl_khr_external_semaphore depends on cl_khr_semaphore, but [cl_khr_external_semaphore spec](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#cl_khr_external_semaphore) says (largely to facilitate import-only scenario described above)

_clCreateSemaphoreWithPropertiesKHR may return a NULL value on some implementations if sema_props does not contain an external semaphore handle type to import. Such implementations are required to return a valid semaphore when a supported external memory handle type and valid external semaphore handle is specified._

This makes cl_khr_semaphore base functional guarantees ambiguous as cl_khr_external_semaphore leads to subtracting functionality provided by required cl_khr_semaphore.

This issue is to track any spec / CTS changes needed to remove inconsistencies in the descriptions.

**Comment by bashbaug** [comment]
This issue looks similar to (if not the same as) https://github.com/KhronosGroup/OpenCL-Docs/issues/720.

**Comment by bcalidas** [comment]
From the spec  for cl_khr_external_semaphore - "The cl_khr_semaphore extension is required as it defines semaphore objects as well as for wait and signal operations on semaphores.".

This dependency makes sense and should be preserved.

**Comment by nikhiljnv** [comment]
As discussed in memory subgroup call on Sept 19, 2023, we agreed to remove below part from external semaphore spec 
and file  a separate issue for multidevice support.

clCreateSemaphoreWithPropertiesKHR may return a NULL value on some implementations if sema_props does not contain an external semaphore handle type to import. Such implementations are required to return a valid semaphore when a supported external memory handle type and valid external semaphore handle is specified.

**Comment by nikhiljnv** [comment]
Now that PR #976 is merged, can this issue be closed? Is there anything left that we need to continue to track on this issue?
