### ISSUE TITLE
Exporting semaphores created with multiple exportable handle types

### ISSUE THREAD

**Issue by nikhiljnv** [KhronosGroup/OpenCL-Docs#945]
As per [cl_khr_external_semaphore ](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#cl_khr_external_semaphore), clCreateSemaphoreWithPropertiesKHR can take a list of handle types via property CL_SEMAPHORE_EXPORT_HANDLE_TYPES_KHR  which can be used to export these semaphores later on.

Need to discuss -

- Are implementations already supporting this?
- Are there any use-cases where this is useful?
- Are there any restrictions wrt which multiple handle types can be passed and safely be used for the export?
- Should the list of handle types be restricted to just a single handle type if passing multiple handle types is problematic?

**Comment by bcalidas** [comment]
As per the Vulkan spec, it is possible to export multiple handle types for the same semaphore. This should be possible for OpenCL as well.

**Comment by bcalidas** [comment]
Vulkan has a query for compatible export handle types  ( per handle type ) that can be specified when creating a semaphore. The correct solution would be for OpenCL to have a comparable query. 
Something along the lines of 

GetDeviceSemaphoreInfo(
cl_device device, 
cl_external_semaphore_handle_type_khr  handle_type, 
param_name (CL_COMPATIBLE_SEMAPHORE_HANDLE_TYPES_KHR), 
size_t         param_value_size,
void *         param_value,
size_t *       param_value_size_ret
)

We would also need clCreateSemaphore to return a CL_INCOMPATIBLE_SEMAPHORE_HANDLE_TYPES_KHR error if an invalid combination of export handle types was specified when creating a semaphore.

**Comment by bashbaug** [comment]
To save others a search, the Vulkan "compatible handle types" information comes from [VkExternalSemaphoreProperties](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkExternalSemaphoreProperties.html):

```c++
typedef struct VkExternalSemaphoreProperties {
    VkStructureType                       sType;
    void*                                 pNext;
    VkExternalSemaphoreHandleTypeFlags    exportFromImportedHandleTypes;
    VkExternalSemaphoreHandleTypeFlags    compatibleHandleTypes;
    VkExternalSemaphoreFeatureFlags       externalSemaphoreFeatures;
} VkExternalSemaphoreProperties;
```

This is a structure that is returned by [vkGetPhysicalDeviceExternalSemaphoreProperties](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceExternalSemaphoreProperties.html).

Would we want an equivalent of `exportFromImportedHandleTypes` also?

For completeness, note that there is a similar query for compatible external memory handles also, but we do not support external memory export from OpenCL (yet).

**Comment by lakshmih** [comment]
We should clarify within the group whether it was the intention of the cl_khr_external_semaphore spec to support exporting from imported semaphores. We need to confirm that vendors currently support this behavior and that we have conformance test coverage for this.

**Comment by nikhiljnv** [comment]
Noting down some AIs from last week's discussion.
Check what different Vulkan implementations report as part of these queries to see if we have a case where multiple handle types are reported.
NVIDIA implementation seems to be reporting same and only handle for which these are queried.

**Comment by lakshmih** [comment]
Checked our Vulkan implementation and we return the single handle type for which the query was made as well.

**Comment by nikhiljnv** [comment]
Just capturing summary from OpenCL Memory subgroup call on Sept 19, 2023.

Discuss high-level direction and decide among following approaches -

- Add query mechanisms now allowing implementations to report compatible handle types or
- Restrict the usage to single handle type and defer query and multiple handle type usage for future when use-case arises.
- Do nothing. Leave the spec open as is.

**Comment by bcalidas** [comment]
We pushed a PR for the external semaphore spec which captures the above resolution. Please review https://github.com/KhronosGroup/OpenCL-Docs/pull/975 .

**Comment by bcalidas** [comment]
The latest commit to https://github.com/KhronosGroup/OpenCL-Docs/pull/975 reflects the most recent discussion from Oct 3, 2023. Only 1 semaphore handle type  can be exported and exporting of imported semaphores is not allowed.

**Comment by bcalidas** [comment]
Following the discussion on 10 Oct, 23,  we analyzed the likely usage patterns for sync_fd semaphores. we discovered that it was reasonable to have a single semaphore be used in a signal->wait->signal sequence across APIs. This would require the export of an imported semaphore from OpenCL. 

The sequence would look something like
   sem_a = clCreateSemaphore(..., external sync_fd_handle)
   clEnqueueWaitSemaphore (sem_a, ...)
   clEnqueueNDRangeKernel(...)
   clEnqueueSignalSemaphore(sem_a,...)
   clGetHandleForType (sem_a,..)
   \\ export sem_a to other API

This means that we have to allow the re-export of imported semaphores for at least some handle types. We don't see a need for the export handle type to be different from the import handle type. If no vendors currently need this handle type switching, we would like to write that restriction into the spec.

To give implementations flexibility on supporting export of imported  semaphore handle types, we could add another query if needed. Something along the lines of CL_PLATFORM_SEMAPHORE_EXPORTABLE_IMPORT_HANDLE_TYPES_KHR. This is only if such flexibility is needed. Otherwise, it is implicit that if a semaphore handle type appears in both the EXPORT_HANDLE_TYPES list and the IMPORT_HANDLE_TYPES list,,  export from import is possible.

**Comment by nikhiljnv** [comment]
#975 is merged now.
Listing down some of the open items from discussion during Memory subgroup call of October 17, 2023 -
1. How does an application know if a given semaphore is imported/exportable or not? 
Possible use-cases for libraries where entity creating semaphore may be outside of the library which is trying to understand if the semaphore was exportable. Some possible alternatives discussed
- Query the semaphore properties and check if an importable or exportable handle type property was specified at the time of semaphore creation
- The API querying semaphore handle to be exported for a given semaphore already returns an error if the semaphore was not exportable.
- Consider adding another convenience boolean query to report if a semaphore is exportable or not.

**Comment by bcalidas** [comment]
Adding some thoughts about how a library could infer the origin (internal or external ) of the semaphore.

1) The library could query the semaphore properties.  For a semaphore created from an external handle, the  import  handle type  would show up in the properties.
2) Going forward, if we add an extension that permits the re-export of an imported semaphore, we should also include a query ( as part of that extension) that reports the semaphore's origin.

**Comment by nikhiljnv** [comment]
As per discussion on Memory subgroup call of Nov 7, 2023, we agreed to add  a query to return boolean result to check if a semaphore is exportable or not.

**Comment by bcalidas** [comment]
We pushed a PR for the is_semaphore_exportable check.
https://github.com/KhronosGroup/OpenCL-Docs/pull/997

**Comment by nikhiljnv** [comment]
Now that spec PR is merged, can we close this issue? Can file a separate CTS issue if needed.

**Comment by nikhiljnv** [comment]
As discussed in Memory subgroup call on Novmeber 28th, 2023, closing this issue. Will file separate issue for CTS.
