### ISSUE TITLE
HTML errors in OpenCL specification

### ISSUE THREAD

**Issue by KhronosWebservices** [KhronosGroup/OpenCL-Docs#948]
There are 11 issues in the HTML of the OpenCL spec [here](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html).  The issues are listed here:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fregistry.khronos.org%2FOpenCL%2Fspecs%2F3.0-unified%2Fhtml%2FOpenCL_API.html

Fixing these issues will help us ensure the the major search engines can reliably pickup on these pages.

**Comment by bashbaug** [comment]
I created a PR that fixes all of these but one.  The remaining issue is in our `khronos.css` style sheet:

```
#footer { max-width: 100%; background-color: none; padding: 1.25em; }
```

This produces the error:

> Error: CSS: background-color: none is not a background-color value.

@oddhack, any preference how to solve this?  It looks like other Khronos repos that share this style sheet have the same issue (checked [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs/blob/2b7d9c9f65cde43580573a677490c3c7d099c09f/config/khronos.css#L366)).

**Comment by outofcontrol** [comment]
```
#footer { max-width: 100%; background: none; padding: 1.25em; }
```

would be appropriate.

**Comment by bashbaug** [comment]
Works for me!

**Comment by bashbaug** [comment]
Fixed by #952 - closing.

**Comment by oddhack** [comment]
> ```
> #footer { max-width: 100%; background: none; padding: 1.25em; }
> ```
> 
> would be appropriate.

@outofcontrol @bashbaug I'm wondering where you saw this error? I looked at the JS console in Chromium while loading the Vulkan single-page HTML spec, which contains the background-color: none CSS, and saw no errors reported (not arguing that it's valid, just trying to understand where it was diagnosed).

**Comment by bashbaug** [comment]
It came from the validator in the initial issue description - we haven't published a new spec (yet) so you can still see the errors:

> https://validator.w3.org/nu/?doc=https%3A%2F%2Fregistry.khronos.org%2FOpenCL%2Fspecs%2F3.0-unified%2Fhtml%2FOpenCL_API.html

**Comment by outofcontrol** [comment]
This month, we are finally seeing OpenCL in the registry appear in Google when searching for 'opencl spec'.
