### ISSUE TITLE
"nextafter" function mis-defined for double precision

### ISSUE THREAD

**Issue by gmlueck** [KhronosGroup/OpenCL-Docs#951]
The `nextafter` function is defined in [section 6.15.2](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#math-functions) "Math Functions" of the OpenCL C specification as:

> ```
> gentype nextafter(gentype x, gentype y)
> ```
>
> Computes the next representable **single-precision** floating-point value following x in the direction of y. Thus, if y is less than x, nextafter() returns the largest representable floating-point number less than x.

(Emphasis mine.)

This function is available for both `float` and `double` types, so I think it is incorrect for the description to specifically say that it returns the next **single-precision** floating-point value.  If the input type is `double`, I presume it should return the next double-precision floating-point value.  It seems like the wording could simply drop these words:

> Computes the next representable floating-point value following x in the direction of y. Thus, if y is less than x, nextafter() returns the largest representable floating-point number less than x.

FWIW, I'm on the Khronos SYCL WG, and I'm reporting this because we have similar wording in the SYCL specification.

**Comment by bashbaug** [comment]
Thanks!  Interestingly the extension spec is fine, both for double precision (for `cl_khr_fp64`) and for half precision (for `cl_khr_fp16`).

**Comment by bashbaug** [comment]
I created #953 to fix this.  It just drops "single-precision", as you suggested.

If SYCL decides to do something significantly different for some reason please let me know; it'd be nice to keep the descriptions roughly aligned.  Thanks!

**Comment by gmlueck** [comment]
> If SYCL decides to do something significantly different for some reason please let me know; it'd be nice to keep the descriptions roughly aligned.

Nope, we are making the same change in SYCL.
