### ISSUE TITLE
`clEnqueueSVMFree` doesn't state that the `pfn_free_func` parameter needs to point to a thread-safe callback

### ISSUE THREAD

**Issue by karolherbst** [KhronosGroup/OpenCL-Docs#977]
Is this intentional? All the other callback functions are required to be thread-safe by the specification, this seems to be the only exception.

Or is there a different part of the spec stating that all callback functions are thread-safe by default?

**Comment by karolherbst** [comment]
Same for `clEnqueueNativeKernel`

**Comment by bashbaug** [comment]
I've unhooked #1016 by editing the PR description.  I think it can be merged now without closing this issue.

Did we want to update `clEnqueueNativeKernel` also?

**Comment by karolherbst** [comment]
> Because the "callback" functions for clEnqueueSVMFree and clEnqueueNativeKernel are placed into an OpenCL queue though, the application has control when they are called. It's certainly safest if they are thread-safe, but you could also imagine cases with a single in-order queue where it would be perfectly fine for the function not to be thread-safe.
> 
> The current text we are using now, in all of the functions with callbacks, is:
> 
> > This callback function may be called asynchronously by the OpenCL implementation. It is the application's responsibility to ensure that the callback function is thread-safe.
> 
> Maybe this should be weakened slightly, for clEnqueueSVMFree and clEnqueueNativeKernel only, to say something like:
> 
> > This callback function may be called asynchronously by the OpenCL implementation. It is the application's responsibility to ensure that the callback function is thread-safe, **if needed**.
> 
> Am I over thinking this?

It depends on how much freedom we want to give implementations here. Rusticl e.g. offloads all processing (except validation) of enqueued commands to a worker thread to unblock application threads as quickly as possible. So the callback to `clEnqueueSVMFree` could race with whatever SVM allocation the application is doing even for single in-order queue applications.

Having all callbacks guaranteed to be thread-safe makes it easier on the runtime so it doesn't have to do any locking around calling callbacks itself. It's is also very hard for the runtime to judge with what application state a callback might race on. Is it just between the same callback? Is it all callbacks to `clEnqueueSVMFree`? Is it any CL callback? Is it even more?

It is much easier for applications to answer that question. And if the spec states "this may be called asynchronously" , it already kinda says "the runtime might call it from any thread at any time". Does OpenCL guarantee that those callback functions are only called after the queue was flushed explicitly? What if the runtime does implicit flushing, because the queue filled up too much or for any other reasons?

So I don't really see the application being in full control on when those callbacks are called at all, even single in-order queue ones.

**Comment by bashbaug** [comment]
OK, so I might be over thinking this.  😄 

To be clear though, by "under application control" I'm imagining something like this:

```
// Initially, I can assume that my free function will not be called.

// As soon as the free function is enqueued it can be called anytime.
clEnqueueSVMFree(queue, my_free_function);

// If this is an in-order queue, I can enqueue another free, and it will only execute after the first free has completed.
clEnqueueSVMFree(queue, my_free_function);

// This will ensure that both frees are complete and can be called directly from the host again.
clFinish(queue);
```

The main thing I want to avoid is an application thinking they **must** to add locks or mutexes around every function that gets enqueued, especially "native functions".  Maybe that's still covered though by "it is the application's responsibility to ensure that the callback function is thread-safe"?  Is there some way we could rephrase this, or perhaps add a footnote, to make the intent more clear?

**Comment by karolherbst** [comment]
I mean.. that's what's meant by "This callback function may be called asynchronously by the OpenCL implementation". The CL spec doesn't guarantee that the calling thread is the same as the one the application used to call the CL API.

**Comment by SunSerega** [comment]
I think a while ago I empirically determined some implementation (NV?) to have 4 working threads allocated for event callbacks. Probably shared for other callbacks too. So even in the case of 2 consecutive `clEnqueueSVMFree` on the in-order queue, I guess it might currently be possible for both callbacks to be running at the same time?

**Comment by bashbaug** [comment]
> I think a while ago I empirically determined some implementation (NV?) to have 4 working threads allocated for event callbacks. Probably shared for other callbacks too. So even in the case of 2 consecutive clEnqueueSVMFree on the in-order queue, I guess it might currently be possible for both callbacks to be running at the same time?

I think this is a great example why I think that the functions passed to clEnqueueSVMFree and clEnqueueNativeFunction might be different than other callback functions, like the event callback functions.  Going back to my previous example, and expanding it slightly to include event callbacks:

```c++
// Remember: queue is an in-order queue!

// As soon as the free function is enqueued it can be called anytime.
event0 = clEnqueueSVMFree(queue, my_free_function0);
clSetEventCallback(event0, CL_COMPLETE, my_event_callback0);

// If this is an in-order queue, I can enqueue another free, and it will
// only execute after the first free has completed.
event1 = clEnqueueSVMFree(queue, my_free_function1);
clSetEventCallback(event1, CL_COMPLETE, my_event_callback1);

clFinish(queue);
```

I think all of the following can execute concurrently (meaning, at the same time):
* my_event_callback0 and my_free_function1
* my_event_callback0 and my_event_callback1
* my_event_callback0, my_event_callback1, and the host call to clFinish
* my_free_function0 and the host calls to clSetEventCallback, the next clEnqueueSVMFree, and clFinish
* my_free_function1 and the host call to clFinish

The following can NOT execute concurrently though:
* my_free_function0 and my_event_callback0 - the event callback is only called when the event is complete.
* my_free_function1 and my_event_callback1 - same as above, the event callback is only called when the event is complete.
* my_free_function0 and my_free_function1 - because this is an in-order queue the previous command calling my_free_function0 must complete before the next command calling my_free_function1 can start.

Does this make sense?

**Comment by karolherbst** [comment]
> > I think a while ago I empirically determined some implementation (NV?) to have 4 working threads allocated for event callbacks. Probably shared for other callbacks too. So even in the case of 2 consecutive clEnqueueSVMFree on the in-order queue, I guess it might currently be possible for both callbacks to be running at the same time?
> 
> I think this is a great example why I think that the functions passed to clEnqueueSVMFree and clEnqueueNativeFunction might be different than other callback functions, like the event callback functions. Going back to my previous example, and expanding it slightly to include event callbacks:
> 
> ```c++
> // Remember: queue is an in-order queue!
> 
> // As soon as the free function is enqueued it can be called anytime.
> event0 = clEnqueueSVMFree(queue, my_free_function0);
> clSetEventCallback(event0, CL_COMPLETE, my_event_callback0);
> 
> // If this is an in-order queue, I can enqueue another free, and it will
> // only execute after the first free has completed.
> event1 = clEnqueueSVMFree(queue, my_free_function1);
> clSetEventCallback(event1, CL_COMPLETE, my_event_callback1);
> 
> clFinish(queue);
> ```
> 
> I think all of the following can execute concurrently (meaning, at the same time):
> 
>     * my_event_callback0 and my_free_function1
> 
>     * my_event_callback0 and my_event_callback1
> 
>     * my_event_callback0, my_event_callback1, and the host call to clFinish
> 
>     * my_free_function0 and the host calls to clSetEventCallback, the next clEnqueueSVMFree, and clFinish
> 
>     * my_free_function1 and the host call to clFinish
> 
> 
> The following can NOT execute concurrently though:
> 
>     * my_free_function0 and my_event_callback0 - the event callback is only called when the event is complete.
> 
>     * my_free_function1 and my_event_callback1 - same as above, the event callback is only called when the event is complete.
> 
>     * my_free_function0 and my_free_function1 - because this is an in-order queue the previous command calling my_free_function0 must complete before the next command calling my_free_function1 can start.
> 
> 
> Does this make sense?

It does, just that it still doesn't change anything in regards to thread-safety. A data race can occur on any data, not just data shared between the callbacks.

Those callbacks could access global data of the application and access to that should be locked regardless of the queue being in-order or not. The application might make the assumption that callbacks will be called in-order, but they have to make sure data races do not happen regardless as the runtime might call the callback on a different thread.

Like what if the application just tracks SVM allocations like this?

```c
static my_hash_set svm_ptrs;

void my_free_function(cl_command_queue queue, cl_uint num_svm_pointers, void* svm_pointers[], void* user_data)
{
    context = clGetCommandQueueInfo(queue, CL_QUEUE_CONTEXT);
    for (int i = 0; i < num_svm_pointers; i++) {
        // DATA RACE: runtime might call this asynchronously
        my_hash_set_remove(&svm_ptrs, svm_pointers[i]);
        clSVMFree(context, svm_pointers[i]);
    }
}

void* my_alloc_function(...)
{
    void *ptr = clSVMAlloc(...);
    // DATA RACE: runtime might call `my_free_function` asynchronously
    my_hash_set_add(&svm_ptrs, ptr);
    return ptr;
}

int main()
{
    ...
    void *svm_ptr = my_alloc_function(....);
    ....
    clEnqueueSVMFree(queue, my_free_function, svm_ptr);
    clFlush(queue);

    void *new_svm_ptr = my_alloc_function(....);
    ....
}
```

The question is mostly do we allow code like this or not? And then we have to decide if the runtime is responsible for locking or not. But locking has to happen regardless, the question is just who needs to do it.

**Comment by bashbaug** [comment]
OK, I think I'm sold, and we should add similar text to clEnqueueNativeKernel also.  I'll create a PR to add:

> It is the application's responsibility to ensure that the callback function is thread-safe.

As a note for future-me, or anyone else who finds this issue, "ensure that the callback function is thread-safe" doesn't _necessarily_ mean that the callback function needs to have locks, though in many cases it does (and it's certainly safest to have them).

**Comment by bashbaug** [comment]
I think we fixed this in the latest spec release, so I am closing this issue.  If there's still something we missed, please let us know, and I'll reopen this issue - thanks!
