### ISSUE TITLE
Semantics of structure pointer chains in cl_khr_command_buffer_mutable_dispatch

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenCL-Docs#990]
Noticed this in passing and wanted to make sure people were aware of some of the pitfalls we have encountered in Vulkan as a result of initially underspecifying how these behave, then later trying to resolve different implementation choices. A non-exhaustive list of things to consider:

- Behavior when multiple instances of the same extending struct (possibly with different values) are included
- Behavior when passing chained structures through layers which may not be aware of some of them, and which may need to modify others for their own purposes
- Behavior when passing chained structures valid for extensions that are not enabled / supported in the context they are passed through

Not saying Vulkan has all the answers, but if this approach takes off in OpenCL too, it seems likely you will encounter some or all of the same issues downstream.

**Comment by EwanC** [comment]
Thanks for flagging this up Jon, I wasn't aware of these pitfalls Vulkan has encountered. Will take a look into them and see how we can update the cl_khr_command_buffer_mutable_dispatch wording

**Comment by EwanC** [comment]
Structure pointer chains were removed from cl_khr_command_buffer_mutable_dispatch in https://github.com/KhronosGroup/OpenCL-Docs/pull/1045, closing this issue
